### ISSUE TITLE
Unable to use setSelectionRange on HTML Editor to set cursor pointer at the begining

### ISSUE THREAD

**Issue by v2amruta** [Sibiraj-S/ngx-editor#101]
I want to set focus with cursor at the begining of HTML Editor on click of button in angular 4.

**Comment by Sibiraj-S** [comment]
If I understood correctly you want to focus your cursor on the editor by an external action, when code edit mode is active

**Comment by Sibiraj-S** [comment]
@v2amruta do follow the issue guidelines that why I have it there. 😕

**Comment by v2amruta** [comment]
@Sibiraj-S  : I didn't get your last comment.

**Comment by Sibiraj-S** [comment]
I provided a template/format to post an ISSUE but you haven't followed that.
