### ISSUE TITLE
[Feature]: Custom image upload function

### ISSUE THREAD

**Issue by VladimirHumeniuk** [sibiraj-s/ngx-editor#103]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [X] Feature request
- [X] Documentation issue or request

## Description

It would be amazing if we could use custom functions to load pictures, and not just send POST requests to the address specified in the configuration. For example, I use Firebase in my application, and just a post request to save a picture to the FIrestore is not enough. 

Also, huge thanks for you work. Editor is pretty nice.

### Version Information

```
ngx-editor: 3.3.0
angular: 5.2.9
```

**Comment by Sibiraj-S** [comment]
@VladimirHumeniuk . Glad to hear that.

>I use Firebase in my application, and just a post request to save a picture to the FIrestore is not enough.

What would it be. More information will be easier to get going. Like an example.

**Comment by VladimirHumeniuk** [comment]
@Sibiraj-S To solve the problem of downloading files to Firebase, I had to add an additional button with next to the editor. The function of uploading a file to the Firebase Storage is as follows:
![image](https://user-images.githubusercontent.com/20288162/38931168-f7bbc9cc-431a-11e8-8ad8-4828eda666e3.png)

Its return downloadURL, which I copy and paste into the editor.

**Comment by Sibiraj-S** [comment]
I can't have multiple methods, but what possible is

1. A custom toolbar as previously said
2. An api can be exposed that inserts image to the editor.


What do you think?

**Comment by Sibiraj-S** [comment]
Will try to solve these issues ASAP, but I was little tied up to other tasks here. so may take a little time than expected. 

🍻

**Comment by VladimirHumeniuk** [comment]
@Sibiraj-S cool, thanks.

**Comment by cerealexx** [comment]
@Sibiraj-S Is there a way to get a file path from the uploader instead of a buffer? That way it'd be quite easy to build an endpoint with Firebase Functions.

**Comment by khernik93** [comment]
I've added a PR with the upload event implementation - feel free to approve it, or discard if it doesn't really suits your architecture ;-)

**Comment by sibiraj-s** [comment]
With v5. you can write your own custom menu items, so it is possible to write custom image component upload function to upload images and insert the images back. See the `ImageCommand` implementation for how to insert images.

Also. Sorry for the delay. I have been not using angular anymore and I maintain this during my spare time. If you are still using the package and need help feel free to post the issues if you face any. I will help.
