### ISSUE TITLE
[Request] Missing icons

### ISSUE THREAD

**Issue by Lukasz199312** [Sibiraj-S/ngx-editor#105]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [x] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description
Hello, I have problem with missing icons. https://ibb.co/kxXH2S. Do you have any suggestion how can i fix it?

### Version Information

```
ngx-editor: x.x.x
angular: 5
```

### Browser

- [ x] Chrome -  65.0.3325.181
- [ ]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

**Comment by VladimirHumeniuk** [comment]
@Lukasz199312  you are using Fontawesome 5 version, but in editor is Fontawesome 4. If you want use FA5, add next styles to your project:
```
.fa-scissors::before {
  content: "\f0c4";
}

.fa-files-o::before {
  content: "\f0c5";
}

.fa-repeat::before {
  content: "\f01e";
}

.fa-chain-broken::before {
  content: "\f127";
}

.fa-picture-o::before {
  content: "\f03e";
}

.fa-youtube-play::before {
  content: "\f03d";
}

```
