### ISSUE TITLE
[BUG]: Maxlength validation on editor is working properly

### ISSUE THREAD

**Issue by v2amruta** [sibiraj-s/ngx-editor#110]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

_A bug: I have applied maxlength validation on formcontrol property using angular 4 reactive form validation (i.e by setting formcontrol property value as  'body: ['', Validators.maxLength(800)]' ) but instead of showing validation message when characters are more than 800, it is showing validation message randomly when number of characters are 383, 607 etc.  I have used following text for testing this.
"sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"

-There is one more issue with enter key i.e when we are entering text with enter key then  it is showing validation message when there are 253 characters.  I have used following text for testing this.
"sssssssssssssssssssssssssssssssssssssssssssssss
sssssssssssssssssssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssssssssssssssss
ssssssssssssssssssssssssssssssssssssssssssssss
ssssssssssssssss"

### Version Information
https://ngx-editor.stackblitz.io/ (Currently - v3.3.0-rc.13)

### Browser

- [ ] Chrome - x.x.x

**Comment by Sibiraj-S** [comment]
I think i got it. Length validation happens based in the html but it should be based on text. I will look at it

**Comment by v2amruta** [comment]
Hi Sibiraj-S,

Please look into it asap as it is a urgent requirement of my project and thanks for your reply.

**Comment by mmahmad** [comment]
A related question: I can't find any config variable to limit character count. Is validation the recommended way?

**Comment by Spurdha** [comment]
Perhaps, we are also facing similar issue, when user is typing in ngx-editor, user cannot type after reaching 100 chars. However the same field, if I paste the text, it does not stall after 100 chars.

**Comment by arikbidny** [comment]
Hey, about reactive form .. how I can use it with formContolName and use it with my validators like:

  ngOnInit() {
    this.wikiForm = this.formBuilder.group({
      title: ['', Validators.required],
      os: ['', Validators.required],
      category: ['', Validators.required],
      content: ['', Validators.required]
    });

**Comment by sibiraj-s** [comment]
Sorry for the delay, You can't use the existing max-length validators on editor. As the model represents the HTML content. all html entities will be taken into account while length is calculated. So I have added a custom validator for validation. Will release in v4.1
