### ISSUE TITLE
[Feature]: Set Bold option of editor as default option

### ISSUE THREAD

**Issue by v2amruta** [Sibiraj-S/ngx-editor#111]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [x] Feature request
- [ ] Documentation issue or request

## Description

_A feature: I want to set bold option of editor as default option so that whenever i start entering text into it then it will display in Bold format.

### Version Information
https://ngx-editor.stackblitz.io/ (Currently - v3.3.0-rc.13)

### Browser

- [ ] Chrome - x.x.x
- [ ] Microsoft Edge - x.x.x

**Comment by Sibiraj-S** [comment]
I doesn't even sounds logical. Justify your request to sort it out.
