### ISSUE TITLE
[Enhance]: Copy the selected text to the link creation form

### ISSUE THREAD

**Issue by urbanogb** [sibiraj-s/ngx-editor#112]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [x] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

It is common to create a link on an existing text. The usual way to do it is to select the text to link and click on the button to create link.
The improvement that I propose is to check if there is a selected text and it is included in the form to create the link.

### Version Information

```
ngx-editor: 3.3.0-rc.13
angular: 5.2.10
```

### Browser

- [x] Chrome - x.x.x
- [x]  Mozilla Firefox - x.x.x
- [x] Opera - x.x.x
- [x] Microsoft Edge - x.x.x

**Comment by Sibiraj-S** [comment]
I am sorry. I don't exactly understand the enhancement. Can you elaborate?

**Comment by urbanogb** [comment]
When we click on the button insert link, the form that is presented is the
same with a selected text that without it. I propose that if there is a
selected text it is copied in the form to create the link.




2018-05-02 7:12 GMT+02:00 Sibiraj <notifications@github.com>:

**Comment by urbanogb** [comment]
If you want I can try to make the modification, although I am a novice in
angular this would be useful for me to learn.





2018-05-02 7:12 GMT+02:00 Sibiraj <notifications@github.com>:

**Comment by urbanogb** [comment]
Exactly, that is. In my experience, most users fill everything with a
copy / paste from other sources, word processors such as Word.
When pasting as plain text, it is necessary to reacer styles and
links. That is why it is very useful to do so.



2018-05-02 10:23 GMT+02:00 Sibiraj <notifications@github.com>:

**Comment by urbanogb** [comment]
In other editors there is a button that allows copying as plain text. We
have solved this using angular, but maybe it is also an improvement to take
into account. We solve it like this:

HTML TEMPLATE
<app-ngx-editor #ngxEditor (paste)="onPaste($event)" [config]="config"
formControlName="texto"></app-ngx-editor>


COMPONENT
import { DOCUMENT } from '@angular/platform-browser';
constructor(@Inject(DOCUMENT) private document: any) {
}

public onPaste(e){
e.preventDefault;
e.stopPropagation();
let texto= e.clipboardData.getData('text/plain');
this.document.execCommand('insertText',false,texto);
return false;
}




2018-05-02 10:23 GMT+02:00 Sibiraj <notifications@github.com>:

**Comment by urbanogb** [comment]
**I propose to add these changes in ngx-editor-toolbar.component.ts** 

import { Component, Input, Output, EventEmitter, OnInit, ViewChild, **Inject** } from ....
...

**import { DOCUMENT } from  '@ angular/platform-browser';**
...


  constructor(**@Inject(DOCUMENT) private document: any,**
    private _popOverConfig: PopoverConfig,
....


buildUrlForm(): void {
    **const text = (this.document.getSelection()).toString();**
    this.urlForm = this._formBuilder.group({
      urlLink: ['', [Validators.required]],
      urlText: [**text**, [Validators.required]],
      urlNewTab: [true]
    });

**Comment by urbanogb** [comment]
More simplex using Utils.saveSelection():  


buildUrlForm(): void {
    const text = (Utils.saveSelection() || '').toString();
    this.urlForm = this._formBuilder.group({
      urlLink: ['', [Validators.required]],
      urlText: [text, [Validators.required]],
      urlNewTab: [true]
    });
    return;
  }

**Comment by urbanogb** [comment]
Ok. Thanks.

**Comment by Sibiraj-S** [comment]
🍻

**Comment by sibiraj-s** [comment]
Sorry for the big delay. I am not working with angular anymore nor I don't have the time. I do stuff at the the spare time I get. Finally Fixed in v5.alpha.9.
