### ISSUE TITLE
[Feature] Get caret position.

### ISSUE THREAD

**Issue by yanshuf0** [Sibiraj-S/ngx-editor#113]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [x] Feature request
- [x] Documentation issue or request

## Description
I'd like to get the caret position in the html content. This is in order to add text based on an external event, e.g. a click event appending a string at the cursor position. I am able to get the caret position in the text box but this does not work as the html is hidden in the text box and therefore the index will be incorrect for string augmentation.

### Version Information

```
ngx-editor: 3.3.0-rc.13
angular: 5.2.0
```

### Browser

- [x] Chrome - 65.0.3325.181
- [ ]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

**Comment by Sibiraj-S** [comment]
Hi @yanshuf0 .It is decided and removed the code-editor feature which will not be worked on now. as the code-mirror breaks the build in Angular Universal.

but I can say that this will be worked later.

**Comment by yanshuf0** [comment]
So I found a solution for those looking to add content to the html on some event at the cursor position. I use a dummy character with nodes to change the html and then search for that dummy character in the html to give me the index at which to add the content to retain the styling and html.

`someEvent() { 
const target = document.createTextNode('\u0001');
          document
            .getSelection()
            .getRangeAt(0)
            .insertNode(target);
          const position = this.editor.textArea.nativeElement.innerHTML.indexOf(
            '\u0001'
          );
          const beginning = this.editor.textArea.nativeElement.innerHTML.substring(
            0,
            position || 0
          );
          const end = this.editor.textArea.nativeElement.innerHTML.substring(
            position || 0
          );
          // Removes dummy character.
          this.htmlContent = this.editor.textArea.nativeElement.innerHTML =
            beginning +
            ` [[${node.parent.data.name}.${node.data.name}]] ` +
            end.slice(1);
}`

**Comment by Sibiraj-S** [comment]
@yanshuf0 . I guess you found your solution, closing this issue now. The code editor will be worked on as all pending issues and PR's are closed.

🍻

**Comment by ChrisPanthera** [comment]
Thanks @yanshuf0 I had to edit this slightly to get position on blur as when clicking on the button to do stuff the caret position would move.

    public onTextAreaBlur() {
        // Inserts dummy character to get html position.
        const target = document.createTextNode('\u0001');
        document
            .getSelection()
            .getRangeAt(0)
            .insertNode(target);
        this.position = this.editor.textArea.nativeElement.innerHTML.indexOf(
            '\u0001'
        );
    }
