### ISSUE TITLE
[Feature]: Resize image in editor like $("img").resizable( )

### ISSUE THREAD

**Issue by lucasrueda** [sibiraj-s/ngx-editor#115]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [X] Feature request
- [ ] Documentation issue or request

## Description

It will be very helpful if we can resize the images that we include in the content just like this:

https://jqueryui.com/resizable/

The most of the times the user includes an image.. it is not in the proper size.

### Version Information

```
ngx-editor@3.3.0-rc.13
angular@5.2.10
```
Sorry if my english is bad!

**Comment by npahalZenways** [comment]
Or if we can enter image size while uploading the image, that would also do.
