### ISSUE TITLE
'Code Editor' wrong position

### ISSUE THREAD

**Issue by SerhiDi** [Sibiraj-S/ngx-editor#117]
# 'Code Editor' has incorrect position when I use </> button.

https://gyazo.com/7e754bc4bb21feaaee7af81cb8003fc4

```
"ngx-editor": "^3.3.0-rc.13",
"codemirror": "^5.37.0"
```

### Browsers

- Chrome
- Firefox

**Comment by Sibiraj-S** [comment]
Hi, The code-mirror feature was removed completely. I will make a release soon.

**Comment by luiz04nl** [comment]
Hi, Is there any old version where this feature is working properly?

**Comment by Sibiraj-S** [comment]
Never heard of this issue from users. Can't be sure which one had caused that. Also check it not a css problem.

**Comment by hesampour** [comment]
why code mirror has been removed? really its 3 hours I am searching for this issue and I was really confused. It was a great feature. when this feature comes back?

**Comment by Sibiraj-S** [comment]
@hesampour . Having CodeMirror causes problem with Angular Universal builds and also it is thought as `Why should a WYSIWYG editor need one?` hence it is removed.

**Comment by hesampour** [comment]
so you have no plan to bring it back? but its a very important feature for any WYSIWYG editor.
