### ISSUE TITLE
[Bug]: Wrong input padding inside of toolbar popups

### ISSUE THREAD

**Issue by idealser** [sibiraj-s/ngx-editor#122]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

Using angular material and ngx-editor with formControlName inside a form causes wrong input padding of toolbar popups.

![image](https://user-images.githubusercontent.com/28928275/39635558-86abfdfc-4fc6-11e8-8040-7c31df8f7613.png)

HTML
`<form [formGroup]="emailTemplateForm">
  <app-ngx-editor
            [placeholder]="'Enter message template'" 
            [spellcheck]="true"
            [imageEndPoint]="'uploads'"
            [toolbar]="ngxToolbarSet"
            formControlName="html" 
            required>
  </app-ngx-editor></form>`

Output CSS
![image](https://user-images.githubusercontent.com/28928275/39635635-bbb847ee-4fc6-11e8-820a-1697408e6195.png)

Disabling the padding fixes it.

### Version Information

```
ngx-editor: 3.3.0
angular: 5.2.10
```

### Browser

- [x] Chrome - 66.0.3359.139
- [ ]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

**Comment by simepy** [comment]
Hello, this bug affected Firefox too, with link property
I'm in Firefox 60.0.1
![image](https://user-images.githubusercontent.com/12037541/41086603-c85cefe8-6a3a-11e8-8219-af75f6a1622b.png)

**Comment by Sibiraj-S** [comment]
hi @simepy, @idealser I was working in removing ngx-bootstrap completely and implementing custom styles. Since then I recommend you to manually override the CSS properties that affects the popover.

**Comment by simepy** [comment]
Thanks for your answer  @Sibiraj-S, but I don't find in the doc how to override the CSS

**Comment by idealser** [comment]
@simepy You can do this in your global styles.css
`.ngxePopover form .form-group .form-control-sm {
  padding-left: 0 !important;
  padding-right: 0 !important;
}`

**Comment by Sibiraj-S** [comment]
Thanks @idealser . Thats what I meant @simepy

**Comment by sibiraj-s** [comment]
Sorry for the delayed response. do you still face this issue.

**Comment by sibiraj-s** [comment]
Sorry for the delay. since v5 no more, bootstrap. still few features are pending, they will be added soon.
