### ISSUE TITLE
[Feature]: Immutable placeholders

### ISSUE THREAD

**Issue by yanshuf0** [sibiraj-s/ngx-editor#124]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [X] Feature request
- [ ] Documentation issue or request

## Description

I would like to be able to have immutable placeholders that the user cannot edit, they can only delete or move them.
### Version Information

```
ngx-editor: 3.3.0-rc.13
angular: 5.2.0
```

### Browser

- [X] Chrome

<br>

**Comment by Sibiraj-S** [comment]
Hi @yanshuf0 . Never heard of immutable placeholder concept. By default placeholders is kind of immutable. Once the user starts editing it tends to hide. Users can't edit it by any chance.

Have you found any bug possibly?

**Comment by yanshuf0** [comment]
Hey maybe I explained this incorrectly. What I meant are immutable elements like those in kendo ui. https://docs.telerik.com/kendo-ui/controls/editors/editor/immutable-elements

**Comment by sibiraj-s** [comment]
Hi,Sorry for the delayed response. I don't think this possible. if you have any ideas. Send a PR 😄 . if you sort it out befor #164 gets merged. Send PR to `development` brach will release it in v4.1
