### ISSUE TITLE
How to increase the toolbar font size and validation not working in firefox browser.

### ISSUE THREAD

**Issue by GRabinJude** [sibiraj-s/ngx-editor#125]
![validation toolbar_issue](https://user-images.githubusercontent.com/28302094/39908542-2dc13c02-550c-11e8-9b6b-2b8d13c86afd.png)

I'm submitting a
    Bug report

Description
1) For validation added  [required]="true" but initially br tag added in firefox browser because br tag prevents validation.
2) How can i increase my toolbar font size issue.

Browser
    Firefox - x.x.x

**Comment by Achutharaman** [comment]
Any solutions you got?

**Comment by GRabinJude** [comment]
Not yet...can you give fix for that?


Thanks & Regards,
Rabin Jude G

















________________________________

**Comment by Achutharaman** [comment]
Use ngx-editor2 which is a fix for this

**Comment by Achutharaman** [comment]
.fa {
    font-size: 1.4rem !important;
}

Add this style to change the toolbar size
