### ISSUE TITLE
[Feature]: Grey out textarea when not editable

### ISSUE THREAD

**Issue by yanshuf0** [sibiraj-s/ngx-editor#126]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [X] Feature request
- [ ] Documentation issue or request

## Description

I would like the textarea to be grayed out when editable is set to false. I'm finding this difficult to accomplish, do you have any suggestions?

### Version Information

```
ngx-editor: 3.3.0-rc.13
angular: 5.2.0
```

### Browser

- [x] Chrome - x.x.x
- [x]  Mozilla Firefox - x.x.x
- [x] Opera - x.x.x
- [x] Microsoft Edge - x.x.x

**Comment by Sibiraj-S** [comment]
Hi, That is a valid point. I will update it. until then you can use the attributes to set css when contenteditable is set to false.

**Comment by Sibiraj-S** [comment]
Hi, I am sorry I didn't see ur comment. You can look for `contenteditable` attribute. which will be true or false based on the behaviour.

**Comment by sibiraj-s** [comment]
Should be doable via css attribute selector.
