### ISSUE TITLE
Not working in Angular 4

### ISSUE THREAD

**Issue by DT007** [Sibiraj-S/ngx-editor#129]
install ngx-editor 3.3.0 but getting error 
ERROR in Error: Metadata version mismatch for module D:/Projects/FlexCPQ/Code/UI/node_modules/ngx-editor/ngx-editor.d.ts, found version 4, expected 3, resolving symbol QuotesModule in D:/Projects/FlexCPQ/Code/UI/src/app/quotes/quotes.module.ts, resolving symbol QuotesModule in D:/Projects/FlexCPQ/Code/UI/src/app/quotes/quotes.module.ts

**Comment by Sibiraj-S** [comment]
it is not supposed to work. Check the README.
