### ISSUE TITLE
[Feature]: color picker

### ISSUE THREAD

**Issue by NiZelooer** [sibiraj-s/ngx-editor#130]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [x] Feature request
- [ ] Documentation issue or request

## Description

I would like to be able to select a color. I'm finding this difficult when I first need to google the color hex code.

### Version Information

```
ngx-editor: 3.3.0
angular: 5.2.0
```

### Browser

- [x] Chrome - x.x.x
- [x]  Mozilla Firefox - x.x.x
- [x] Opera - x.x.x
- [x] Microsoft Edge - x.x.x

**Comment by gianca970226** [comment]
Vrey importan
