### ISSUE TITLE
Insert links are not working in IE, It Says unsupported operation performed 

### ISSUE THREAD

**Issue by V2NileshSukalikar** [Sibiraj-S/ngx-editor#134]
Hi , 

Can you please provided this small support for IE where I unable to insert links inside editor in IE 10 .

**Comment by Sibiraj-S** [comment]
Hi, I initially started supporting but maintaining that is a pain. Also the browser is dead and has lot of security issues.

So IE wont be supported. This is meant to run in evergreen browsers.🍻
