### ISSUE TITLE
[BUG] cursor in Firefox is in wrong place

### ISSUE THREAD

**Issue by simepy** [sibiraj-s/ngx-editor#135]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

When I click in the ngx-editor my cursor is shift in top

![image](https://user-images.githubusercontent.com/12037541/41158343-e2cd56e4-6b28-11e8-88be-8488aaf6f7ff.png)

### Version Information

```
ngx-editor: 3.3.0
angular: 5.2.9
```

### Browser

- [ ] Chrome - x.x.x
- [x]  Mozilla Firefox - 60.0.1
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

**Comment by pareshgami** [comment]
Trying to override below css that is working for me

.ngx-editor-textarea::before {
    content: normal !important;
}
