### ISSUE TITLE
[BUG] Links are broken after font-size change

### ISSUE THREAD

**Issue by paweltin** [sibiraj-s/ngx-editor#136]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

Links are broken after font-size change. STR:
- insert link,
- select the link,
- change font size.

### Version Information

```
ngx-editor: 3.3.0
angular: 5.0.0
```

### Browser

- [x] Chrome - x.x.x
- [x]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [x] Microsoft Edge - x.x.x

**Comment by idealser** [comment]
Seems like any kind of formatting brokes after font change
