### ISSUE TITLE
[Enhancement & Feature]: Drop down list for font-family & font-size. Option to insert table.

### ISSUE THREAD

**Issue by nishantcoolmike** [sibiraj-s/ngx-editor#137]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [x] Enhancement
- [x] Feature request
- [ ] Documentation issue or request

## Description

It would be very helpful if you add drop down list for font-family and font-size.  From where we can choose necessary font family and font size. Option to insert table would be a very good feature.

### Version Information

```
ngx-editor: 3.3.0
angular: 5.2.10
```

### Browser

- [x] Chrome - x.x.x
- [x]  Mozilla Firefox - x.x.x
- [x] Opera - x.x.x
- [x] Microsoft Edge - x.x.x

**Comment by sibiraj-s** [comment]
Font size/family can be implemented using custom menu in v5. Table support will be added eventually.
