### ISSUE TITLE
link popover position.

### ISSUE THREAD

**Issue by JPCdk** [sibiraj-s/ngx-editor#138]
# I'm submitting a bug/fix

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

When you use a dialog box with ngx-editor inside and you open this dialog box while you have scrolled far down the site and you try to make a link. Then the link popover does not show.
Way to fix this is change 

```
.ngxePopover.popover {
        position: fixed;
}
```

### Version Information

```
ngx-editor: 3.3.0
angular: 5.0.2 and 6.0.5


### Browser

- [x] Chrome - 66.0.3359.181
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

**Comment by sibiraj-s** [comment]
Finally, fixed in v5-alpha.9.
