### ISSUE TITLE
[BUG] Image icon button doesn't work when use ngx-editor in Modal

### ISSUE THREAD

**Issue by haifzhan** [Sibiraj-S/ngx-editor#139]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

_A bug: Using ngx-editor in my new/edit modal page,  when click the image or video icon buttons, no response, it seems like there's conflicts when 2 modals popup_

### Version Information

```
ngx-editor: 3.3.0
angular: 6.0.2
```

### Browser

- [x] Chrome -  67.0.3396.87
- [ ]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

_NOTE: Replace `x.x.x` with your version information_

**Comment by Sibiraj-S** [comment]
Yeah possibly. Also You found where the bug is. I recommend patching it manually using css for now. The plugin now used is `ngx-bootstrap` will be removed at that time. All this issues will be addressed.

🍻
