### ISSUE TITLE
Configurable block tag (div, paragraph)

### ISSUE THREAD

**Issue by kisonay** [Sibiraj-S/ngx-editor#140]
I notice that when hitting "return" in the editor that the block level element used is a `<div>` tag. Is there any way to change this configuration to use `<p>` tags? 

Long blocks of text are typically broken up by paragraphs and the `<div>` block level items are affecting formatting when being displayed in a non-authoring environment.

**Comment by Sibiraj-S** [comment]
Hi @kisonay . Sorry for the delayed response. I just wanted to make a simple editor for angular. this editor is nothing but a wrapper for HTML5 `contenteditable` and that is how it behaves. I would like it be simple with some extra touch up.
