### ISSUE TITLE
[BUG] enable and change fontSize in toolbar with custom config

### ISSUE THREAD

**Issue by RomainMarecat** [Sibiraj-S/ngx-editor#141]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

fontSize, color, etc ... doesn't work with configuration and toolbar object. 
Because Utils function doesn't check deep keys. 
I test all possibilities but it doesn't work for this examples: 
```
{'font-size': '20px'}
{'fontSize':  {'font-size': '20px'}}
{'fontSize': '20px'}

```
 I had configuration like that: 

```
 ngEditorSettings = {
        editable: true,
        'spellcheck': true,
        'height': 'auto',
        'minHeight': '0',
        'width': 'auto',
        'minWidth': '0',
        'translate': 'yes',
        'enableToolbar': true,
        'showToolbar': true,
        'placeholder': '...',
        'imageEndPoint': '',
        'toolbar':
            {'fontSize': '50px'}

    };

    toolbarConfigurationEnabled = [
        ['bold', 'italic', 'underline', 'strikeThrough', 'superscript', 'subscript'],
        ['fontName', 'fontSize', 'color'],
        ['orderedList', 'unorderedList'],
        ['link', 'unlink']
    ];


html 
<app-ngx-editor  [config]="ngEditorSettings"
                                        [toolbar]="toolbarConfigurationEnabled"></app-ngx-editor>
```

### Version Information

```
ngx-editor: 3.3.0
angular: 6.x.x
```

### Browser

- [x] Chrome - x.x.x
- [ ]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

**Comment by kavinda1995** [comment]
Any update on font size change?
