### ISSUE TITLE
[BUG/DOC] icons not displaying, no documentation to install font awesome

### ISSUE THREAD

**Issue by phil123456** [Sibiraj-S/ngx-editor#142]
[ NEVERMIND THIS EDITOR IS BUGGY AS HELL ] 

# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [x] Documentation issue or request

## Description

Just installed the editor
but the icons are not appearing (probably because I cant install fontawesome)

I installed this : 

`npm install --save-dev @fortawesome/fontawesome-free`

my .angular-cli.json :

```
 "styles": [
        "styles.css",
         "../node_modules/node_modules/@fortawesome/fontawesome-free/css/all.css",
      ],
      "scripts": [
      	"../node_modules/node_modules/@fortawesome/fontawesome-free/js/all.js",
      ],
```

no icon are apprearing

but it works using this :

```
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
```

so why is it not working with local files ????

how do I install fontawesome correctly ?

### Version Information

```
ngx-editor: latest
angular: 5.2.0
```

### Browser

- [x] Chrome - 67.0.3396.99
- [ ]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

_NOTE: Replace `x.x.x` with your version information_

**Comment by hackherlin** [comment]
Same Problem....

**Comment by Sibiraj-S** [comment]
Use font-awesome v4.7. have you read the docs https://sibiraj-s.github.io/ngx-editor/.

**Comment by hackherlin** [comment]
I am using Font-Awesome v4.7 and I imported the Stylesheets into the .angular-cli.json file. Still doesn't show any Icons...

**Comment by Sibiraj-S** [comment]
Okay, In your issue decription you have used font-awesome 5 thats why I mentioned that.

If it is working when added via cdn and not if injected via then it is a project configuring error, not editor's. Closing this now.

If you want any help regarding your issue, feel free to continue this conversation.
