### ISSUE TITLE
Icons disappearing for ngx-editor

### ISSUE THREAD

**Issue by VinayakMan** [Sibiraj-S/ngx-editor#144]
HI, I am facing some problem with this control. When i implemented this in my project, some of the icons disappeared. Not sure whats wrong done here.. The functionality is working.. but the icons are not displayed. 

Can anyone help please?

![editor](https://user-images.githubusercontent.com/22950676/42364517-06b7c3cc-8119-11e8-9223-bf97bac4250a.png)

**Comment by kolkov** [comment]
i think maybe you use wrong fontawisome version.

**Comment by Sibiraj-S** [comment]
Hi, I can be 100% sure it won't happen if you use correct icon version. Can you reproduce the issue, maybe a sample repo or a stackblitz

**Comment by Sibiraj-S** [comment]
closing this issue as there is no possible way that can happen. I personally use it aroung 3-4 products and two of them in production. You should check with your project configuration. If there is any problem with the config or anything overrides fontaweome.

Also, try loading via cdn to check.
