### ISSUE TITLE
[Feature] Retrieve text from the editor

### ISSUE THREAD

**Issue by goodmite** [sibiraj-s/ngx-editor#145]
I am aware that HTML can be retrieved using [(ngModel)]="htmlContent", but is it possible to get just the text? Thanks.

**Comment by Sibiraj-S** [comment]
@sangupta007 will be added in next release with angular6

**Comment by rjmnt** [comment]
Hi,
Is this feature implemented?  Can we get details on this?

**Comment by sibiraj-s** [comment]
Sorry for the huge delay response.

you can extract text by.

in v4

```ts
const el = document.createElement('div')
el.innerHTML = htmlContent
const textContent = el.textContent
```

v5
see https://sibiraj.dev/ngx-editor/additional-documentation/ngmodel-binding.html

```ts
import { schema } from 'ngx-editor';

const contentNode = schema.nodeFromJSON(this.jsonDoc);
const textContent = contentNode.textContent;
```
