### ISSUE TITLE
[BUG] Angular 6: Link Text is not updating when unchecking  "Open in new tab"

### ISSUE THREAD

**Issue by arsenk01** [Sibiraj-S/ngx-editor#146]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

When trying to Create Link with unchecked "Open in new tab" I'm seeing only URL without text.

![image](https://user-images.githubusercontent.com/3646534/42455580-bc26a6c4-83a3-11e8-81fa-f84489ab80dc.png)

### Version Information

```
ngx-editor: 3.3.0
angular: 6.0.1
```

### Browser

- [x] Chrome - 67.0.3396.99
- [ ]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

**Comment by Sibiraj-S** [comment]
Hi, This editor is made for angular5, also its dependencies depend on angular 5. Angular6 is a work-in-progress. please wait for some time.
