### ISSUE TITLE
Horizontal issue

### ISSUE THREAD

**Issue by charan-r** [Sibiraj-S/ngx-editor#147]
Please help me to get horizontal scroll in this editor

**Comment by Sibiraj-S** [comment]
Hi, @charan-r . I would highly recommend not to have horizontal scrollbar. It is against the design principles and I would not be adding that any time in future. 

Seeing ur question. I would suggest you to go through some basics for UI/UX suggested by experts before u start. 
You might have know this but you can look at some articles at https://www.nngroup.com/.

Also, Next time. If there is an issue template fill it out or even if it doesn't comply with ur scenario just fill out the description don't delete it and type ur question.
