### ISSUE TITLE
ngx editor with angular reactive forms 

### ISSUE THREAD

**Issue by arikbidny** [Sibiraj-S/ngx-editor#148]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [x] Feature request
- [ ] Documentation issue or request

## Description
_A feature: Hey, I'm trying to use the editor with angular reactive forms, Is it possible? 
I want to add to [app-ngx-editor formContolName="content"] 
thanks for your help
### Version Information

ngx-editor: 3.3.0
angular: 6.0
```

### Browser

- [x] Chrome - x.x.x
- [ ]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

**Comment by jmdmao** [comment]
I'm starting to test, just with reactive forms. Apparently, it works normally.

I just didn't understand the "translate" setting.

**Comment by arikbidny** [comment]
@jmdmao You just added the formControlName to [app-ngx-editor] and it works ?

**Comment by Sibiraj-S** [comment]
@jmdmao .sorry for the delayed response. yes that is how it should be. are you facing any problems

> _A feature: Hey, I'm trying to use the editor with angular reactive forms, Is it possible?

The feature is already there, released in verison [v3.1.0](https://github.com/Sibiraj-S/ngx-editor/releases/tag/v3.1.0)

I recommend using the latest version though in angular 5

**Comment by arikbidny** [comment]
@Sibiraj-S I can use it in normal way with formControlName ?

**Comment by Sibiraj-S** [comment]
yes. it should work

**Comment by jmdmao** [comment]
@arikbidny Yes. Just like that. 

![image](https://user-images.githubusercontent.com/29717874/43537437-521bbcb4-958d-11e8-9948-99cf833f36d8.png)

![image](https://user-images.githubusercontent.com/29717874/43537458-5be1daa8-958d-11e8-95f0-fa44e5760db1.png)

**Comment by jmdmao** [comment]
@Sibiraj-S Reactive form worked for me. What I did not understand is the "translate" function, which is in the editor configuration documentation.

**Comment by Sibiraj-S** [comment]
Hi @jmdmao . I forgot to reply to ur comment. 

The `translate` is nothing but an HTML5 attribute. Check out more information here
https://www.w3schools.com/tags/att_global_translate.asp

**Comment by Sibiraj-S** [comment]
Currently it is experimental and not supported by any browsers out there. I just added it, as may be supported in future and may come handy.

**Comment by jmdmao** [comment]
Ah ok. Thanks for information! And thanks for the good job. If I may, a suggestion: put in the readme how to use the dependency of fontawsome 4.7. It will save a lot of people time. Do you have plans to upgrade to fontawesome 5, now that they have official version for angular 6?

**Comment by Sibiraj-S** [comment]
I would love to work on this editor . But I am stuck with work I cannot find time to work on this. Already I started migrating this to Angular6 and it was half way done and I am occupied. It too stuck

>If I may, a suggestion: put in the readme how to use the dependency of fontawsome 4.7

I do gave a link to the stackblitz which I thought would be enough, but I can see someone are facing troubles. Soon I will give steps to use fontawesome. where it will include three different methods to do it

The upcoming tasks I have are 
1. removing font awesome and replace with svg's or any better solution I come up at that time
2. removing all sort of dependencies to other libs
3. Angular 6

**Comment by jmdmao** [comment]
I'm using nfx-editor with angle 6, and it's working normally. On the icons, I had to install 4.7 beyond the 5, which I already use in my app. But this is not a problem. Again, thank you for your work. Good luck! (ps: I will not increase the topic anymore)

**Comment by arikbidny** [comment]
@jmdmao @Sibiraj-S thanks you both for replies its very helpful.
