### ISSUE TITLE
Unit test breaks when importing NgxEditorModule

### ISSUE THREAD

**Issue by alexanto** [Sibiraj-S/ngx-editor#149]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x ] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

Unit testing is not possible inside Angular 6 App, when importing the NgxEditorModule into the TestBed
I get an error "Can't resolve all parameters for ComponentLoaderFactory"
### Version Information

```
ngx-editor: 3.3.0
angular: 6.0.4
```

**Comment by kolkov** [comment]
This version for Angular 5 only, not for 6+.
Search GitHub for 6+ version or waiting for updated version.

**Comment by alexanto** [comment]
It works fine with Angular 6 it is only the test that's failing, why is that?

**Comment by kolkov** [comment]
if this editor works fine for you, then it's good. but this does not happen for all users ...

**Comment by alexanto** [comment]
why is the testing different?

**Comment by Sibiraj-S** [comment]
Hi @alexanto , as @kolkov said this is for angular 5, there is no guarantee for it to work with latter or older versions. If it works then it is awesome, but again there is no guarantee.
 
Angular 6 version will be release by end of this month 🍻
