### ISSUE TITLE
[Enhancement]: Use angular-fontawesome instead of bulky Fontawesome CSS

### ISSUE THREAD

**Issue by Joniras** [sibiraj-s/ngx-editor#151]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [x] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

It would be super useful if this package would use [angular-fontawesome](https://github.com/FortAwesome/angular-fontawesome) to reduce package size a lot.

This would reduce package size and setup difficulty (no additional package to install, no addition css to include).

### Version Information

```
ngx-editor: 3.3.0
angular: 6.0.9
```

### Browser

- [x] Chrome 
- [x]  Mozilla Firefox
- [x] Opera
- [x] Microsoft Edge

<br>

**Comment by Sibiraj-S** [comment]
Hi, Thanks for the suggestion. I was planning to use svg's so that icons will remain consistent everywhere.

**Comment by sibiraj-s** [comment]
Fixed in v5. Now uses material icons(SVG's) for the toolbar

**Comment by Joniras** [comment]
Thanks @sibiraj-s for working on the library again, you make a lot of people happy 😄
