### ISSUE TITLE
[Feature] Needs much more customization and better documentation

### ISSUE THREAD

**Issue by kassimir** [sibiraj-s/ngx-editor#152]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [X] Enhancement
- [X] Feature request
- [ ] Documentation issue or request

## Description

The documentation is awful. Colors just says 

> Color input can be a hex code or rgba value or a color name.
> Make Sure the HTML color names are supported by all browsers.

What does this even mean? Where do I set the colors? [color] is not a valid input for the component.

Font Size is similar:

> Font size can have any values as suggested here. If the input is a number then it will be treated as pixel, Other values are inserted as it is. Make sure you pass the correct input.

[Font] and [FontSize] are not valid inputs either, so where do I set this?

Font on the toolbar should be a drop-down with third-party fonts available, like from Google fonts.

Why is it ONLY resizable? Why can't I make it a static size and not resizable?

I would like my toolbar to have rows of buttons - not just stuck in one row.

I would like to add my own buttons with whatever font-awesome icon I want.

Hitting "tab" in the editor doesn't send any kind of tab character.

### Version Information

```
ngx-editor: 3.3.0
angular: 5.2.0
```

### Browser

- [X] Chrome - x.x.x
- [X]  Mozilla Firefox - x.x.x
- [X] Opera - x.x.x
- [X] Microsoft Edge - x.x.x

**Comment by sibiraj-s** [comment]
Hi. sorry for trouble you faced. I didn't enough time to work this lib at that time.

Currently v5 is a WIP. will try to cover the documentation as much as possible.

Meanwhile, Feel free to raise PR's incase there are any errors if you found in the documentation.
