### ISSUE TITLE
Unable to upload image in the editor

### ISSUE THREAD

**Issue by dsjambekar** [sibiraj-s/ngx-editor#156]
# I'm submitting a

- [ ] Documentation issue or request

## Description

I am trying to load an image in the editor. It allows me to select image. And then it shows 100% uploaded but it doesn't really upload the image.
![image](https://user-images.githubusercontent.com/29460586/46276570-c6f0c400-c560-11e8-9413-805d31d6e9d5.png)

I get this following error in the console-
![image](https://user-images.githubusercontent.com/29460586/46276621-f9022600-c560-11e8-9b88-45570b92be06.png)

Maybe it is not about your editor. I have to do something on my side but I don't know exactly what to do. What should I do with the json response?
Can you please explain?

### Version Information

ngx-bootstrap": "^3.0.1",
ngx-editor": "^3.3.0",
ngx-quill": "^3.6.0"

**Comment by sibiraj-s** [comment]
I guess, the problem is with the endpoint. Have you added as mentioned here? [Upload Images](https://sibiraj-s.github.io/ngx-editor/additional-documentation/image-uploader.html)

**Comment by dsjambekar** [comment]
I have added it like this -
 <app-ngx-editor id="question" imageEndPoint="/assets"  [placeholder]="'Enter text here...'" [spellcheck]="true" height="200px" ></app-ngx-editor>

**Comment by sibiraj-s** [comment]
Okay. Are you trying to upload the image to a local directory?

**Comment by dsjambekar** [comment]
yes, when running in local, it will upload on local. 
But I have hosted this app on the firebase, so later I want it to be inside a folder with the same name, on the firebase.

**Comment by dsjambekar** [comment]
Ok, so the api will receive the image as input and then the api has to save the image to whatever folder I want to save. The api will have to return the image url. Am I right?

**Comment by sibiraj-s** [comment]
Yes, totally correct. 

I should have been more clear in the docs regarding this. as this is the third issue related to the same question. Will update the docs.

**Comment by dsjambekar** [comment]
ok, thanks for the explanation.
