### ISSUE TITLE
Link button translation href

### ISSUE THREAD

**Issue by HufkensJeroen** [sibiraj-s/ngx-editor#157]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [ ] Feature request
- [x] Documentation issue or request

## Description

Hi, 

For the linking button, the text is translated for the href between double quote's. Where can i find the functionality for changing this to single quote's?

Thanks in advance,
Kind regards,
Jeroen

### Version Information

```
ngx-editor: 3.3.0
angular: 5.2.0
```

### Browser

- [x] Chrome - latest
- [ ]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

**Comment by sibiraj-s** [comment]
Thanks for reporting this. I can get the point that something unusual is happening. but I cant quite understand exactly whats happening can you elaborate?

**Comment by HufkensJeroen** [comment]
> Thanks for reporting this. I can get the point that something unusual is happening. but I cant quite understand exactly whats happening can you elaborate?

So we are using this part of the code to translate it to a json object, the fact that the href="some url" is used this has conflicts with the json object, by which it cannot be parsed. That is why i try to change this so that we atleast can use this functionality.

**Comment by HufkensJeroen** [comment]
> Thanks for reporting this. I can get the point that something unusual is happening. but I cant quite understand exactly whats happening can you elaborate?

Do you have any update on this?

Kr,
Jeroen

**Comment by sibiraj-s** [comment]
So you want to use single quote instead of double in the editor?

**Comment by HufkensJeroen** [comment]
> So you want to use single quote instead of double in the editor?

Yes single quote :-)

**Comment by HufkensJeroen** [comment]
Do you have any update on this matter?

**Comment by jerthiry** [comment]
Hi, I'm also encountering this issue on Angular 5. I think the issue is that the href is inserted with `document.execCommand('insertHTML', false, html);` which replaces the single quotes by double quotes when inserting in the editor.

**Comment by jerthiry** [comment]
Because I tried replacing double quotes with single quotes in the module code when creating the href and it is fine until the `document.execCommand('insertHTML', false, html);` line is executed.

**Comment by sibiraj-s** [comment]
Hi, Sorry for the delay. I am fixing issues in FCFS basis. Will work on this soon, I think I may need some help on this. Meanwhile, if fixable send a PR to `development` branch 😄.
