### ISSUE TITLE
HTML Content not formatted in Microsoft Edge

### ISSUE THREAD

**Issue by rowellscott** [sibiraj-s/ngx-editor#158]
[BUG]: Richtext not saving HTML formatting in Edge

# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

Richtext is only storing text content and not HTML formatting in Microsoft Edge 41. Works as expected in Chrome and Mozilla.

### Version Information

```
ngx-editor: 3.3.0
angular: 6.0.3
```

### Browser

- [ ] Chrome - x.x.x
- [ ]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ x] Microsoft Edge - x.x.x

<br>

_NOTE: Replace `x.x.x` with your version information_

**Comment by sibiraj-s** [comment]
Hi, this just wraps api's around HTML5 content-editable feature.  I don't have control over them. Sorry, I don't think I can fix this.
