### ISSUE TITLE
[BUG]: Resize does not work properly.

### ISSUE THREAD

**Issue by kapilthakkar2912** [sibiraj-s/ngx-editor#159]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

bug: When i try to decrease height of editor then it'll set height = minHeight

### Version Information

```
ngx-editor:3.3.0
angular: 5.2.1
```

### Browser

- [X] Chrome - x.x.x
- [ ]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

_NOTE: Replace `x.x.x` with your version information_

**Comment by sibiraj-s** [comment]
With min height set you won't be able to decrease the height of the editor. That is what it is intended for.

**Comment by kapilthakkar2912** [comment]
I know that, but when i start resizing editor or just click and start dragging  it will directly set with minHeight.
