### ISSUE TITLE
[BUG]: [showToolbar] does not work properly

### ISSUE THREAD

**Issue by kapilthakkar2912** [sibiraj-s/ngx-editor#160]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description
I want to hide toolbar dynamically (based on some condition ) but its want work for me.
I have written code as following
```
<app-ngx-editor [showToolbar]="condition">
</app-ngx-editor>
```

### Version Information

```
ngx-editor: 3.3.0
angular: 5.2.1
```

### Browser

- [X] Chrome - x.x.x
- [ ]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

**Comment by sibiraj-s** [comment]
Hi, it was meant to enable and disable at load, kind of like a one way. may be I can try tweaking them.
