### ISSUE TITLE
Issue on Toolbar button active

### ISSUE THREAD

**Issue by rakesh2293** [sibiraj-s/ngx-editor#162]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [x] Documentation issue or request

## Description

_A bug: Description of the issue you encountered_
_A feature: Description of the feature. Cause and its Motivation_

### Version Information

```
ngx-editor: x.x.x
angular: x.x.x
```

### Browser

- [x] Chrome - x.x.x
- [x]  Mozilla Firefox - x.x.x
- [x] Opera - x.x.x
- [x] Microsoft Edge - x.x.x

<br>

_NOTE: Replace `x.x.x` with your version information
Hi team I have an issue when i click on the toolbar button the button is not  active so please let me know the solution for this

**Comment by sibiraj-s** [comment]
hi @rakesh2293 , You have not provided any information. do elaborate.

**Comment by rakesh2293** [comment]
Please let me know the solution **ASAP**

**Comment by rakesh2293** [comment]
@sibiraj-s example: when we click on Bold Letter  **B**  that button is not active by the change of the background color the user got confused  which button I clicked  so please let me know the solution

**Comment by sibiraj-s** [comment]
You want to highlight the active element?

**Comment by rakesh2293** [comment]
I didn't get which element I have to active

**Comment by rakesh2293** [comment]
do i change anything on config??

**Comment by sibiraj-s** [comment]
That feature is not available now.

**Comment by rakesh2293** [comment]
if u don't mind shall I send the video???

**Comment by sibiraj-s** [comment]
Sure, Upload a gif or something in smaller size. 😃

**Comment by rakesh2293** [comment]
[2018-10-04_12-27-46.zip](https://github.com/sibiraj-s/ngx-editor/files/2445201/2018-10-04_12-27-46.zip)
I will send the  zip file of the video please check and let me know 
Thank you for replying

**Comment by sibiraj-s** [comment]
I will check, do u find the behaviour here too https://ngx-editor.stackblitz.io/?

**Comment by rakesh2293** [comment]
Yes

**Comment by CMUKUL** [comment]
@sibiraj-s - any update on this
