### ISSUE TITLE
Any possibility to remove some any menu item of editor

### ISSUE THREAD

**Issue by AmitAKB** [sibiraj-s/ngx-editor#163]
Any configuration is required for remove the menu item of editor
like: Insert Link, Unlink etc

Please give let me know about this?

**Comment by sibiraj-s** [comment]
Hi, it is available. Seems the document is broken, will update shortly. this is the usage.

# Configuration

The Configuration can be provided using `config` property

## Usage

```HTML
<app-ngx-editor [config]="editorConfig" [(ngModel)]="htmlContent"></app-ngx-editor>
```

### Default Configuration

The config property is a JSON object.

```JSON
{
    "editable": true,
    "spellcheck": true,
    "height": "auto",
    "minHeight": "0",
    "width": "auto",
    "minWidth": "0",
    "translate": "yes",
    "enableToolbar": true,
    "showToolbar": true,
    "placeholder": "Enter text here...",
    "imageEndPoint": "",
    "toolbar": [
        ["bold", "italic", "underline", "strikeThrough", "superscript", "subscript"],
        ["fontName", "fontSize", "color"],
        ["justifyLeft", "justifyCenter", "justifyRight", "justifyFull", "indent", "outdent"],
        ["cut", "copy", "delete", "removeFormat", "undo", "redo"],
        ["paragraph", "blockquote", "removeBlockquote", "horizontalLine", "orderedList", "unorderedList"],
        ["link", "unlink", "image", "video"]
    ]
}
```

Add values to toolbar array as required to customize it.

**Comment by AmitAKB** [comment]
Thank you...!

I need one more clarification, Shall we add drop value in "FONT Family" and "FONT Size"?

**Comment by sibiraj-s** [comment]
>Shall we add drop value in "FONT Family" and "FONT Size"? 

I don't understand. Can u clarify?

**Comment by sibiraj-s** [comment]
Feel free to continue this conversation.

**Comment by AmitAKB** [comment]
Font Family like Time New Roman, Arial, etc.
Font size like 12, 14, 16, 18 etc
