### ISSUE TITLE
stackblitz demo down

### ISSUE THREAD

**Issue by Methodician** [sibiraj-s/ngx-editor#165]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [x] Documentation issue or request

## Description

The Stackblitz demo linked in Github is not working. Console errors revolve around ComponentLoaderFactory

> Unhandled Promise rejection: Can't resolve all parameters for ComponentLoaderFactory: (?, ?, ?, ?, ?).

### Browser

- [x] Chrome -  69.0.3497.100

**Comment by sibiraj-s** [comment]
Yeah. I did that. Something went wrong while upgrading to angular 6. I wasn't able to exactly pin point the problem will fix that sooner.

**Comment by sibiraj-s** [comment]
Seems problem with `ngx-bootstrap`.

**Comment by riginoommen** [comment]
@sibiraj-s can you share the stable version of ngx-editor for the angular 5 - from the upstream this module looks broken.

@sibiraj-s i think its beter to move your unstable changes to a different repository and work it. now its messing up

**Comment by sibiraj-s** [comment]
>different repository ,

do u mean a stackblitz?

**Comment by Methodician** [comment]
TBH this lead me to just stick with CKEditor even though I'd rather use a more open-source, less capitalistic tool with better Angular integration. I had to do a custom build of CKEditor and develop my own plugin (soon to be released under @Methodician ) just to use Firebase Cloud Storage.

My front-end specialist and I both liked the simplicity and documentation of this as well as the reduction in long-term dependencies for an Angular project, but when you click the live demo link and it's broken that's a red flag. Could I perhaps be of assistance?

**Comment by Methodician** [comment]
FWIW here's where we're using CKEditor and approximately the functionality we'd hope to get from ngx-editor: https://github.com/Methodician/CoSourcery/tree/article-edit-ckeditor

And here's where I'm working on a custom build of CKEditor just so I can use it with Firebase Storage, which is a silly requirement that probably comes out of their attempt to commercialize an open source tool by offering paid image management services: https://github.com/Methodician/ckeditor5-build-inline

**Comment by sibiraj-s** [comment]
@Methodician I have no clue why stackblitz is broken. In case of demo. Just temporarily Clone this repo and run `npm start`. You can get a working editor.

**Comment by sibiraj-s** [comment]
Closing as fixed.
