### ISSUE TITLE
Code editor button is not working 

### ISSUE THREAD

**Issue by MALHARIHALGEKAR** [sibiraj-s/ngx-editor#168]
## Code editor button is not working
I have added ["code"] as array in toobar but I am not getting code editor

# I'm submitting a 

- [x] Bug report

## Description

In Angular 5 it was working fine the code editor button is showing and I am able to edit html content

In Angular 6 it is not working please check image

![joxi_screenshot_1539586057915](https://user-images.githubusercontent.com/19145662/46934166-5ecbd300-d074-11e8-9f54-e41112e22100.png)

### Toolbar config 

`editorConfig = {
    editable: true,
    spellcheck: true,
    minHeight: '100px',
    translate: 'no',
    width: 'auto',
    toolbar: [
      ["bold", "italic", "underline", "strikeThrough", "superscript", "subscript"],
      ["fontName", "fontSize", "color"],
      ["justifyLeft", "justifyCenter", "justifyRight", "justifyFull", "indent", "outdent"],
      ["cut", "copy", "delete", "removeFormat", "undo", "redo"],
      ["paragraph", "blockquote", "removeBlockquote", "horizontalLine", "orderedList", "unorderedList"],
      ["link", "unlink"],
      ["code"]
    ]
  };`

### HTML
`<app-ngx-editor (focus)="helpBox($event)" class="xeditors" *ngIf="this.templateData.templateType == 'EMAIL'"
                placeholder="{{'Enter text Template' | translate}}" [config]="editorConfig" [spellcheck]="true"
                [(ngModel)]="templateBody" name="templateBody" (ngModelChange)="templateBodyChange($event)"></app-ngx-editor>`

### Version Information

```
ngx-editor: "^3.3.0-rc.10"
angular: "^6.0.3"
```

### Browser

In all browsers

**Comment by sibiraj-s** [comment]
Hi, The code-editing feature is dropped. Also That version doesn't support Angular 6. Update to v4+

**Comment by MALHARIHALGEKAR** [comment]
@sibiraj-s I needed code-editing for my application

**Comment by MALHARIHALGEKAR** [comment]
code-editor is working in ngx-editor: "^3.3.0-rc.10" version with angular 5 and this is the important feature we already have in production please help me to get work

![joxi_screenshot_1539590446443](https://user-images.githubusercontent.com/19145662/46937427-e9193480-d07e-11e8-9063-ba6e51121c64.png)
