### ISSUE TITLE
Drop-down menu to select the protocol from the link popup

### ISSUE THREAD

**Issue by NicholaAlkhouri** [sibiraj-s/ngx-editor#170]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [x] Feature request
- [ ] Documentation issue or request

## Description

_A feature: Add a drop-down with a list of protocols in the Link popup. the drop-down contains "http, https, ftp, none .etc" and defaulted to "http" or "https".

Motivation: normal users usually use "www.google.com" not "http://www.google.com", this will lead to a relative link to the host domain "http://example.com/www.google.com", so the drop-down menu with a default protocol will insure that the user will always enter a valid URL.
In case of a need of a relative URL to the host domain, user can select "none" from the protocol list.

### Version Information

```
ngx-editor: 4.0.0,
angular: 6.1.2
```

### Browser

- [x] Chrome - x.x.x
- [x]  Mozilla Firefox - x.x.x
- [x] Opera - x.x.x
- [x] Microsoft Edge - x.x.x

**Comment by sibiraj-s** [comment]
Sorry for the huge delay. I no longer use angular and I maintain this on my free time. Fixed in v5. URL's are validated now. Thanks.
