### ISSUE TITLE
Multiple editor on same page and showToolbar 

### ISSUE THREAD

**Issue by bringentor** [sibiraj-s/ngx-editor#176]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

I'm using many editors on the same page and the problem is that by setting up 'showToolbar' property it doesnt get affected separatly, both editor toolbars are shown or hidden
```
<app-ngx-editor [placeholder]="'Enter text here...'" [(ngModel)]="something" [spellcheck]="true" [showToolbar]="true"></app-ngx-editor>
<app-ngx-editor [placeholder]="'Enter text here...'" [(ngModel)]="somethingDifferent" [spellcheck]="true" [showToolbar]="false"></app-ngx-editor>
```

Anyone knows what is wrong or how to fix it ? 
### Version Information

```
ngx-editor: 4.1.0
angular: 6.1.0
```

### Browser

- [x] Chrome - 70.0.3538.77
- [ ]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

**Comment by ph1lolog1st** [comment]
I have similar issue with [editable] input. All editors on my page are editable or not editable, so I cannot set [editable]="true" only to one editor.

**Comment by sibiraj-s** [comment]
Sorry for the delayed response. Try v5 (currently in alpha). this should be working now. Reopen the issue if the problem still exists

**Comment by yusufkhan2546** [comment]
i am still facing this issue ..
here in my package.json

"ngx-editor": "^5.3.0",
![issue2](https://user-images.githubusercontent.com/48908924/103466613-89e19080-4d6c-11eb-86a7-9d008ef9f7af.png)

**Comment by sibiraj-s** [comment]
@yusufkhan2546 I will check that out. Meanwhile a stackblitz example would fasten things up.

**Comment by sibiraj-s** [comment]
@yusufkhan2546 V5 has no option to disable menu via component level. Try v6 you can include the menu component only when required.

```html
<ngx-editor-menu [editor]="editor" [toolbar]="toolbar"></ngx-editor-menu>
```

**Comment by priyank989** [comment]
if i am calling editor in for loop. Its not working. only the last editor in for loop working

 <div *ngFor="let tests of test; let i = index"
             [ngClass]="'main-div-' + division.id">
<div class="NgxEditor__Wrapper" [class.hidden]="!division.isEdit">
                    <ngx-editor-menu [editor]="editor"> </ngx-editor-menu>
                    <ngx-editor
                      [editor]="editor"
                      [ngModel]="html"
                      [disabled]="false"
                      [placeholder]="'test'"
                    ></ngx-editor>
                  </div>
</div>

**Comment by sibiraj-s** [comment]
@priyank989 Are you using the same editor instance inside the loop?

**Comment by JamesAtTheGBSgroup** [comment]
I'm having the same problem.  It would be nice if you could initialize the editor inside the template.  Instead, my workaround is to init an array of editors... for (i < x) editors.push(new Editor()).  I don't like it.

**Comment by sibiraj-s** [comment]
> I'm having the same problem.  It would be nice if you could initialize the editor inside the template.  Instead, my workaround is to init an array of editors... for (i < x) editors.push(new Editor()).  I don't like it.

You can write a new component that does this binding and you can use that component inside the for loop. 

And the idea behind editor initialised first is to have programmatic control over the editor. The editor uses prosemirror under the hood, which creates the DOM during initialization :(. hence this issue. I open to alternate implementation suggestions as well.
