### ISSUE TITLE
how to remove the youtube , image , link buttons??????????????????

### ISSUE THREAD

**Issue by hemanth-sp** [sibiraj-s/ngx-editor#178]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [ ] Feature request
- [x] Documentation issue or request

## Description

_A bug: Description of the issue you encountered_
_A feature: Description of the feature. Cause and its Motivation_

### Version Information

```
ngx-editor: x.x.x
angular: x.x.x
```

### Browser

- [ ] Chrome - x.x.x
- [ ]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

_NOTE: Replace `x.x.x` with your version information_

**Comment by sibiraj-s** [comment]
You Should be able to configure tool bar by providing necessary options. 

- https://sibiraj-s.github.io/ngx-editor/additional-documentation/configuration.html
- https://sibiraj-s.github.io/ngx-editor/additional-documentation/toolbar.html.

**Comment by hemanth-sp** [comment]
thank you boss
