### ISSUE TITLE
[Feature]: paste & paste as text buttons

### ISSUE THREAD

**Issue by RobertHajbok** [sibiraj-s/ngx-editor#184]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [x] Feature request
- [ ] Documentation issue or request

## Description

I was wondering if there is any plan to add the paste button. I saw another issue - https://github.com/sibiraj-s/ngx-editor/issues/127#issuecomment-390474060, you mentioned you were considering removing the cut & copy buttons. Also, TinyMCE for example gives you the possibility to paste as text. Meaning that if I paste some HTML content from an email for example, that will only paste the text for me, without any HTML tags at all. You can see that here: https://www.tiny.cloud/docs/demo/full-featured/, under Edit on the menu. Note that the functionality is different from "Clear formatting" button ngx-editor (or even TinyMCE) provides. I think adding these 2 buttons would be very useful. I can contribute with a PR if you don't have time for this. Thanks!

### Version Information

```
ngx-editor: 4.1.0
angular: 6.1.10
```

### Browser

- [x] Chrome
- [x] Mozilla Firefox
- [x] Opera
- [x] Microsoft Edge

**Comment by sibiraj-s** [comment]
Hi, Sorry for the huge delay. I stopped working on angular. I started maintaining the project in my free time and I will continue to. 

Closing this one as it is too old, and can be implemented by writing a prosemirror plugin using [transformPastedHTML](
https://prosemirror.net/docs/ref/#view.EditorProps.transformPastedHTML) or related methods.

In case if you are still using this editor. let me know if any help required.
