### ISSUE TITLE
[BUG]:Copy a data Microsoft excel to text-editor styles are missing

### ISSUE THREAD

**Issue by Mandark-iprogrammer** [sibiraj-s/ngx-editor#186]
# I'm submitting a

Bug report

## Description

I have copied data excel to text-editor ,there is formatted data which is bold,table heading etc., So problem is that when we copy that data excel to text-editor that pasted data has removed it's CSS(also Table border). This issue is coming on all browsers which are copy data MS Office 365 excel to Text-editor.
Kindly please help for me that issue.

### Version Information

```
ngx-editor: ^4.0.0
angular: ^6.0.3
```

### Browser

Chrome -  71.0.3578.98

<br>

NOTE: We have all the data keep in Microsoft Excel like(Office 365).

**Comment by Mandark-iprogrammer** [comment]
### Ngx-editor Excel copy paste to editor

@sibiraj-s  please give me suggest of that issue

**Comment by sibiraj-s** [comment]
Sorry for the huge delay. Can you try v5. 

Note: Tables are not supported yet.
