### ISSUE TITLE
[Feature]: Editor format buttons to interact with iOS keyboard format buttons

### ISSUE THREAD

**Issue by tomrainedotcom** [sibiraj-s/ngx-editor#188]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [x] Feature request
- [ ] Documentation issue or request

## Description
A feature: When using the editor on an iOS device the keyboard gives options for bold, italic and underline. These are not selected when used in the editor. For example, if I was to press the underline button on the editor, this is not selected on the keyboard. Also if I was to select the underline option on the keyboard the editor underline button is not selected.

However when you select either option from the editor or the keyboard the format is reflected on the input.

### Version Information

```
ngx-editor: ^4.1.0
angular: ^6.0.3
```

### Browser

- [x] Chrome - x.x.x
- [ ]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

**Comment by sibiraj-s** [comment]
This should be working since v5. reopen this if the issue still persists.
