### ISSUE TITLE
Max length validator documentation with example

### ISSUE THREAD

**Issue by knr89** [sibiraj-s/ngx-editor#190]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [ ] Feature request
- [x] Documentation issue or request

## Description
I am new to Angular 6 and unable to figure out how to use custom max length validator. There is no proper documentation nor sample example to figure it out. Please provide working example with documentation, so that beginner/entry level can easily understand..
_A bug: Description of the issue you encountered_
_A feature: Description of the feature. Cause and its Motivation_

### Version Information

```
ngx-editor: 4.1
angular: 6
```

### Browser

- [ ] Chrome - x.x.x
- [ ]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

_NOTE: Replace `x.x.x` with your version information_

**Comment by sibiraj-s** [comment]
sorry for the delay. I no longer use angular and I maintain this on my free time. this No longer applicable in v5 so closing it. If you are still using this editor. It is recommended to use v5. Thanks.

**Comment by Maks-Yaremenko** [comment]
Hello.
Seems like Validators.required() from ngx-editor not working, as well as custom validation for maxLength... 
I'm using "ngx-editor": "^5.0.0".
I tested it on the demo app from your repo. Could you please suggest smth how can I solve this? Thank you.
