### ISSUE TITLE
How to use image uploader from local system ?

### ISSUE THREAD

**Issue by QuentinIcky** [sibiraj-s/ngx-editor#193]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [ ] Feature request
- [x] Documentation issue or request

## Description

I'm using your editor to create a blog with Angular and MongoDb. But I don't understand how to use the image uploader. When I try to upload, I can see a request and get a 200 from server, but the image doesn't appear in the text box. 
And when I post article and retrieve it from my API, image is not present. 
How to use it ? I didn't find any details in the documentation or in other issues.

My image API endpoint is simply : `http://localhost:3000/picture` 

### Version Information

```
ngx-editor: 4.1.0
angular: 6.0.0
```

<br>

**Comment by QuentinIcky** [comment]
Any idea ?

**Comment by sibiraj-s** [comment]
With v5. you can write your own custom menu items, so it is possible to write custom image component/upload function to upload images and insert the images back. See the `ImageCommand` implementation for how to insert images.

Also. Sorry for the delay. I have been not using angular anymore and I maintain this during my spare time. If you are still using the package and need help feel free to post the issues if you face any. I will help.
