### ISSUE TITLE
Editor's dependencies need to be moved to peerDependencies

### ISSUE THREAD

**Issue by ssuperczynski** [Sibiraj-S/ngx-editor#20]
Hey, I found new issue.
I've created Stackblitz demo to show current behaviour https://stackblitz.com/edit/app-ngx-editor?file=app%2Fapp.component.html
It actually can't render editor because parent component has it's own node_modules and ngx-editor installed own node_modules. As a result - is unable to render component correctly.

Dependencies need to be moved to devDependencies, or peerDependencies https://github.com/stackblitz/core/issues/161#issuecomment-334909068

**Comment by Sibiraj-S** [comment]
Oops. I guess I missed that out. I crafted this app using angular cli and exported directly. I Will fix this as first thing in the morning.

**Comment by Sibiraj-S** [comment]
@ssuperczynski . It is fixed now. :)

**Comment by ssuperczynski** [comment]
Thanks @Sibiraj-S I can confirm app starts now, but... stopped to show content in the WYSIWYG ;)
DEMO https://app-ngx-editor.stackblitz.io/
CODE https://stackblitz.com/edit/app-ngx-editor?file=app%2Fapp.component.ts

**Comment by Sibiraj-S** [comment]
But I verified. It worked. let me check again

**Comment by Sibiraj-S** [comment]
You should import  `FormsModule` for `ngModel` to work.

Here is the working stackblitz: https://stackblitz.com/edit/app-ngx-editor-huycdx?file=app/app.module.ts

**Comment by Sibiraj-S** [comment]
`html` is now changed to `ngModel` in release 3.1.0

**Comment by ssuperczynski** [comment]
<3 You are awesome

**Comment by Sibiraj-S** [comment]
:smile:  Thanks
