### ISSUE TITLE
Unable to set and reset [(ngModel)] value in ngx-editor-5.0.0-Alpha-1 

### ISSUE THREAD

**Issue by mrgunav** [sibiraj-s/ngx-editor#203]
1). Initially i try set some text from component in ngmodel. But it is not updatedin editor.

2). After entering value in editor i try to reset the text by setting ngmodel empty. But it is also not updated.

**Comment by sibiraj-s** [comment]
can u post the input for ngModel and no longer accets html as input. It should be a prosemirror document object.

v5 has lots of breaking changes and docs is incomplete. i am currently working on docs.

**Comment by DevelopersCourt** [comment]
If you want to reset it pass `{type: 'doc', content: []}` as value.

**Comment by sibiraj-s** [comment]
Oh. I misunderstood. I thought it was not working at all. Thanks @DevelopersCourt .

Please reopen the issue, if it still exists
