### ISSUE TITLE
CSS Style not getting applied in text area

### ISSUE THREAD

**Issue by arunkiraan** [sibiraj-s/ngx-editor#206]
I'm trying to apply CSS styling to the text area. 

.ngx-editor .ngx-editor.text-area{
font-size: 12px !important;
}

when I try to copy and paste a text. The above style is overridden.

**Comment by sibiraj-s** [comment]
Yes. there are multiple issues with versions < v4 rite now. v5 is in alpha which uses prosemirror underneath which should be more stable.

**Comment by sibiraj-s** [comment]
Closing this as answered.
