### ISSUE TITLE
Paste as plain text

### ISSUE THREAD

**Issue by rjmnt** [sibiraj-s/ngx-editor#208]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [ ] Feature request
- [x] Documentation issue or request

## Description

How is pasting to plain text working in the demo version https://ngx-editor.stackblitz.io/?  Would like details, as I want to be able to paste as plain text into the editor after copying from Excel or PowerPoint, etc.  Currently, Excel cells pasted into the editor are displayed as below:

![screenshot](https://user-images.githubusercontent.com/64523281/80576052-23101880-8a22-11ea-852d-b1b8b9d84fda.png)

### Version Information

```
ngx-editor: 4.1.0
angular: 8.3.2
```

### Browser

- [x] Chrome - x.x.x
- [x] Mozilla Firefox - x.x.x
- [x] Opera - x.x.x
- [x] Microsoft Edge - x.x.x

**Comment by sibiraj-s** [comment]
the demo, you see is v5 alpha.1.
v4 is not maintained.

**Comment by rjmnt** [comment]
Thank you so much for your reply.

**Comment by sibiraj-s** [comment]
Closing as answered.
