### ISSUE TITLE
[FEATURE] Inserting/extracting html into a popup version of ngx-editor

### ISSUE THREAD

**Issue by goldel777** [sibiraj-s/ngx-editor#221]
Hi, 

This is a feature request.

We really love this editor.  We've been using an earlier version as a popup editor to handle lengthy descriptions.  We save editor changes only displaying the first n characters as inner html.    

It seems that the latest version of the editor does not store the model innerHTML as html.   It would be great if there were an easy way to convert between html (which we use for our readonly display) and the json doc format that is use in ngx-editor.

**EXAMPLE

Inner Html:**

`<p><strong>BOLD</strong></p><p><em>Italic</em></p>
`
**JSON format:**

```
{type: "doc", content: Array(2)}
content: Array(2)
0:
content: Array(1)
0: {type: "text", marks: Array(1), text: "BOLD"}
length: 1
__proto__: Array(0)
type: "paragraph"
__proto__: Object
1:
content: Array(1)
0: {type: "text", marks: Array(1), text: "Itali"}
length: 1
__proto__: Array(0)
type: "paragraph"
__proto__: Object
length: 2
__proto__: Array(0)
type: "doc"
__proto__:

```

Any help appreciated

### Version Information

```
ngx-editor: ^5.0.0-alpha.4
angular: ^9.1.5
```

### Browser

- [ X] Chrome - x.x.x
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

**Comment by sibiraj-s** [comment]
Are you looking for this

```
import { DOMSerializer } from "prosemirror-model";
import { schema } from "ngx-editor";

const contentNode = schema.nodeFromJSON(jsonDoc);

// https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment
const html: DocumentFragment = DOMSerializer.fromSchema(schema).serializeFragment(contentNode.content);
console.log(html);
```

**Comment by goldel777** [comment]
Thanks for getting back to me
Yes and also how to go from html to the Jan doc that Nyc-editor used


Sent from Yahoo Mail for iPhone


On Friday, May 29, 2020, 2:09 PM, Sibiraj <notifications@github.com> wrote:




Are you looking for this
import { DOMSerializer } from "prosemirror-model";
import { schema } from "ngx-editor";

const contentNode = schema.nodeFromJSON(jsonDoc);

// https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment
const html: DocumentFragment = DOMSerializer.fromSchema(schema).serializeFragment(contentNode.content);
console.log(html);

**Comment by sibiraj-s** [comment]
@goldel777 check the  comment https://github.com/sibiraj-s/ngx-editor/issues/221#issuecomment-636111024. I updated it now.

**Comment by sibiraj-s** [comment]
```
const div = document.createElement('div')
div.innerHTML = '<div>Hello world!</div>'
const json = DOMParser.fromSchema(schema).parse(div).toJSON() // use this as ngModel input
```

**Comment by goldel777** [comment]
Thank You!


Sent from Yahoo Mail for iPhone


On Friday, May 29, 2020, 2:26 PM, Sibiraj <notifications@github.com> wrote:




@goldel777 check the comment #221 (comment). I updated it now.
