### ISSUE TITLE
ngx-editor has no exported member schema

### ISSUE THREAD

**Issue by aaqibqadeer** [sibiraj-s/ngx-editor#237]
I want to convert the text to html to allow users to see the source code.

I read the documentation and tried to implement few things from it, but I am getting these errors

I can import the package by simply importing NgxEditorModule. But I can't call the forRoot() method to update the configuration.
```
import { NgxEditorModule } from 'ngx-editor';

@NgModule({
  imports: [
    NgxEditorModule.forRoot(),
  ],
```
It is showing this error:
`Property 'forRoot' does not exist on type 'typeof NgxEditorModule`

And when I am importing this:
```
import { DOMSerializer } from 'prosemirror-model';
import { schema } from 'ngx-editor';
```
The compiler is showing:
`Cannot find module 'prosemirror-model`

```
Module '"../../../../../../../../../../../../../OneDrive/Desktop/Project/glo/node_modules/ngx-editor/ngx-editor"' has no exported member 'schema'.ts(2305)
```

**Comment by sibiraj-s** [comment]
what version are you using? the documentation is for v5. 
I will add it in readme.

**Comment by sibiraj-s** [comment]
> The compiler is showing:
Cannot find module 'prosemirror-model
```
Module '"../../../../../../../../../../../../../OneDrive/Desktop/Project/glo/node_modules/ngx-editor/ngx-editor"' has no exported member 'schema'.ts(2305)
```
You must install external modules yourself.

**Comment by aaqibqadeer** [comment]
I am using ngx-editor 4.1.0 and angular 7. I can't install the v5? Is it for angular 8+

**Comment by sibiraj-s** [comment]
Nope. It should work, but I can't guarantee.

**Comment by ravimallya** [comment]
Whoever comes here for the error `k/node_modules/@angular/core/core"' has noore/core"' has no exported member 'ɵɵInjectorDeclaration'.

15     static ɵinj: i0.ɵɵInjectorDeclaration<NgxEditorModule>;` using the latest version of ngx-editor with Angular 10, please downgrade editor version to 8.x.x
