### ISSUE TITLE
[BUG] Cursor not going to newline on pressing Enter.

### ISSUE THREAD

**Issue by dwaipayan-dev** [sibiraj-s/ngx-editor#239]
# I'm submitting a

- 

- [x] Regression (a behavior that used to work and stopped working in a new release)

- [ ] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

_A bug: Description of the issue you encountered_
_A feature: Description of the feature. Cause and its Motivation_

### Version Information

```
ngx-editor: x.x.x
angular: x.x.x
```

### Browser

- [x] Chrome - x.x.x
- [x] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

_NOTE: Replace `x.x.x` with your version information_

**Comment by dwaipayan-dev** [comment]
I am trying to develop an angular application where I want to insert a rich text editor that stores data in string format rather than HTML format. Your editor used to store the data written in it as a string, so I decided to use it, but I found that the cursor is not shifting to new line on pressing enter. Also in firefox the cursor is not shifting to new line when it reaches the border of the text feild. Please look issue and inform me as to how to resolve it.
![Issue](https://user-images.githubusercontent.com/51186857/85851863-24b14f00-b7cd-11ea-8cf0-77cabca23b6a.PNG)

Note: In the previous versions this was not the issue.

**Comment by sibiraj-s** [comment]
You need add plugins for that to work.

For example see https://stackblitz.com/edit/ngx-editor?file=src%2Fapp%2Fplugins%2Findex.ts

```
 const plugins = [
    keymap(baseKeymap), // required for this issue
  ];
```

**Comment by sibiraj-s** [comment]
Please reopen the issue if it doesn't solve the problem.
