### ISSUE TITLE
Option to remove the font-awesome dependency

### ISSUE THREAD

**Issue by RicardoVaranda** [Sibiraj-S/ngx-editor#24]
Would be nice to be able to disable this if for example you wanted to use material instead.

**Comment by Sibiraj-S** [comment]
Are you saying about a custom toolbar?

**Comment by Sibiraj-S** [comment]
@RicardoVaranda. Can You provide more information for clarification?

**Comment by Sibiraj-S** [comment]
###### INACTIVE
closing the issue

**Comment by KK220794** [comment]
can we change dependency from font-awesome to anything else like angular material icons?
