### ISSUE TITLE
How to set height

### ISSUE THREAD

**Issue by nandekonst** [sibiraj-s/ngx-editor#242]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ X] Documentation issue or request

## Description

Thanks for creating this awesome package. In previous editions from this package it was always possible to set the height through a config property. This doesn't seem to exist anymore. Using the css class also doesnt allow me to set the height. In the documentation I can't find anything about it. How can I set a custom height?

Thanks for your response.

### Version Information

```
ngx-editor: 5.0.0-alpha.9
angular: 9.1.9
```

### Browser

- [ ] Chrome - x.x.x
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

_NOTE: Replace `x.x.x` with your version information_

**Comment by sibiraj-s** [comment]
the height prop is removed, will add options to set attributes soon, until then you can use css.

try.

```css
.NgxEditor__Content {
 height: 200px;
 overflow: auto;
}
```

**Comment by nandekonst** [comment]
Thanks for the info and the solution.

**Comment by nandekonst** [comment]
That works!! thnx
