### ISSUE TITLE
editor size not incresing size when pressing Enter button .

### ISSUE THREAD

**Issue by frndxyz** [sibiraj-s/ngx-editor#253]
I'm submitting a bug:

## Description

editor not incresing size when pressing enter.

using reactive-forms.

### Version Information

```
"ngx-editor": "^5.0.0-alpha.9"
"@angular/core": "^10.0.4"
```

### Browser

chrome

Error from developer tools:

column: 25
line: 107067
message: "Unknown node type: undefined"
sourceURL: "http://localhost:4201/vendor.js"
stack: "nodeType@http://localhost:4201/vendor.js:107067:25↵fromJSON@http://localhost:4201/vendor.js:105698:25↵nodeFromJSON@[native code…"

**Comment by sibiraj-s** [comment]
I can see but it working here https://ngx-editor.stackblitz.io/. can you create a stackblitz so that I can see what went wrong and fix it

**Comment by sibiraj-s** [comment]
I can see it working here https://ngx-editor.stackblitz.io/. 

I am not sure where it went wrong. Can you share a stackblitz reproducing the error?

**Comment by sibiraj-s** [comment]
Closing it due to inactivity. Feel free to reopen if the issue still exists.
