### ISSUE TITLE
[Feature] Collaborative Editing

### ISSUE THREAD

**Issue by vicatcu** [sibiraj-s/ngx-editor#254]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [x] Enhancement
- [x] Feature request
- [ ] Documentation issue or request

## Description

To be totally transparent, I haven't even tried using this library yet. I came across it by looking for an angular binding for prose-mirror and stumbled upon this project via npm. While not directly stated in the README, there was a prose-mirror tag in the npm listing, and the package.json of this project certainly suggests prose-mirror packages are included.

It doesn't look like prosemirror-collab is included currently though. I realize there's a server-side aspect to making the collab module work and it's more complicated (e.g. represent multiple user cursor selections and what not), but I wanted to see if this is something on the roadmap for this project and if so when it might be expected to debut.

Omitting version information because this is a fairly general feature request.

Thanks for your consideration!

**Comment by sibiraj-s** [comment]
Haven't looked in the collaborative editing yet. but with prosemirror one should be able to write a plugin to achieve it by following the example here https://github.com/ProseMirror/prosemirror-collab. 

It is possible to pass prosemirror plugins via `editor.forRoot({plugins})`. I am not sure about adding the support to the editor itself. It might increase the maintenance burden. When I am free I will try doing a working example of that and post a reference or example for that in the docs or even better link a working demo of it.

**Comment by sibiraj-s** [comment]
I have added an example here https://sibiraj-s.github.io/ngx-editor/#/collab using `yjs`.
