### ISSUE TITLE
WYSIWYG Markdown support

### ISSUE THREAD

**Issue by LifeIsStrange** [sibiraj-s/ngx-editor#256]
Next generation editors allow WYSIWYG Markdown support such as slate and Tiptap.

Explanation of this awesome feature:
Markdown as of today is underused as the changes it will do are not visible while editing but this doesn't has to be the case:

As you can see in this demo[0], just outline a word with * and it instantaneously become italic. 
What's more: if you start a new line with # it instantaneously get the right size. 
You want an h2? Just put 2 ##
In fact you have this feature but just for this special case :/
It's just plain instantaneous and therefore user friendly and productive Markdown. 

[0] https://tiptap.dev

The WYSIWYG that you already provide is *complementary* and is quicker to access sometimes and sometimes isn't, especially for doing partial selections, double clicking repeatedly and so much mouse movements "break" the train of thoughts of the writing process, I think this point is important.
What do you think? To me this is the future and is implemented through prosemirror
https://prosemirror.net (but doesn't necessarily has to be)

Also there is a market opportunity here, since as of today there are no WYSIWYG Markdown editors available for Angular (slate being for react and Tiptap for Vue) and since you have a great support of Angular, you could adress that market.

**Comment by sibiraj-s** [comment]
I agree markdown is a great addition. I myself use markdown editor mostly.

There is still lot work to do. The current road map items for this package is to support everything that prosemirror supports which also includes markdown. I mostly work on this package on my free time, which I hardly find.

Any help is appreciated and All PR's are welcome.

**Comment by LifeIsStrange** [comment]
Good to know!
But why not use the prosemirror API where relevant? At least as a stop gap for the missing features?

Sorry I won't do PR I have not the time nor the skill :p

**Comment by sibiraj-s** [comment]
Use v5. This is doable via Input rules, see https://sibiraj.dev/ngx-editor/#/input-rules for implementation.
