### ISSUE TITLE
[Bug/Feature?] NgModel two-way binding: Ngx-editor refreshes only on 'shallow' document change

### ISSUE THREAD

**Issue by nandekonst** [sibiraj-s/ngx-editor#257]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [x] Feature request
- [ ] Documentation issue or request

## Description

Only when you swap out the entire document for a new one, Ngx editor re-renders its shown content. When I change a value inside the JSON Doc (for example the text of one of the text elements) through a typescript function, the Ngx Editor bound to the doc doesn't update its shown content.  

### Version Information

```
ngx-editor: ^5.0.0-alpha.9
angular: 9.1.x
```

### Browser

- [X] Chrome - l86.0.4240.75 (only one tested)
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

I can understand tracking the entire doc for changes may be resource intensive and this is expected behavior. In that case a 'refresh' functionality that re-renders the changed document when called would be a feature request to get Ngx Editor to show the change.

**Comment by sibiraj-s** [comment]
Yeah. I just noticed. but there seems to be a bug there. I am working on it. 

If the bug is fixed we won't need a forceRefresh option right?

**Comment by sibiraj-s** [comment]
I did a mistake while testing. it seems to be working fine. Can you provide a small example(a stackblitz) to reproduce this.

**Comment by nandekonst** [comment]
Sorry for the delay. In your Stackblitz you replace the first doc with a completely new doc, on button press. This works for us as well. However, we change just one node in the doc. In that case the changes are not reflected in the ngx-editor element. GIve us a moment to build a stackblitz to illustrate our example, we'll post it later today.

**Comment by jpwichern** [comment]
Dear Sibiraj,

I'm a collegue of @nandekonst and modified your Stackblitz to fit the problem we have. You can find it here: https://stackblitz.com/edit/ngx-editor-cka7ga?file=src/app/app.component.ts . I have noticed on one occasion the modified text was output to the browser window, however I couldn't reproduce it. Most of the time when the button is pressed, the text won't change.

**Comment by sibiraj-s** [comment]
I am looking into it, i will post an update by today.

**Comment by sibiraj-s** [comment]
I have tested it, it seems the angular is the one not picking it up deep object mutation. IMO avoid mutations.

Some working hacks could be

```ts
  onButtonClick() {
    this.editorContent.content[1].content[0].text = "This is editable text, changed programmatically. You can focus it and start typing."

    this.editorContent =  {...this.editorContent}
  }
```
> By default, Angular does not do deep object comparison to detect changes, it only takes into account properties used by the template

Source: https://blog.angular-university.io/how-does-angular-2-change-detection-really-work/
See here for some information on how angular treat deep objects. 

A related [stackoverflow question](https://stackoverflow.com/questions/34796901/angular2-change-detection-ngonchanges-not-firing-for-nested-object)maybe for some alternate solutions(I have not tested them)

**Comment by nandekonst** [comment]
Thank you for your suggestions about (mis)using the spread/rest operator to force a change detect. It works! This is a sufficient hack for everyone who has full control over the jsondoc. Your link to stackoverflow about Angular2 change detection is also very interesting (especially the ```ngDoCheck()``` part). I will close the issue now.
