### ISSUE TITLE
[BUG] Insert video popover form validation is not enough permissive (width and height)

### ISSUE THREAD

**Issue by florianpasteur** [sibiraj-s/ngx-editor#263]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

When adding a video on `Insert Video Popover` the validation form does not allow more than one number for `width` or `height` values. 

**Valid form:** 
![valid-form](https://user-images.githubusercontent.com/59569242/98547836-09853e80-2299-11eb-953a-725347c34e7e.png)

**Invalid form:** 
![invalid-form](https://user-images.githubusercontent.com/59569242/98547839-0ab66b80-2299-11eb-9137-6b0201be843e.png)

### Version Information

```
ngx-editor: 4.1.0
angular: 8.2.14
```

### Browser

- [x] Chrome - 86.0.4240.183 (only one tested)
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

**Comment by sibiraj-s** [comment]
Fixed in v4.1.1
