### ISSUE TITLE
Support for angular 10

### ISSUE THREAD

**Issue by argelj289** [sibiraj-s/ngx-editor#266]
Is ngx-editor still supported for angular 10?

because when I tried to upgrade my project to angular 10  that has ngx-editor in it,

the editor is not created in page after compiling it

ngx-editor version: ^5.0.0-alpha.7
angular version: 10.1.3

**Comment by sibiraj-s** [comment]
If you are updating from v4, there are changes. See the documentation for usage details. Else, can you provide more details?

**Comment by sibiraj-s** [comment]
Try the current version. alpha.9 supports angular 10. Incase you are updating from v4, there are some breaking changes. see the docs once.

Thanks.
