### ISSUE TITLE
[BUG]: Run in production mode: Heading dropdown disappears.

### ISSUE THREAD

**Issue by jpwichern** [sibiraj-s/ngx-editor#269]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

When compiling our project which uses the ngx-editor v5, in production mode (ng build --prod, ng serve --prod), the heading drop down disappears. It also leaves no traces in the DOM. Attached is a picture how the menu bar looks like when using our app with ng serve in production mode and developer tools open. The separator is selected, where we would expect the heading drop down on the right. The heading drop down is present when not compiling in production mode... also as an extra test I removed our work in progress clipboard extension (the X C A on the left side) to make sure that wasn't the cause. Unfortunately that didn't help out...

### Version Information

```
ngx-editor: ^5.0.0-alpha.9
angular: ~9.1.9
```

### Browser

- [x] Chrome - x.x.x
- [x] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [x] Microsoft Edge - x.x.x

<br>

![heading error](https://user-images.githubusercontent.com/7807708/99807989-85f10a80-2b40-11eb-96d1-ef74901e23da.png)

**Comment by sibiraj-s** [comment]
Hmm, strange 🤔 . I will look into this. It would be great if you could put together a stackblitz to reproduce this.

Also, PR's are welcome 😄

**Comment by jpwichern** [comment]
I tried to use the stackblitz you sent us from a previous issue, updated ngx-editor to alpha 9 and added --prod flags but there the header dropdown just appeared. So either something else goes wrong in my code which I can't find that has a particular impact on the menu or the bug isn't reproducable with stackblitz. However I did find a console warning in the log now which I overlooked earlier:

Unkown dropdown group: heading  ...   main.c0c037afcad69cffceb2.js:1:832245

So, the heading key isn't seen as a dropdown group when compiling for production... Of course no such warning is present when compiling or serving without --prod ...

**Comment by sibiraj-s** [comment]
Thanks. Incase if you are not using the defaults, post your config here. I I will check. Meanwhile I will try to setup a locally and verify. I will update you back by tomorrow.

**Comment by sibiraj-s** [comment]
I was able to reproduce it in angular 10, where as it works fine in angualr. 11 strange 🤔 . I make a patch soon.

**Comment by sibiraj-s** [comment]
Try with the recent alpha.

**Comment by jpwichern** [comment]
I will, monday when I'll continue work on the editor with my colleague.
I'll keep you posted on the results.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by sibiraj-s** [comment]
@jpwichern did it work?
