### ISSUE TITLE
[BUG]: ngx-editor-toolbar.component.d.ts:3:31 - error TS2307: Cannot find module 'ngx-bootstrap'

### ISSUE THREAD

**Issue by mzbrand** [sibiraj-s/ngx-editor#290]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

### Version Information

After upgrading from Angular 8 I'm getting a compilation error for ngx-editor:

`Error: node_modules/ngx-editor/app/ngx-editor/ngx-editor-toolbar/ngx-editor-toolbar.component.d.ts:3:31 - error TS2307: Cannot find module 'ngx-bootstrap' or its corresponding type declarations.`

I am able to resolve this by changing that line in the ngx-editor-toolbar.component.d.ts file to:

`import { PopoverConfig } from 'ngx-bootstrap/popover';`

Note the addition of "/popover".

This is a known issue when upgrading from Angular 8.

ngx-editor: 5.0.0-alpha.17 
angular: 11.0.4
ngx-bootstrap: 6.2.0

### Browser

n/a

<br>

**Comment by sibiraj-s** [comment]
V5 doesn't have `ngx-bootstrap` dependency. and the file `ngx-editor-toolbar.component.d.ts` doesn't exist. Try deleting the node_modules and reinstall. that should fix it.

**Comment by sibiraj-s** [comment]
Note: Since you are upgrading from v5. see here https://sibiraj.dev/ngx-editor/#/doc-html-doc for converting HTML to json and vice versa.

**Comment by sibiraj-s** [comment]
I hope it is fixed. reopen if the problems still exists.
