### ISSUE TITLE
editorConfig path

### ISSUE THREAD

**Issue by bbeniston** [Sibiraj-S/ngx-editor#30]
`[config]="editorConfig"`

What is the path of editorConfig file? I placed editorConfig.json file in the outside src folder and its not taking.

It says: 

> ERROR TypeError: Cannot read property 'hasOwnProperty' of undefined

and the error is pointing to

`<app-ngx-editor [config]="editorConfig" [(ngModel)]="content"></app-ngx-editor>`

**Comment by Sibiraj-S** [comment]
editorConfig is not a file.

It is a JSON(not JSON file). Add that in yout `.ts` file. Check this for example

https://github.com/Sibiraj-S/ngx-editor/blob/30e1ad2716161fc0753cca3de1ca5606aea42961/src/app/app.component.ts#L18-L25

**Comment by bbeniston** [comment]
Yes, it works well now.
