### ISSUE TITLE
[BUG]: editable: false, should disable controls

### ISSUE THREAD

**Issue by Maks-Yaremenko** [sibiraj-s/ngx-editor#302]
## Description

When we are setting editable false, it would be great to disable controls as well. Currently in case if editable set as false, the user cant type anything but he is able to apply all actions on the selected text, which can be confusing.

### Version Information
```
ngx-editor: 5.1.1
angular: 9+
```

**Comment by sibiraj-s** [comment]
Since the severity is low. I will fix this tomorrow. I am quite occupied at this moment. Have fixed other high sev issues though

**Comment by sibiraj-s** [comment]
Fixed in v5.2.1
