### ISSUE TITLE
[BUG]: Backgroud and color of text gets remove 

### ISSUE THREAD

**Issue by azaif7** [sibiraj-s/ngx-editor#303]
# I'm submitting a

- [x] Bug report

## Description

_A bug: When I give some background color or color to the text and then I resize the text, the color and bg gets remove.

### Version Information

```
ngx-editor: 2.2.3
angular: 2+
```

### Browser

- [ ] Chrome - 87.0.4280.88

https://user-images.githubusercontent.com/76776233/103349288-495ceb00-4abe-11eb-8254-ccc13c5b02f8.mp4

**Comment by sibiraj-s** [comment]
@azaif7 v2 is more than 2years old. It is no longer supported, also I don't remember most of the things there and also the API's.  There are many issues with contenteditable api's. 

Recommended to use latest version but unfortunately the latest version requires angualr 9 or above.
