### ISSUE TITLE
[Feature] Custom floating menu

### ISSUE THREAD

**Issue by MateMahinKhan** [sibiraj-s/ngx-editor#305]
# I'm submitting a
Feature request

## Description

Love the project! Thanks for your hard work. 

I'm trying to implement a floating menu that would appear above the line when some text is selected

I saw the issue for menu on the bottom of the editor. I was wondering if It's possible to do it in prosemirror bypassing ngx-editor toolbar altogether?

![image](https://user-images.githubusercontent.com/4667473/103575023-cccd7080-4ef2-11eb-8a31-a1fe04d01e31.png)

Thanks for any pointers you can offer.

**Comment by sibiraj-s** [comment]
> I was wondering if It's possible to do it in prosemirror bypassing ngx-editor toolbar altogether?

You should be able to provide plugins to prosemirror directly via.

```ts
new Editor({
  plugins: [
    // prosemirror plugins
  ],
});
```

or register a plugin on the fly like.

```ts
const editor = new Editor();
editor.registerPlugin(plugin);
```

Refer bubble component as an example https://github.com/sibiraj-s/ngx-editor/blob/master/src/lib/components/bubble/bubble.component.ts
This is what that shows up when you click on a link in the editor. this is based on the example here https://prosemirror.net/examples/tooltip/.

Inject the component into the element with `NgxEditor` class. You should be able to write a floating menu.

Plus I am working on exposing commands so that would allow to build custom menu easily.

like

```ts
const editor = new Editor();

editor
  .commands()
  .bold()
  .insertText()
  .italic()
  .exec();
```
but it will take few weeks. as I am occupied with personal work here.


I hope this helps.

**Comment by fredmabire** [comment]
Hi,

I create a component for doing this.

ballon.component.html
`<ngx-editor-menu class="tooltip" [editor]="editor" >
</ngx-editor-menu>`

ballon.component.css (see [Prosemirror tooltip](https://glitch.com/edit/#!/raspy-burnt-archduchess?path=index.html%3A1%3A0))
```
:host {
    position: absolute;
      .tooltip {
        position: absolute;
        // pointer-events: none;
        z-index: 20;
        background: white;
        border: 1px solid silver;
        border-radius: 2px;
        padding: 2px 10px;
        margin-bottom: 7px;
        -webkit-transform: translateX(-50%);
        transform: translateX(-50%);
      }

      .tooltip:before {
        content: "";
        height: 0;
        width: 0;
        position: absolute;
        left: 50%;
        margin-left: -5px;
        bottom: -6px;
        border: 5px solid transparent;
        border-bottom-width: 0;
        border-top-color: silver;
      }

      .tooltip:after {
        content: "";
        height: 0;
        width: 0;
        position: absolute;
        left: 50%;
        margin-left: -5px;
        bottom: -4.5px;
        border: 5px solid transparent;
        border-bottom-width: 0;
        border-top-color: white;
      }

}
```  

ballon.component.ts 

```
import {
  Component,
  ElementRef,
  Input,
  OnDestroy,
  OnInit,
  Renderer2
} from '@angular/core';
import {
  Editor
} from 'ngx-editor';
import {
  EditorView
} from 'prosemirror-view';
import {
  Subscription
} from 'rxjs';

@Component({
  selector: 'app-ballon',
  templateUrl: './ballon.component.html',
  styleUrls: ['./ballon.component.scss']
})
export class BallonComponent implements OnInit, OnDestroy {
  @Input() editor: Editor;

  private view: EditorView;
  private updateSubscription: Subscription;

  constructor(
    private el: ElementRef,
    private renderer: Renderer2
  ) {}

  private setDomPosition(): void {

    this.showBubble();
    let state = this.view.state
    let {
      from,
      to
    } = state.selection;
    let start = this.view.coordsAtPos(from),
      end = this.view.coordsAtPos(to)
 
    let box = (this.view.dom.parentNode as any).getBoundingClientRect();

    let left = (start.left + end.left) / 4;
    
    let bottom = (box.bottom - start.top + 50);
    
    this.renderer.setStyle(this.el.nativeElement, 'left', `${left}px`);
    this.renderer.setStyle(this.el.nativeElement, 'bottom', `${bottom}px`);
  }

  private showBubble(): void {
    this.renderer.setStyle(this.el.nativeElement, 'display', 'flex');
  }

  private hideBubble(): void {
    this.renderer.setStyle(this.el.nativeElement, 'display', 'none');
  }

  private update(): void {
    const {
      state
    } = this.view;

    if (state.selection.empty) {
      this.hideBubble();
      return
    }

    // update dom position
    this.setDomPosition();
  }

  ngOnInit(): void {
    this.view = this.editor.view;

    this.updateSubscription = this.editor.onUpdate.subscribe(() => {
      this.update();
    });
  }

  ngOnDestroy(): void {
    this.updateSubscription.unsubscribe();
  }

}
```  
Add `position: relative;` to `.editor` class in app.component.scss

Then replace 

`<ngx-editor-menu [editor]="editor" [toolbar]="toolbar" [customMenuRef]="customMenu">
        </ngx-editor-menu>`

by 

`<app-ballon [editor]="editor"></app-ballon>` in app.component.html

### **Result :** 

![image](https://user-images.githubusercontent.com/34098151/104950874-c7c3f300-59c1-11eb-8339-621ea8904c6f.png)


I hope this can help you.

**Comment by sibiraj-s** [comment]
Thanks @fredmabire . It is a good one.

But I didn't add it to the lib yet since it was difficult to calculate the position of nodes with images in it. I need to try if I can do one will node_views. couldn't find time.

Also this might overlap with the builtin link bubble that showsup when selection has a link or clicked on a link

**Comment by GitHubish** [comment]
No idea if this resource can be useful to you, the Tiptap editor (usable with VueJS) also uses Prosemirror and they have a system where the toolbar appears in a bubble.

https://github.com/ueberdosis/tiptap/blob/3b8ba27cc8871a7b8949fc423a8335edf7f9c3c8/packages/tiptap/src/Components/EditorMenuBubble.js

In any case I am interested in this project. Today I'm using Quill and I'll be taking the arguments in favor of NgxEditor but that's another subject.

**Comment by sibiraj-s** [comment]
Thanks @GitHubish . I just know Tiptap, not aware of its complete features. I will look into it.

Also, I will try to add floating menu components and try to fix conflicts with link bubble that already exists.

**Comment by fredmabire** [comment]
Hi @sibiraj-s !
Yes I saw that there was a display problem with the link bubble.
This was just a brief example for @MateMahinKhan .
I am also interested in NgxEditor and I did not know TipTap editor either (thanks @GitHubish)  but some elements are interesting such as suggestions and tables.

Maybe I can help if you want.

**Comment by GitHubish** [comment]
@fredmabire cool if I could make you discover a new library.
For the @Mention feature there may be something inspired by [Tiptap](https://github.com/ueberdosis/tiptap/blob/046babfd3a94222128f08cef653859ab66eaf3cd/packages/tiptap-extensions/src/nodes/Mention.js) too and [quill-mention](https://github.com/afry/quill-mention) that I use and that I had to fork for an internal project and rewritten in Typescript. Maybe I could help NgxEditor to have a module like this one. 

Anyway great job @sibiraj-s

**Comment by sibiraj-s** [comment]
Thanks @GitHubish.

NgxEditor supports plugins. See https://github.com/joelewis/prosemirror-mentions. 

You can do this and no changes is required from the editor side for now. there are many community provided plugins. you can use them. If nothing is available we can add it.

```ts
new Editor({
  pluigins: [
    new MentionsPlugin()
  ]
})
```

Create a discussion if you need any help regarding this. Let's continue it there if required. lets keep this discussion for floating menu alone.

**Comment by sibiraj-s** [comment]
I have added a bubble with minimal options as floating menu built in in v8. 

It is also possible to make the current menu floating around selection with few lines of code. See https://stackblitz.com/edit/ngx-editor-floating-menu. The position calculation is not perfect yet. I will update that later.

**Comment by sibiraj-s** [comment]
I have fixed the positioning issue in demo. I will see if I could provide the same as an easy to use built in component with better positioning.

**Comment by GitHubish** [comment]
@sibiraj-s thank you it's already super cool!

The problem I often see, which would be great to fix is when the editor is in a modal and the parent has an `overflow: hidden | scroll`, floating toolbars are a problem if they are not created at the body level.
example : [demo](https://stackblitz.com/edit/ngx-editor-floating-menu-npqhzk)

Do you think it can be done?

**Comment by sibiraj-s** [comment]
> Do you think it can be done?

Yes.

I have forked your example and made few changes to append to body. Checkout [stackblitz](https://stackblitz.com/edit/ngx-editor-floating-menu-append-to-body?file=src%2Fapp%2Fapp.component.ts)

**Comment by sibiraj-s** [comment]
I just made rendering floating menu simpler in v8.0.0-beta.4

A Simple floating menu (default)

```html
<ngx-editor [editor]="editor"> </ngx-editor>
<ngx-editor-floating-menu [editor]="editor"></ngx-editor-floating-menu> // place this whererver required.
```

To make the existing menu float

```html
<ngx-editor [editor]="editor"> </ngx-editor>
<ngx-editor-floating-menu [editor]="editor">
  <ngx-editor-menu [editor]="editor"></ngx-editor-menu>
</ngx-editor-floating-menu>
```

You can place the floating menu anywhere in the HTML. just make sure its wrapper has `postion: relative` on it.

Demo: [Default Floating Menu](https://stackblitz.com/edit/ngx-editor-floating-menu?file=src%2Fapp%2Fapp.component.scss)
Demo: [Floating Menu with menu component](https://stackblitz.com/edit/ngx-editor-floating-menu-custom?file=src%2Fapp%2Fapp.component.scss)

**Comment by wkulinski** [comment]
I don't know if its bug or feature but this info might be helpful for someone:
floating menu is not working when Ivy is disabled in tsconfig:

`
"angularCompilerOptions": {
    "enableIvy": false,
  }
`

You can try it here (Ivy is disabled in this example. To fix menu just enable it):
https://stackblitz.com/edit/ngx-editor-floating-menu-o7e8d1?file=tsconfig.json

**Comment by sibiraj-s** [comment]
thanks @wkulinski. Angular 9 comes with ivy enabled by default. It didn't occur to me to test in non ivy mode at the time of development. I will check this.
