### ISSUE TITLE
[BUG] Custom menu example not working properly on stackblitz

### ISSUE THREAD

**Issue by MateMahinKhan** [sibiraj-s/ngx-editor#306]
[ ] Bug report

[stackblitz example that I forked](https://stackblitz.com/edit/ngx-editor-kpd7tc?file=src%2Fapp%2Fcomponents%2Fcustom-menu%2Fcustom-menu.component.html)

I added the class `newClass` in custom-menu.component.html and it does not appear in HTML inspection.

In the documentation it mentions adding the `customMenuRef` like this 
```
<ngx-editor-menu
  [editor]="editor"
  [toolbar]="toolbar"
  [customMenuRef]="customMenu"
>
</ngx-editor-menu>
```

but the app.component.ts file doesn't tell how to create this ref. Maybe I'm missing something.

 I'd very happy to create a PR to documentation once I find the fix. 
 
 I've already tried adding these to app.component.ts
 `customMenu = new CustomMenuComponent();`
 `customMenu = CustomMenuComponent;`

Best

**Comment by MateMahinKhan** [comment]
Now I understand how it works. The top menu option for CodeMirror was not visible when stackblitz opened. (menu was cut off)

but I'm still curious how does the reference work here?

**Comment by sibiraj-s** [comment]
Glad you figured it out. the documentation is little dull as of now, I couldn't find time to work on it. If you think anything can be improved anywhere in the documentation to avoid these scenarios, feel free to suggest improvements. All contributions are welcome.

Thanks.
