### ISSUE TITLE
[Feature]: Option to change font size

### ISSUE THREAD

**Issue by bbeniston** [Sibiraj-S/ngx-editor#31]
Can you please provide feature to change the text size. (This is not a issue, but feature request)

**Comment by kavinda1995** [comment]
Any update on this? I actually need this feature but couldn't get to work like @kb11Collective

**Comment by sibiraj-s** [comment]
Sorry. I missed this one. The Option `fontSize` was added and then removed in the recent versions for maintainability issues. One can use custom components to implement the custom menu. but I still don't think there is a straight forward way from the editor to implement this in few lines. Let me see what can be done. 

I don't think I will add the feature directly to the editor, but can provide ways to implement this will little configuration.

To implement this, we'll need

- A schema to accept/parse font size attribute
- A command to set font size attribute to the node.
