### ISSUE TITLE
[BUG]: After image or link injection, editor lose focus

### ISSUE THREAD

**Issue by Maks-Yaremenko** [sibiraj-s/ngx-editor#310]
# I'm submitting a

- Bug report

## Description

_A bug: Description of the issue you encountered_
In case of usage add a link or image functionality, after the overlay is closed editor loses focus.

steps to reproduce #1
1. click on the add link or image button
2. select enter link or any input field
3. put your image link or a simple link
4. click add
5. link was added BUT editor loses its focus
6. you can't continue typing until set focus onto the editor

steps to reproduce #2
1. set focus onto the editor
2. click on the add link or image button
3. set focus to input inside the overlay
2. click anywhere in the window outside the editor
5. editor loses its focus - error thrown by angular

In case of usage component wrapper with ControlValueAccessor, MatFormFieldControl, and FocusMonitor. Due to losing focus angular throwing error

    ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for 'mat-focused': 'true'. Current value: 'false'.

focusMonitor:

     private focusHandler(): void {
        this.focusMonitor.monitor(this.elementRef, true).subscribe((origin) => {
          if (this.focused && !origin) {
            this.onTouched();
          }

          this.focused = !!origin;
          this.stateChanges.next();
        });
      }

### Version Information

```
ngx-editor: 5.2.0
angular: 9.1.9
```

### Browser

- Chrome - Version 87.0.4280.88 (Official Build) (x86_64)

**Comment by sibiraj-s** [comment]
Will fix it.

**Comment by sibiraj-s** [comment]
Fixed in v6.0.3.
