### ISSUE TITLE
[BUG]: error TS1127: Invalid character in MenuService

### ISSUE THREAD

**Issue by vibhorebhatnagar** [sibiraj-s/ngx-editor#319]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

Received the following error :

**ERROR in ../node_modules/ngx-editor/lib/modules/menu/menu.service.d.ts:6:5 - error TS1127: Invalid character.   #private;**

I was following the instructions in the ReadMe and simply installed the package and imported NgxEditorModule in the app Module.
```
import { NgxEditorModule } from 'ngx-editor';
```
and got the above error. 

### Version Information

```
ngx-editor: 7.0.0 (received the same error on v6+)
angular: 9.0.0
```

### Browser

- [x] Chrome - 88.0.x
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

_NOTE: Replace `x.x.x` with your version information_

**Comment by sibiraj-s** [comment]
What is the typescript version you have? You might want to check in your compiler options for private fields.

See https://www.typescriptlang.org/docs/handbook/classes.html#ecmascript-private-fields

**Comment by sibiraj-s** [comment]
I have also removed them in v8.0.0-beta.7. Feel free to continue the discussion if you have more question or need any help.

**Comment by vibhorebhatnagar** [comment]
@sibiraj-s  v8.0.0-beta.7 worked for me! Thanks!

**Comment by sibiraj-s** [comment]
Glad that helped.

**Comment by sibiraj-s** [comment]
@sarrasarra1. Noticed an issue in OpenBase. Just letting you know that this issue is fixed.
