### ISSUE TITLE
[BUG]: In a form array value is not the editor content

### ISSUE THREAD

**Issue by GuillaumeGorret** [sibiraj-s/ngx-editor#320]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

When using a FormArray, the value of a control is { type: string, content: Array }.

### Version Information

```
ngx-editor: 8.0.0-beta.7
angular: 9.1.13
```

### Browser

- All browsers

**Comment by sibiraj-s** [comment]
> { type: string, content: Array }

is not a valid value. 

Change it to `{ type: 'doc', content: Array }`

See here for example. https://github.com/sibiraj-s/ngx-editor/blob/master/demo/src/app/doc.ts

Feel free to reopen the issue, if that is not the case. Thanks.

**Comment by sibiraj-s** [comment]
I think I misunderstood the context here.

> { type: string, content: Array }

This I think you mentioned it to the FormArray Initializer. I mistook it to the json doc value. I will check and update regarding this.

**Comment by sibiraj-s** [comment]
I think I misunderstood the context here. Let me check and update back.

**Comment by GuillaumeGorret** [comment]
I think my explanation is not clear enough. 

I use a custom component that basically use ngx-editor. Sometimes on focusOut the value I receive is the HTML and sometimes it's an object. I don't know why I have two different behaviour with the same component.

**Comment by sibiraj-s** [comment]
If input is HTML the output is HTML, If input is json output is json. You can also set outputFormat manually by  setting `outputFormat`  to `doc|html` on the editor component.

**Comment by sibiraj-s** [comment]
> I use a custom component that basically use ngx-editor. Sometimes on focusOut the value I receive is the HTML and sometimes it's an object. I don't know why I have two different behaviour with the same component.

Is this the issue you face?

**Comment by GuillaumeGorret** [comment]
Input is always HTML. 

outputFormat fix the issue. Thanks for the tip :)

**Comment by sibiraj-s** [comment]
Glad that fixes the issue. Also make sure initializser is not null as well. It might cause the editor to emit object as well.

**Comment by sibiraj-s** [comment]
Glad that fixes the issue. Also make sure initial value is not null as well, It will cause the editor to emit json. You can set it to empty string.
