### ISSUE TITLE
[Feature]: When we empty the editor, remove <p></p> from content

### ISSUE THREAD

**Issue by GuillaumeGorret** [sibiraj-s/ngx-editor#321]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [x] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

When we empty the editor the content is &lt;p>&lt;/p> so angular validator required cannot be used

### Version Information

```
ngx-editor: 8.0.0-beta.7
angular: 9.1.13
```

### Browser

- All browsers

<br>

**Comment by sibiraj-s** [comment]
You can use the custom validator comes with the editor.

```ts
import {Validators} from 'ngx-editor'

new FormControl('', Validators.required())
```

See here for some other validators https://sibiraj-s.github.io/ngx-editor/#/reactive-forms?id=validators
