### ISSUE TITLE
[BUG]: Returns empty p tags string when there is no text just line breaks! required validation not working

### ISSUE THREAD

**Issue by shockingResident** [sibiraj-s/ngx-editor#322]
## Description

_A bug: When i press enter and add line breaks it returns empty p tags string like `<p><p></p></p>`. on it angular required validation does not work. please fix it, if there is no text then angular required validation should work. thanks

### Version Information

```
ngx-editor: 7.0.4
angular: 10.0.4
```

### Browser

- [x] Chrome -  87.0.4280.66 

<br>

**Comment by sibiraj-s** [comment]
Use custom validators. Example

```ts
import {Validators} from 'ngx-editor'

new FormControl('', Validators.required())
```

Some other validators https://sibiraj-s.github.io/ngx-editor/#/reactive-forms?id=validators

**Comment by sibiraj-s** [comment]
Closing this issue. Feel free to continue the discussion If you have any doubts.

**Comment by shockingResident** [comment]
I have used this validator but still facing issue, can you please tell me the version of ngx-editor please?

**Comment by sibiraj-s** [comment]
Oh. I get it. I misunderstood earlier. The validator just check if the editor is empty or not, this is same as Angular's required validator. 
It doesn't trim the value before validation. 

You might wan't to implement your own custom validator for custom .

See here for examples https://github.com/sibiraj-s/ngx-editor/blob/master/src/lib/validators.ts.

Let me know if you need any help with that.

**Comment by shockingResident** [comment]
Okay, I will submit a PR later after handling this issue. Others will also benifit from it.

**Comment by sibiraj-s** [comment]
Thanks. I am just not sure whether it has to added to required validator, since I added the behaviour to match angular's required validator.

I don't use angular that heavily. how is this handled in other places?

**Comment by sibiraj-s** [comment]
I have put some thought over it. I think this is not just about text content. the editor will have custom views, images etc. Considering those into account, I suppose deciding when the editor is TRULY empty is purely subjective .

Exposing bare default would be the best way to go and for custom needs they can implement their own solution which is also supported by angular. 

> Okay, I will submit a PR later after handling this issue. Others will also benefit from it.

and for this. I am open to adding a section in the docs adding custom code examples.
