### ISSUE TITLE
[Feature]: insertHtml command

### ISSUE THREAD

**Issue by GuillaumeGorret** [sibiraj-s/ngx-editor#323]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [x] Feature request
- [x] Documentation issue or request

## Description

Is it possible to add a command that allow us to insert some content as HTML ? 

If not, is it possible to have some documentation to write this new command ?

### Version Information

```
ngx-editor: 8.0.0-beta.7
angular: 9.1.13
```

### Browser

- All browsers

<br>

**Comment by sibiraj-s** [comment]
Like HTML snippet as code block or could you elaborate a little?

**Comment by GuillaumeGorret** [comment]
For example I want to add via a button the character Ψ. So I used insertText("&Psi;") but insertText insert directly the text.

**Comment by sibiraj-s** [comment]
The editor uses ProseMirror underneath for content editing. ProseMirror documents are not HTML. So It is not possible to insert random HTML in it. 

You can try inserting unicode in your case may be

```ts
this.editor.commands.insertText("\u03A8").exec() // will insert `Ψ`
```

Else you might need to create custom schema and implement nodeviews for specific needs.

**Comment by sibiraj-s** [comment]
You can do this to insertHTML.

```ts
import { DOMParser } from "prosemirror-model";

const { state, dispatch } = this.editor.view;
const { selection, schema, tr } = state;

const element = document.createElement("div");
element.innerHTML = html;
const slice = DOMParser.fromSchema(schema).parseSlice(element);

const transaction = tr.insert(selection.anchor, slice.content);
dispatch(transaction);
```

but for the above requirement It will always insert the parsed value. `Ψ` will be a text inside the doc.

**Comment by sibiraj-s** [comment]
Added in v8.
