### ISSUE TITLE
[Feature] On Focus, On Blur, enable and disable features are missing in v8

### ISSUE THREAD

**Issue by lyamone** [sibiraj-s/ngx-editor#324]
# I'm submitting a 

- [x] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

In the latest version (v8.0.0) the Editor object is not exposing the focus, blur, disable and enable methods anymore.
I know this is an intended beheavor but I would like to know if it was replaced by something else or it was just deprecated.
We are using the focus to show the toolbar menu and the blur to hide it.
Also, the disable and the enable methods to programmatically make the editor editable for the user.

Thanks!

### Version Information

```
ngx-editor: 8.0.0
angular: 9.1.12
```

### Browser

- [x] Chrome - x.x.x
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

**Comment by sibiraj-s** [comment]
I never intended to add them. v8 is mostly a cleanup and hence those got removed along with few other things.

You will need to use the component parameters. 

See here.

https://github.com/sibiraj-s/ngx-editor/blob/40aa5484d94a391754d4dc7252c8145a871f32c8/src/lib/editor.component.ts#L38-L41

> We are using the focus to show the toolbar menu and the blur to hide it.
Also, the disable and the enable methods to programmatically make the editor editable for the user.

You may be able to still do that with the above props.

**Comment by sibiraj-s** [comment]
May be I can add this to the migration guide 🤔

**Comment by lyamone** [comment]
Hi @sibiraj-s ,

Thanks for the quick response.
I tried the props that you mentioned and they are working. Nice!

I think It would be useful for others to just clarify in the migration guide that we can still use the focus and blur methods using props.

BTW, I really like the library. Great work! Thanks for the help!

**Comment by sibiraj-s** [comment]
Thanks @lyamone. Glad I was helpful in a way. Also, Consider a star for this lib 😄 

And, I have updated the migration guide as well.

**Comment by lyamone** [comment]
Of course I did it!
