### ISSUE TITLE
[BUG] Disappearing carriage/cursor

### ISSUE THREAD

**Issue by wkulinski** [sibiraj-s/ngx-editor#325]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

Hello,

I've noticed that when editor is empty (no content) and placeholder is visible the carriage/cursor becomes invisible after one time "blink". This might be very misleading for user who would think that editor lost focus (while not). This bug is probably related with placeholder itself because cursor becomes visible when you delete placeholder from DOM with dev console.

You can check it on this stackblitz - just try to focus editor with mouse click:
https://stackblitz.com/edit/ngx-editor-disappearing-carriage?file=src/app/app.component.ts

### Version Information

```
ngx-editor: 8.0.0
angular: 10.2.x
```

### Browser

- [ ] Chrome - x.x.x
- [x] Mozilla Firefox - 85.0.1
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

BTW, thanks for your time and great work @sibiraj-s 

Best,
Wojciech Kuliński

**Comment by wkulinski** [comment]
Also pleas have a look on this threat form prosemirror discuss. You might find it helpful:
https://discuss.prosemirror.net/t/placeholders-caret-vanishes-in-firefox/3541

**Comment by sibiraj-s** [comment]
I will fix it this weekend. Got little occupied here.

Thanks for the link. I have already though about css placeholders, since the existing solution is working fine, didn't bother much. I will look into that now.

**Comment by sibiraj-s** [comment]
Fixed in v8.0.1
