### ISSUE TITLE
[Feature]:  Remove HTML and formatting from text on paste

### ISSUE THREAD

**Issue by steffensbola** [sibiraj-s/ngx-editor#326]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [x] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

It would be nice to have an option to strip HTML when pasting. Maybe we can do it using  Schemas, but I was unable to get it to work. For instance, I would like to only keep `<strong>, <em>,<u>` and `<br>` elements.

### Version Information

```
ngx-editor: 8.0.1
angular: 10.2.4
```

### Browser

- [x] Chrome - x.x.x
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

_NOTE: Replace `x.x.x` with your version information_

**Comment by sibiraj-s** [comment]
> I would like to only keep `<strong>, <em>,<u>` and `<br>` elements.

does your schema has only these elements or you need to restrict to the given elements only while pasting?.

**Comment by steffensbola** [comment]
Currently, my toolbar has only these basic formatting options. Both alternatives would work for me.
However, when the user pastes something that he copied from somewhere else, the content can bring a lot of garbage which I am unable to control.

**Comment by sibiraj-s** [comment]
You can provide a schema with required marks are nodes. In your case it would be

```ts
import { Schema } from "prosemirror-model";
import { nodes, marks } from "ngx-editor/schema";

const schema = new Schema({
  nodes: {
    doc: basicNodes.doc,
    text: basicNodes.text,
    paragraph: basicNodes.paragraph,
  },
  marks: {
    strong: marks.strong,
    em: marks.em,
    u: marks.u,
  },
});
```

You can also write a plugin

```ts
import { Plugin, PluginKey } from "prosemirror-state";
import { Editor } from "ngx-editor";

const sanitizePastedHTMLPlugin = new Plugin({
  key: new PluginKey("PastePlugin"),
  props: {
    transformPastedHTML(inputHtml: string): string {
      // do something with the html
      const output = sanitize(html);
      return output;
    },
  },
});

const editor = new Editor();
editor.registerPlugin(sanitizePastedHTMLPlugin);
```

Let me know if that helps.

**Comment by steffensbola** [comment]
Yup! 
That does the trick. Perhaps if you could include the plugin example in the docs that would help even more people.

Thank's for the support.

**Comment by sibiraj-s** [comment]
Glad that worked. Closing the issue. Feel free to continue the conversation if needed. 

> Perhaps if you could include the plugin example in the docs that would help even more people.

I will try to do it this weekend. Busy with work. PR's are welcome meanwhile 🙏
