### ISSUE TITLE
[BUG]: The floating menu is hidden in a container with an overflow:hidden

### ISSUE THREAD

**Issue by GitHubish** [sibiraj-s/ngx-editor#327]
There is a problem in the positioning with an `overflow:hidden` container when you are on top. I think the case is not handled in `calculateBubblePosition()` ?

What if the floating menu was created at the body level like the Mention plugin or [ngSelect](https://github.com/ng-select/ng-select#api) with their appendTo solution? These are only ideas...

- [x] Bug report

[Example](https://stackblitz.com/edit/ngx-editor-floating-menu-jey3r8?file=src%2Fapp%2Fapp.component.scss)

![chrome_2021-03-12_15-53-24](https://user-images.githubusercontent.com/7701833/110957819-4b5be980-834c-11eb-80b3-ee088b680e9f.png)

Thanks

**Comment by sibiraj-s** [comment]
> There is a problem in the positioning with an overflow:hidden container when you are on top

that is the expected behaviour when the parent has overflow hidden.

FloatingMenu is exported as component. It can be placed anywhere in the component tree as needed. Also appending the menu to body can be done with few lines of code. I have also made a [stackblitz](https://stackblitz.com/edit/ngx-editor-floating-menu-append-to-body) example for the same. Let me know if anything else is required.

Closing the issue for now. Feel free to continue the discussion if required.

**Comment by gopal-augment** [comment]
@sibiraj-s any solution?

**Comment by sibiraj-s** [comment]
Hi @gopal-augment,

I am not sure what you mean by

> But how can we show the specific tool icons.

What are you referring to as specific tool icons and show it where?

**Comment by gopal-augment** [comment]
We can specify the Toolbar to be shown in the menu by
```
 toolbar: Toolbar = [
    ['bold', 'italic'],
    ['underline', 'strike'],
    ['code', 'blockquote'],
    ['ordered_list', 'bullet_list'],
    [{ heading: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'] }],
    ['link', 'image'],
    ['text_color', 'background_color'],
    ['align_left', 'align_center', 'align_right', 'align_justify'],
  ];
<ngx-editor-menu [editor]="editor" [toolbar]="toolbar"> </ngx-editor-menu>
```

From the above comment:
_FloatingMenu is exported as component. It can be placed anywhere in the component tree as needed. Also appending the menu to body can be done with few lines of code. I have also made a [stackblitz](https://stackblitz.com/edit/ngx-editor-floating-menu-append-to-body) example for the same. Let me know if anything else is required._


In this case, how can we define the toolbar in this floating menu? 
@sibiraj-s

**Comment by sibiraj-s** [comment]
> We can specify the Toolbar to be shown in the menu by
> 
> ```
>  toolbar: Toolbar = [
>     ['bold', 'italic'],
>     ['underline', 'strike'],
>     ['code', 'blockquote'],
>     ['ordered_list', 'bullet_list'],
>     [{ heading: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'] }],
>     ['link', 'image'],
>     ['text_color', 'background_color'],
>     ['align_left', 'align_center', 'align_right', 'align_justify'],
>   ];
> <ngx-editor-menu [editor]="editor" [toolbar]="toolbar"> </ngx-editor-menu>
> ```
> 
> From the above comment: _FloatingMenu is exported as component. It can be placed anywhere in the component tree as needed. Also appending the menu to body can be done with few lines of code. I have also made a [stackblitz](https://stackblitz.com/edit/ngx-editor-floating-menu-append-to-body) example for the same. Let me know if anything else is required._
> 
> In this case, how can we define the toolbar in this floating menu? @sibiraj-s

Hope this is what you are looking for [Stackblitz](https://stackblitz.com/edit/ngx-editor-floating-menu-custom)

**Comment by gopal-augment** [comment]
No. I want to display the toolbar bold, italic, link in your below stackbliz link.
`_FloatingMenu is exported as component. It can be placed anywhere in the component tree as needed. Also appending the menu to body can be done with few lines of code. I have also made a [**stackblitz**](https://stackblitz.com/edit/ngx-editor-floating-menu-append-to-body) example for the same. Let me know if anything else is required._`
