### ISSUE TITLE
[BUG]: Duplicate placeholder for many empty paragraphs

### ISSUE THREAD

**Issue by kadiocat** [sibiraj-s/ngx-editor#330]
# I'm submitting a
- [x] Bug report

## Description
Showing placeholder for every empty paragraph when content editor is empty.
![image](https://user-images.githubusercontent.com/40465491/112594805-86fdb580-8e1a-11eb-9e67-5a6b5ad89533.png)
Please add doc.childCount check.
![image](https://user-images.githubusercontent.com/40465491/112595181-199e5480-8e1b-11eb-889a-d3b1e804690e.png)

### Version Information
ngx-editor: 8.1.0
angular: 9.1.7

### Browser
- [x] Chrome - 88.0.4324.190

**Comment by sibiraj-s** [comment]
Will fix. Regression from 8.0.1 it seems

**Comment by sibiraj-s** [comment]
Fixed in v8.1.1. Thanks @kadiocat
