### ISSUE TITLE
[feature]: upload image from local system

### ISSUE THREAD

**Issue by roymj88** [Sibiraj-S/ngx-editor#34]
Is there an option to upload file via browse instead of uploading through link?

**Comment by Sibiraj-S** [comment]
Currently not included but I have been working on it.

**Comment by lruiz-invidgroup** [comment]
How works the image uploader, the POST method need something in the return?

**Comment by AnelR** [comment]
Good day,

I am using the npm NgxEditor control in my Angular 7 project. The upload works fine in uploading the file but when the url is returned the page reloads instead of just inserting the image in the editor so I can continue editing. Inserting image via the URL works 100%, it adds the image in the editor and I can continue typing in the editor.

Is it possible to set the buttons to hidden? Example: Only allow upload of files.
![Image Upload](https://user-images.githubusercontent.com/37829904/56269414-e6fa6600-60f3-11e9-91ff-dcb37953e154.png)

**Comment by mateuspmello** [comment]
> Good day,
> 
> I am using the npm NgxEditor control in my Angular 7 project. The upload works fine in uploading the file but when the url is returned the page reloads instead of just inserting the image in the editor so I can continue editing. Inserting image via the URL works 100%, it adds the image in the editor and I can continue typing in the editor.
> 
> Is it possible to set the buttons to hidden? Example: Only allow upload of files.
> ![Image Upload](https://user-images.githubusercontent.com/37829904/56269414-e6fa6600-60f3-11e9-91ff-dcb37953e154.png)

How did you implements this?
I'm having this problem: Cannot POST /assets/img

**Comment by AnelR** [comment]
In my html I have the following:
 <app-ngx-editor #edtTest name="edtTest " [config]="htmlEditorConfig" height="300px"
                minHeight="300px" [spellcheck]="true" [(ngModel)]="bindingModel"></app-ngx-editor>

In TS file: 
htmlEditorConfig = {
    editable: true,
    spellcheck: true,
    height: "10rem",
    minHeight: "5rem",
    width: "auto",
    minWidth: "0",
    translate: 'no',
    enableToolbar: true,
    showToolbar: true,
    placeholder: "Enter text here...",
    imageEndPoint: t**his.imageUploadUrl**,
    toolbar: [
      ["bold", "italic", "underline", "strikeThrough", "superscript", "subscript"],
      ["fontName", "fontSize", "color"],
      ["justifyLeft", "justifyCenter", "justifyRight", "justifyFull", "indent", "outdent"],
      ["cut", "copy", "delete", "removeFormat", "undo", "redo"],
      ["paragraph", "blockquote", "removeBlockquote", "horizontalLine", "orderedList", "unorderedList"],
      ["link", "unlink", "image"]
    ]
  };

the imageUploadUrl = `${this.baseUrl}` + '/image/uploadfiles' -- this is my API url () that uploads the file to the assets folder and then returns the url location in url form. Example http://MyApplication/Api/UploadFiles" http://MyApplication/assets/uploadedimage.png"

API Method
[HttpPost("UploadFiles")]
public async Task<IActionResult> UploadFiles(List<IFormFile> file)
        {

}

**Comment by AhmedHlaimi** [comment]
@AnelR  can u give us ur response obecjt

**Comment by Sivakaresh** [comment]
@AnelR is it possible to get API method implementation for more illustration?
