### ISSUE TITLE
[Feature]: Disable editor programmatically

### ISSUE THREAD

**Issue by betodasilva** [sibiraj-s/ngx-editor#341]
# I'm submitting a
- [ x ] Documentation issue or request

## Description
In the [docs](https://sibiraj-s.github.io/ngx-editor/#/editor) it says the editor instance has both disable() and enable() methods but it's not true 
 
<img width="445" alt="Screen Shot 2021-05-04 at 20 37 50" src="https://user-images.githubusercontent.com/17956938/117082419-9a087d00-ad18-11eb-95ab-763680fa0842.png">

### Version Information

```
ngx-editor: 9.0.0
angular: 11.2.2
```

**Comment by sibiraj-s** [comment]
I have updated the docs now.
