### ISSUE TITLE
[BUG]: Incorrect url validation

### ISSUE THREAD

**Issue by vitaaaly** [sibiraj-s/ngx-editor#343]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

Validation failed when I type parameters in url input.
For example:

![image](https://user-images.githubusercontent.com/43273546/117830177-0e44a280-b27c-11eb-9e03-c1a5c666c093.png)

This url 100% correct.

### Version Information

```
ngx-editor: 8.1.1
angular: 9.1.4
```

### Browser

- [x] Chrome - 90.0.4430.93
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

**Comment by vitaaaly** [comment]
> Please share an URL sample for me to validate.

Any url that contains '?'
For example:

https://news.google.com/topstories?tab=rn

**Comment by vitaaaly** [comment]
> I can't do it today. I have some personal emergency. At hospital. Feel free to raise a PR, the regex can be non strict. May be this https://regexr.com/39p0t. I will try to merge and release by tomorrow EOD

I fixed this bug in PR.
Review it please.

**Comment by sibiraj-s** [comment]
Fixed in v9.0.2
