### ISSUE TITLE
[BUG]: Missing titles on links and images menu items

### ISSUE THREAD

**Issue by vitaaaly** [sibiraj-s/ngx-editor#345]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

All menu items have titles with localization.
For example: 
![image](https://user-images.githubusercontent.com/43273546/118109465-ed9a5b00-b3e9-11eb-97aa-c344cdd6067a.png)

But titles missing on links and images menu items:
![image](https://user-images.githubusercontent.com/43273546/118109570-0c98ed00-b3ea-11eb-9db5-06318b4f5fc0.png)

### Version Information

```
ngx-editor: 8.1.1
angular: 9.1.4
```

### Browser

- [x] Chrome - 90.0.4430.93
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

**Comment by sibiraj-s** [comment]
Fixed in v9.0.2

**Comment by vitaaaly** [comment]
Thank you!
