### ISSUE TITLE
[BUG]: With ChangeDetectionStrategy.OnPush, toolbar does not update correctly

### ISSUE THREAD

**Issue by kiwidude68** [sibiraj-s/ngx-editor#348]
# I'm submitting a
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

Two bugs in one. If your parent component containing the ngx-editor is set to OnPush change detection, then there is a lag of when the toolbar gets updated to reflect the styles of the currently selected content, and then when it does update the bar after a second mouse click it is showing the style of the previous selection in the toolbar.

e.g. Say I have this text: A quick brown **fox** jumps _over_ the lazy dog.

- If I click somewhere in fox, the first click will show no change to toolbar. Obviously wrong, it should show bold.
- If I then click within "quick", the toolbar will update to show a style of bold - again wrong, it should show no styling.

Actually this is just one example of it going wrong - if you replace the form control you are binding to with a new value, the toolbar won't update at all etc. So for example on my screen I have a list of items on the left, and on the right an ngx-editor that is bound to some data off whatever item I select in the list. The text content of ngx-editor updates correctly fine, but the toolbar menu buttons stay selected with values for whatever the last "edit" was done inside the editor.

### Version Information

```
ngx-editor: 9.0.2
angular: 11.2.14
```

### Browser

- [X] Chrome -  91.0.4472.77
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

**Comment by sibiraj-s** [comment]
Can you try adding this.

```ts
this.editor.update.subscribe(() => {
  this.changeDetectorRef.markForCheck()
})
```

**Comment by kiwidude68** [comment]
Hi there, thanks so much for the quick reply. Yes that makes a big improvement, thanks!

One semi-related question. When I change the value of the underlying form control (as I indicated above by choosing a different parent item from the list), if I had selected text from the previous item prior to the change of value, then the selection inside the ngx-editor is not being reset all the time, and results in some weirdness at times. Sometimes it resets, sometimes it doesnt. Sometimes the selection ends up on a different word in the new text, sometimes it ends up spread across multiple words. Is that something you would expect to happen?

**Comment by sibiraj-s** [comment]
Hi, I understand that selection is not reset sometimes, but I couldn't understand when exactly this is happening. Can you explain with a scenario?

**Comment by kiwidude68** [comment]
Sorry for the lack of clarity. Here is an example for you. Say I have two items on my list, with differing text being bound to the text editor that I toggle between. On the first item I double click the word "is", it selects "is " and I make it bold
![image](https://user-images.githubusercontent.com/23359593/121868144-8dece380-ccf8-11eb-8bba-ded719ecf5dc.png)

Then without clearing the selection within the editor I click the second list item, changing the bound value text for the editor. The selection shown within the editor shows as this:
![image](https://user-images.githubusercontent.com/23359593/121868341-c5f42680-ccf8-11eb-98c1-b07aa5ee5c35.png)

**Comment by sibiraj-s** [comment]
Strange. i will check this out. May be till then can you try using `focus()` method, before changing the value? 

```ts
this.editor.commands.focus()
```

**Comment by sibiraj-s** [comment]
@kiwidude68 did it work?

**Comment by sibiraj-s** [comment]
I am closing this issue for now. If you still face the issue. Please provide a reproducible example, may be a stackblitz, will be better.
