### ISSUE TITLE
[BUG] Linking does not work on Floating Menu

### ISSUE THREAD

**Issue by Gongsta** [sibiraj-s/ngx-editor#349]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

Hello, I followed the documentation for a floating menu with custom elements from [here](https://sibiraj-s.github.io/ngx-editor/#/floating-menu). It seems that the "link" toolbar option doesn't work, as I am unable to enter the URL when the input is prompted to me. It doesn't work on the original demo either, as you can test it out yourself: https://stackblitz.com/edit/ngx-editor-floating-menu-custom 

 
### Version Information

```
ngx-editor: 10.0.0
angular: 12.0.2
```

### Browser

- [X] Chrome - 91.0.4472.101
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

_NOTE: Replace `x.x.x` with your version information_

**Comment by sibiraj-s** [comment]
Found the issue. The example just re-uses the menu as a floating menu. I forgot that it had input elements. I will fix it by tomorrow.
