### ISSUE TITLE
I want to upload image base64..!!!!!

### ISSUE THREAD

**Issue by id1945** [sibiraj-s/ngx-editor#353]
Pls

**Comment by sibiraj-s** [comment]
The editor doesn't support uploading images of any type. You can create a custom menu with upload options, once uploaded you can insert the image into the editor.

Refer https://sibiraj-s.github.io/ngx-editor/#/menu?id=custom-menu for creating a custom menu. and https://sibiraj-s.github.io/ngx-editor/#/commands for the commands.
