### ISSUE TITLE
Runtime translation

### ISSUE THREAD

**Issue by vitaaaly** [sibiraj-s/ngx-editor#354]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [x] Feature request
- [ ] Documentation issue or request

## Description

I use ngx-translate for components runtime translation.
How can I translate ngx-editor in runtime?
In case, when user can change language on page.

In documentation I found only this locale configuration:
https://sibiraj-s.github.io/ngx-editor/#/?id=optional-configuration

### Version Information

```
ngx-editor: 9.0.2
angular: 9.1.4
```

### Browser

- [x] Chrome - 91.0.4472.124

<br>

**Comment by sibiraj-s** [comment]
I have't been using angular for a while, I am little rusty around this area. do you have any implementation concept in mind? I can try to implement it.

**Comment by vitaaaly** [comment]
> I have't been using angular for a while, I am little rusty around this area. do you have any implementation concept in mind? I can try to implement it.

I found a solution.
In my app, i store "locals" in the variable.
When user chnage language I just change "locals".
For example:
`
onChangeLanguage() {
locals.bold = data.bold;
locals.italic = data.italic;
}
`

It works fine!
