### ISSUE TITLE
[Feature]: Add more support for dynamic markdown (italics and bold)

### ISSUE THREAD

**Issue by Gongsta** [sibiraj-s/ngx-editor#355]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [x] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

Currently, with the editor, when we add the # sign, it automatically converts it into a heading just like in markdown. This is great. However, there isn't the same support with italics and bold characters using the * and **. [Notion](https://www.notion.so/)'s
editor supports this. Would be beneficial to have that support on ngx-editor as well as it seems to be standard.

### Version Information

```
ngx-editor: 10.0.2
angular: 12.0.2
```

### Browser

- [x] Chrome - 91.0.4472.101
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

_NOTE: Replace `x.x.x` with your version information_

**Comment by sibiraj-s** [comment]
Fixed in v10.1.0
