### ISSUE TITLE
[BUG]: Command + U shortcut not working for underlining

### ISSUE THREAD

**Issue by Gongsta** [sibiraj-s/ngx-editor#356]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

When using the editor on my Macbook, it seems that the command + u shortcut does not work on the text that I highlight. Command + B (for bolding text) / Command + I (for italics) work fine. 

After some more testing, I notice that Control + U works for underlining. This should be changed to Command + U.
### Version Information

```
ngx-editor: 10.0.0
angular: 12.0.2
```

### Browser

- [x] Chrome - 91.0.4472.101
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

_NOTE: Replace `x.x.x` with your version information_

**Comment by sibiraj-s** [comment]
Fixed in v10.1.0
