### ISSUE TITLE
[Question] Height not set on startup

### ISSUE THREAD

**Issue by laxman1129** [Sibiraj-S/ngx-editor#36]
Hi

I am setting height like below
`<app-ngx-editor [(ngModel)]="content" [height]="300"></app-ngx-editor>`

On startup the editor size is not changed. If I try to increase the height by dragging then it takes the height specified.

Thanks

**Comment by Sibiraj-S** [comment]
You should mention the unit (all acceptable units such as px, rem, cm etc). Height property accepts a string

**Comment by Sibiraj-S** [comment]
@laxman1129 . Did that work?

**Comment by Sibiraj-S** [comment]
closing as answered.

**Comment by androidovshchik** [comment]
Hi
May it be autimatically computed? 100% avaliable height
