### ISSUE TITLE
[Enhancement]:  Don't use rems to size elements

### ISSUE THREAD

**Issue by wawyed** [sibiraj-s/ngx-editor#360]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [X] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

In our project we set our html font-size to 10px so we can use font-sizes based on it but it affects the size of the ngx-editor (without a way to change it). Would it be possible to use px so that the styles don't get affected by the html font-size.

Thanks.

### Version Information

```
ngx-editor: latest
angular: any
```

**Comment by sibiraj-s** [comment]
Fixed in v11.
