### ISSUE TITLE
How to set editor as readonly?

### ISSUE THREAD

**Issue by chengB12** [sibiraj-s/ngx-editor#361]
# I'm submitting a

- [X] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [ ] Feature request
- [X] Documentation issue or request

## Description

I upgrade ngx from 4.x to 10.x, ng build complain that [config] is not property of app-ngx-editor

I used to have [config]="editorConfig", while editorConfig = { editable: false }

Now I didn't found any documentation to bring back editable flag.

I tried [disabled]="true", it seems has no effect at all: https://stackblitz.com/edit/ngx-editor-suinw7?file=src/app/app.component.html

### Version Information

```
ngx-editor: 10.1.0
angular: 12.2.2
```

### Browser

- [X] Chrome - 92
- [ ] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

<br>

**Comment by sibiraj-s** [comment]
You should be able use `disabled` property like you do for input components. Let me know if it is not working. I can check.

**Comment by chengB12** [comment]
you can click the stackbliz link, it has [disabled]="true" yet the toolbar is disabled, however, not main editor body

**Comment by sibiraj-s** [comment]
Oh. Something might have been broken. I will check, but it was the method.

**Comment by sibiraj-s** [comment]
@chengB12 . Something is changed how angular handles this I think.

```ts
form = new FormGroup({
  editorContent: new FormControl(
    { value: jsonDoc, disabled: true },
    Validators.required()
  ),
});
```

this works and to programatically update the form, you can use.

```ts
this.form.get("editorContent").disable();
this.form.get("editorContent").enable();
```

**Comment by sibiraj-s** [comment]
Okay. ☝️ that how you do it for reactive forms. the `disabled` attribute will work as usual for the rest. Pardon me, I am slightly outdated.
