### ISSUE TITLE
How to autofocus?

### ISSUE THREAD

**Issue by waveiron** [sibiraj-s/ngx-editor#364]
Is there any options for autofocusing?

Maybe something like this:

```html
<ngx-editor [autofocus]="true"></ngx-editor>
```

**Comment by sibiraj-s** [comment]
I will see if I could do something. but you should be able to use.

```ts
editor.commands.focus().exec()
```

during OnInit/AfterViewInit should do the same.

**Comment by sibiraj-s** [comment]
You can now use.

```ts
new Editor({
  attributes: { autofocus: 'true' }
})
```
