### ISSUE TITLE
Question: how to show custom popup dialog for URL

### ISSUE THREAD

**Issue by mvandenabeele** [sibiraj-s/ngx-editor#371]
Hi,

I'm using ngx-editor for a small project where workers need to be able to insert predefined links. If they need to memorize and retype these URLs, the user experience is not as good as could be, so I'm investigating the possibility to show a popup where they can just select the item they want to link to. Could this be done? Any pointers would be greatly appreciated!

Merijn

**Comment by sibiraj-s** [comment]
You should be able to insert link by

```ts
const editor = new Editor()
editor.commands.insertLink('Google', {href: 'https://google.com', target: '_blank'})
```

> so I'm investigating the possibility to show a popup

you'll have to create the popup yourself. You can insert the link from there using the above command. There is also  [custom menu](https://sibiraj-s.github.io/ngx-editor/#/menu?id=custom-menu). using custom menu, you can create your own button component which will be rendered at the end of the toolbar item, which you can use to trigger the popup.
