### ISSUE TITLE
[Bug]: Image Alt Show null

### ISSUE THREAD

**Issue by cctomato** [sibiraj-s/ngx-editor#377]
## Description

When insert a image includ alt，it can be displayed.
<img width="531" alt="1" src="https://user-images.githubusercontent.com/18543001/149494785-4270a1e0-8d80-403d-94fe-a853646eca9b.png">

When resize the picture, alt becomes null.
<img width="496" alt="2" src="https://user-images.githubusercontent.com/18543001/149494794-a5d975fa-4785-456d-a5d8-37e432cf6a37.png">

### Version Information
````
ngx-editor: 11.1.1
angular: 12.2.14
````

### Browser
````
Chrome - 97.0.4692.71
````

### OS
````
Windows - 10
````

### Version

v11.1.1

### What browsers are you seeing the problem on?

Chrome

**Comment by sibiraj-s** [comment]
Fixed in v12.1.1
