### ISSUE TITLE
[Bug]: Colorpicking does not work in Angular Material Mat-Dialogs

### ISSUE THREAD

**Issue by DywiTom** [sibiraj-s/ngx-editor#378]
### What happened?

Hello!

First of all, thank you for your great work!
Colorpicking (Font, Background) does not work in Mat-Dialogs (Angular Material).
Can you check this please?

![Unbenannt](https://user-images.githubusercontent.com/87300270/150946706-d20b16ae-2a3f-4e29-b1be-35fc17ee00dc.png)

`
"dependencies": {
    "@angular/animations": "~13.1.3",
    "@angular/cdk": "~13.1.3",
    "@angular/common": "~13.1.3",
    "@angular/compiler": "~13.1.3",
    "@angular/core": "~13.1.3",
    "@angular/forms": "~13.1.3",
    "@angular/material": "~13.1.3",
    "@angular/material-luxon-adapter": "^13.1.3",
    "@angular/platform-browser": "~13.1.3",
    "@angular/platform-browser-dynamic": "~13.1.3",
    "@angular/router": "~13.1.3",
    "chart.js": "^3.7.0",
    "hammerjs": "^2.0.8",
    "luxon": "^2.3.0",
    "ng-gallery": "^6.0.0",
    "ng2-charts": "^3.0.8",
    "ngx-editor": "^12.1.0",
    "rxjs": "^7.5.2",
    "tslib": "^2.3.1",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.1.3",
    "@angular/cli": "~13.1.4",
    "@angular/compiler-cli": "~13.1.3",
    "@angular/localize": "^13.1.3",
    "@types/luxon": "^2.0.9",
    "@types/node": "^17.0.12",
    "codelyzer": "^6.0.2",
    "protractor": "~7.0.0",
    "ts-node": "^10.4.0",
    "tslint": "~6.1.0",
    "typescript": "^4.4.4",
    "webpack-bundle-analyzer": "^4.5.0"
  }
`

### Version

latest

### What browsers are you seeing the problem on?

Chrome

### Link to reproduce

Stackblitz Link:
https://stackblitz.com/edit/ngx-editor-color-bug?devtoolsheight=33&file=src/app/app.component.ts

### Relevant log output

Nothing.

**Comment by sibiraj-s** [comment]
It works fine for me. Can you share a reproducible code may be a stackblitz/repo, where I can reproduce this code?

**Comment by DywiTom** [comment]
Sorry, i can't create a stackblitz repo (can't fork material). The Bug only appears in Mat-Dialogs.

**Comment by sibiraj-s** [comment]
Thanks. checking...

**Comment by sibiraj-s** [comment]
Should be fixed in [v12.1.2](https://github.com/sibiraj-s/ngx-editor/releases/tag/v12.1.2)
