### ISSUE TITLE
[Bug]: Command Exec scrolls without scrollIntoView

### ISSUE THREAD

**Issue by jode-reflact** [sibiraj-s/ngx-editor#389]
### What happened?

Im using the following code snippet for enabling an bullet list in my editor
`this.editor.commands.toggleBulletList().exec();`

Besides not using the scrollIntoView Function the window is still scrolled to the editor after execution.
If this is not a bug, how do I prevent such behaviour?

### Version

v12.2.2

### What browsers are you seeing the problem on?

Chrome

**Comment by thuh-reflact** [comment]
any news on this?

**Comment by sibiraj-s** [comment]
Sorry, had some personal emergencies. Back now. will look into it this weekend.

**Comment by sibiraj-s** [comment]
Sorry for the delay.

> If this is not a bug, how do I prevent such behaviour?

This is not a bug. All commands automatically scrolls into view by default. `scrollIntoView` is to explicitly scroll based on the need. The editor uses `prosemirror-commands` under to work with commands. so unless natively rewriting all commands, its not possible to fix straightaway.

But, looking into other options to mitigate this issue.

**Comment by sibiraj-s** [comment]
That might not look neat. there will be a jump.

Alternatively, there is [handleScrollToSelection](https://prosemirror.net/docs/ref/#view.EditorProps.handleScrollToSelection) which could help.

```js
handleScrollToSelection() {
 return true
}
```

but this will block all the scrolls including `scrollIntoView` method. looking into a way to differentiate them.

**Comment by jode-reflact** [comment]
`handleScrollToSelection` looks useful, is there any way to override it? Maybe through the editor config?

**Comment by sibiraj-s** [comment]
Not possible, I can add but it will block all scrolls. unless able to differentiate the transaction. that is okay?

**Comment by jode-reflact** [comment]
Yes that would be okay for my purpose

**Comment by sibiraj-s** [comment]
Will add that by today or tomorrow.

**Comment by sibiraj-s** [comment]
@jode-reflact handleScrollToSelection  is added in [v12.4.0](https://github.com/sibiraj-s/ngx-editor/releases/tag/v12.4.0)

**Comment by jode-reflact** [comment]
Thanks, works like a charm!
