### ISSUE TITLE
[Bug]: When enabling the Floating Menu, typing the text and displaying the text delayed

### ISSUE THREAD

**Issue by gopal-augment** [sibiraj-s/ngx-editor#392]
### What happened?

To show the tool bar, I used the floating menu stye

```html
<ngx-editor
  [editor]="editor"
  [ngModel]="textHtml"
  (ngModelChange)="savePresenterNotes($event)"
  [placeholder]="'Enter Presenter Notes'"
  spellcheck="false"
></ngx-editor>
<ngx-editor-floating-menu [editor]="editor"></ngx-editor-floating-menu>
```

But when typing the text gets delayed to show the text in the editor. It looks like hanging for a few seconds and then showing the text

### Version

v9.0.2

### What browsers are you seeing the problem on?

Chrome

**Comment by sibiraj-s** [comment]
v9 is too old. Please update to the latest to get the latest performance improvements.

**Comment by gopal-augment** [comment]
But our angular version is 9.1.12

**Comment by sibiraj-s** [comment]
Angular 9 is very old and very far from LTS. Supporting older versions is a pain. I recommend updating your project.

**Comment by gopal-augment** [comment]
Okay. Thanks
