### ISSUE TITLE
[Feature request]: Missing functionalities from one of first version

### ISSUE THREAD

**Issue by MDzyga** [sibiraj-s/ngx-editor#394]
### Proposal

Hi,
I use one of first version ngx-editor and notice that you released new version. I noticed that you don't have all functionalities (listed below) which are in my version. Do you have them in your schedule?
- strikethrough
- superscript
- subscript
- font family
- color picker
- indent
- outdent
- cut
- copy
- delete
- clear formatting
- undo
- redo
- paragraph
- horizontal line
- insert video

![image](https://user-images.githubusercontent.com/38663990/163704505-a7aaa27b-d85d-4b45-8671-45859cdde9c6.png)

I think the most important for me is horizontal line.
![image](https://user-images.githubusercontent.com/38663990/163704511-df0c32ea-806d-4ae3-a370-fecd6ab24716.png)

In HTML it looks like stylish paragraph.
`<p style="border-top: 1px solid rgb(0, 0, 0); border-bottom: 1px solid rgb(0, 0, 0); border-left: none; border-right: none; padding: 0.01in 0in; direction: ltr; text-transform: uppercase; color: rgb(0, 0, 0); text-align: center;"></p>`

**Comment by sibiraj-s** [comment]
Originally, the editor was built on top of [execCommand](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) where the implementation is straightforward but the api is unreliable. Later the editor is ported to use prosemirror, most of the features were made but some were not added which needs some time/effort to implement, which ATM I don't have.

> I think the most important for me is horizontal line.

The rule is already there, but just not exported as menu. I can add that. should be a minor change.

**Comment by sibiraj-s** [comment]
Sorry for the long long delay.

The horizontal rule has been added, include menu item `horizontal_rule` to enable the item. it might be hidden by default.

Thank you
