### ISSUE TITLE
[Bug]: Protocols are not automatically added to the generated urls.

### ISSUE THREAD

**Issue by watchity** [sibiraj-s/ngx-editor#396]
### What happened?

If you add a link, the editor does not automatically add the protocol, either http, https... so if the user simply enters google.es, this will redirect to https://mywebsite/google.es which is totally incorrect and frustrating for the user who clicks on the link. It would be better to add this header automatically, like ngx-quill or other editors do, or at least offer this one.

### Version

v12.2.2

### Angular Version

v13.3.2

### What browsers are you seeing the problem on?

Firefox, Chrome

### Link to reproduce

https://stackblitz.com/edit/angular-ivy-1fpe4o

### Willing to submit a PR?

Yes

**Comment by watchity** [comment]
It would also be a valid option to allow a custom urls form validator. The one I need is this one: 
`((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?[A-Za-z0-9.-]+|(:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9.-]+)((?:\/[\+~%\/.\w-_]*)?\??(?:[-\+=&;%@.\w_]*)#?(?:[\w]*))?)` 

Which is more restrictive than the current one:
`(https?://)?([\\da-z.-]+)\\.([a-z.]{2,6})[/\\w .-]*/??([^#\n\r]*)?#?([^\n\r]*)`

Is this possible to change in the current versions?

**Comment by sibiraj-s** [comment]
> Is this possible to change in the current versions?

That would be a breaking change. 

Will see what can be done without breaking anything. Open to alternate suggestions.

**Comment by schmoizz** [comment]
@sibiraj-s can the Validator Pattern of the Link Component be transfered to a configuration Entry of Editor having the original Pattern as a default value?

**Comment by sibiraj-s** [comment]
Yes @schmoizz . We can do that. We could give preference to the one from options.

PR welcome.
