### ISSUE TITLE
[Bug]: Can't disable specific control

### ISSUE THREAD

**Issue by rogerg93** [sibiraj-s/ngx-editor#402]
### What happened?

I removed the controls from the toolbar by doing this:

`public toolbar: Toolbar = [['bold', 'italic'], ['underline'], [], [], [], ['link'], [], [], []];`

But I can still add an ordered list if I write something like 1.<space>

How can I remove a certain control for good?

### Version

v12.3.0

### Angular Version

v13.2.6

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

**Comment by sibiraj-s** [comment]
All controls are configurable.

```ts
public toolbar: Toolbar = [['bold', 'italic'], ['underline'], ['link']];
```

should do, the inner array just provides grouping, nothing else.

> How can I remove a certain control for good?

Not able to follow, can you elaborate?

**Comment by rogerg93** [comment]
> 

Hey thanks for the answer although this does not solve my problem. The thing is that I only want to allow those 4 editing options and nothing else. If I for example write `1.<and hit space>` it will treat it as a list instead of just normal text.

**Comment by sibiraj-s** [comment]
Right. That only works for menu. doesn't disable features.

**Comment by rogerg93** [comment]
Is there a way to also remove it from the editor itself? For example the user can still just copy paste whatever HTML he wants and it will be displayed.

An expected behaviour to me would be that every html tag that is not visible in the toolbar is also just converted to plain text when applied.

**Comment by sibiraj-s** [comment]
You can manually provide the schemas and include only the ones you want. See https://sibiraj-s.github.io/ngx-editor/#/schema for how to provide a schema.

See https://github.com/sibiraj-s/ngx-editor/blob/master/projects/ngx-editor/schema/index.ts for the default schema. All you need to do is to just ignore the ones you don't need.

**Comment by sibiraj-s** [comment]
There are also few other options you can configure https://sibiraj-s.github.io/ngx-editor/#/editor?id=options

**Comment by sibiraj-s** [comment]
Closing as resolved. Feel free to continue the conversation if required.
