### ISSUE TITLE
[Bug]: NG Build and NPM start giving errors in ProseMirror under NGx- Editor

### ISSUE THREAD

**Issue by johnantony92** [sibiraj-s/ngx-editor#408]
### What happened?

Ng build suddenly started giving for ngx-editor it seems like something from the update of prosemirror command it was working fine and started giving error in the last few days
![issue](https://user-images.githubusercontent.com/13538494/171848781-0a1e3b6f-7fe7-4a05-af2b-6929e97c530e.png)

### Version

9.02

### Angular Version

11

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

**Comment by sibiraj-s** [comment]
Please see the pinned issue for the cause and how to fix. https://github.com/sibiraj-s/ngx-editor/issues/406.

This happened due to the dependencies of ngx-editor introduced breaking changes in a non major version.

Since this is a very old version I won't be able to fix them. A a short fix. download the package from npm. Remove the `caret semver` from all the dependencies and use that by using local installation.

**Comment by johnantony92** [comment]
@sibiraj-s Cant update the package to 13 since i got other dependencies .Also tried downloading the package and removing caret and publishing my private server but renaming the package is giving me this issue
![image](https://user-images.githubusercontent.com/13538494/171861675-95fd9465-e7f0-4e10-a1b7-0967f36bb95e.png)

Can you help on this?otherwise i would have to go for major changes.Can we have a patch release for older package?

**Comment by rko9** [comment]
when you say download package from npm, which package you referring too? I'm using yarn in place of npm.
and ngx-editior version is 8.1.1

**Comment by sibiraj-s** [comment]
You don't need to publish to private server. Just zip the changes and specify the path in the dependency under the same name

```
ngx-editor: file://path-to-zip 
```

**Comment by sibiraj-s** [comment]
You can get the tar like this

```bash
npm view ngx-editor@8 dist.tarball
```

It will give you the url for the tar. you can download.

**Comment by johnantony92** [comment]
@sibiraj-s issue with the approach you mentioned is each time I push my build using ci/cd the local path(since it will try to install the dependencies from the path mentioned) wont work right that's why I went for private server.

**Comment by johnantony92** [comment]
@sibiraj-s Or you are saying i would have to bundle .tgz file with the project?Is there something that i can do publish in the local server as bundling the tar with project wont be better idea .Each time during the publish using ci/cd it tries to install the dependencies so giving a local path wont work

**Comment by sibiraj-s** [comment]
Yeah, bundling with project is the shortest one. To publish under different name, it would require many changes, because of internal dependencies

**Comment by sibiraj-s** [comment]
> Understood .so you meant to create a .tgz from the local build and mentioned that in the pacakge.json depencies right?

download the build. -> extract it -> pin all the dependencies -> rezip it. and use that.

**Comment by rko9** [comment]
> .tgz from the local build

Tried that add tar as local dependency but still throwing same errors
<img width="1336" alt="Screenshot 2022-06-03 at 8 35 25 PM" src="https://user-images.githubusercontent.com/13873719/171881304-ee041276-1493-4244-b1b0-b53056778434.png">

**Comment by sibiraj-s** [comment]
what dependency version you are using?

**Comment by sibiraj-s** [comment]
Unpin all the dependencies. Remove the caret and reinstall.

**Comment by johnantony92** [comment]
@sibiraj-s .Understood the approach you mentioned but can we have a patch-package release ?So that it will be easier for all the people that are stuck with older version and cant update

**Comment by sibiraj-s** [comment]
Not sure, Several versions are affected. It's not possible to patch all. And there are several changes between versions. I don't have the bandwidth ATM. I can try this weekend. Can't be sure.

To avoid getting into these situations. I have pinned all dependencies for now.

**Comment by johnantony92** [comment]
@sibiraj-s Done the local .tgz but still getting the error .Any idea about this
![image](https://user-images.githubusercontent.com/13538494/171894335-5ab632db-561b-4f60-848d-92cfcd13ffb8.png)

**Comment by sibiraj-s** [comment]
Sorry I did not see the notification. Can you try clearing node modules and reinstall?

**Comment by rko9** [comment]
> Pin all the dependencies. Remove the caret and reinstall.

Tried That too, but same errors are still coming.

**Comment by rko9** [comment]
> @sibiraj-s Done the local .tgz but still getting the error .Any idea about this ![image](https://user-images.githubusercontent.com/13538494/171894335-5ab632db-561b-4f60-848d-92cfcd13ffb8.png)

Did you get any solution for this error.

**Comment by johnantony92** [comment]
> > @sibiraj-s Done the local .tgz but still getting the error .Any idea about this ![image](https://user-images.githubusercontent.com/13538494/171894335-5ab632db-561b-4f60-848d-92cfcd13ffb8.png)
> 
> Did you get any solution for this error?

Not till now.Tried the same steps that @sibiraj-s  mentioned not sure what went wrong

**Comment by johnantony92** [comment]
> Sorry I did not see the notification. Can you try clearing node modules and reinstall?

Tried that and removed package.lock.json but still getting 
![image](https://user-images.githubusercontent.com/13538494/172039282-726cd31b-f4b9-475f-b4a7-bb71db8c43be.png)

**Comment by sibiraj-s** [comment]
@johnantony92 . Try this solution I was able to get the editor working in lower versions. https://github.com/sibiraj-s/ngx-editor/issues/409#issuecomment-1146745067.

You don't have to zip, just use `npm overrides` or `yarn resolutions`.

**Comment by johnantony92** [comment]
> @johnantony92 . Try this solution I was able to get the editor working in lower versions. [#409 (comment)](https://github.com/sibiraj-s/ngx-editor/issues/409#issuecomment-1146745067).
> 
> You don't have to zip, just use `npm overrides` or `yarn resolutions`.

thanks @sibiraj-s 
![image](https://user-images.githubusercontent.com/13538494/172040338-2b4794d9-ec9e-470f-a79e-4634cc9e789c.png)
Is this how overrides work?

**Comment by sibiraj-s** [comment]
> > @johnantony92 . Try this solution I was able to get the editor working in lower versions. [#409 (comment)](https://github.com/sibiraj-s/ngx-editor/issues/409#issuecomment-1146745067).
> > You don't have to zip, just use `npm overrides` or `yarn resolutions`.
> 
> thanks @sibiraj-s ![image](https://user-images.githubusercontent.com/13538494/172040338-2b4794d9-ec9e-470f-a79e-4634cc9e789c.png) Is this how overrides work?

Yes @johnantony92 .
