### ISSUE TITLE
[Feature request]: mailto links

### ISSUE THREAD

**Issue by seabmn** [sibiraj-s/ngx-editor#414]
### Proposal

the link editor has a validation pattern that denies links in the format:

`mailto:test@test.com`

it insists on either an http / https / or no protocol provided.

would it be possible to add mailto: as a valid protocol so content can be authored that contains email links within it.

**Comment by sibiraj-s** [comment]
Pr welcome.

**Comment by schmoizz** [comment]
Feature Request can be closed, didn't it?
@sibiraj-s can you maybe publish another release so i can update my project? Thanks in Advance

**Comment by sibiraj-s** [comment]
Published in [v14.1.0](https://github.com/sibiraj-s/ngx-editor/releases/tag/v14.1.0). Thanks for the remainder.
