### ISSUE TITLE
[Bug]: takeUntil import

### ISSUE THREAD

**Issue by hzorr** [sibiraj-s/ngx-editor#419]
### What happened?

Hi, im geting this error, when serving an angular project with ngx-editor v13
./node_modules/ngx-editor/fesm2015/ngx-editor.mjs:1160:34-43 - Error: export 'takeUntil' (imported as 'takeUntil') was not found in 'rxjs'

### Version

v13.0

### Angular Version

v13.3.11

**Comment by sibiraj-s** [comment]
Try updating to rxjs 7.5 or later

**Comment by hzorr** [comment]
Thanks for reply,
From rxjs manual import should be
import { takeUntil } from 'rxjs/operators' , they changed that while ago, I'm not sure they bring that back in 7.5

**Comment by sibiraj-s** [comment]
Not sure. For now, I hope you can upgrade. will fix this sooner.

**Comment by sibiraj-s** [comment]
Fixed in v14.2.0
