### ISSUE TITLE
Toolbar-set shows as a grey dot when there are no buttons configured.

### ISSUE THREAD

**Issue by FolkertCode** [Sibiraj-S/ngx-editor#43]
Toolbar-set shows as a grey dot when there are no buttons configured:
![image](https://user-images.githubusercontent.com/5489255/35276802-ef76447c-0044-11e8-8b25-e12f2f677aa4.png)

![image](https://user-images.githubusercontent.com/5489255/35276908-4f46c818-0045-11e8-9d39-ae6e80610766.png)

**Comment by Sibiraj-S** [comment]
That is due to the `border`. I will patch that soon.

**Comment by FolkertCode** [comment]
Great, thanks in advance!
