### ISSUE TITLE
[Bug]: Editor not compatible with rendered HTML

### ISSUE THREAD

**Issue by roip890** [sibiraj-s/ngx-editor#430]
### What happened?

I found 2 examples that the text inside the editor is not compatible with the rendered HTML.

1. There is no option to make multiple whitespaces. It got trimmed in the rendered HTML.
2. When I make a new break line (press Enter) it creates a <p></p>. On the rendered HTML I don't see those new lines.

### Version

v13.0.0

### Angular Version

v13.2.4

**Comment by sibiraj-s** [comment]
I believe it's the prosmirror's behaviour. the editor itself does not generate or transform HTML.
