### ISSUE TITLE
[Bug]: ngx-Editor text and text field hidden

### ISSUE THREAD

**Issue by madhavanSPR** [sibiraj-s/ngx-editor#434]
### What happened?

when adding multiple ngx-editor on same page,

( 1 ) when I have one editor on top and typed something then add another editor on the same page, previous typed value automatically gone.

( 2 ) placing multiple editors column wise on the same page text field ( editor menu and editor ) only showing on last editor, other only have ( editor menu )

### Version

v13

### Angular Version

v13.1.3

### What browsers are you seeing the problem on?

Chrome

**Comment by sibiraj-s** [comment]
Make sure you are creating new `Editor` instance for each editor. If you use the same editor instance for all components. Only the last item will be rendered.

**Comment by madhavanSPR** [comment]
It Works , Thanks for the Valuable Comment 👏

**Comment by madhavanSPR** [comment]
I created different instance for each editor but not working

**Comment by sibiraj-s** [comment]
Sorry for the delay in response. Please share a reproducible stackblitz to help debug this better.

**Comment by sibiraj-s** [comment]
Please reopen the issue with a reproducible example if the issue still exists
