### ISSUE TITLE
[Bug]: Can not set toolbar of ngx-editor-floating-menu

### ISSUE THREAD

**Issue by HybridFox** [sibiraj-s/ngx-editor#438]
### What happened?

Cannot set toolbar of `ngx-editor-floating-menu`.
Changing `[toolbar]` on the `ngx-editor-floating-menu` component has no effect

### Version

v15.0.1

### Angular Version

v14.2.4

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

**Comment by sibiraj-s** [comment]
Floating menu does not have option to customize toolbar. May be you can use https://sibiraj-s.github.io/ngx-editor/en/examples/floating-menu/#floating-menu-with-custom-content. You can add whatever you need.
