### ISSUE TITLE
Using Multiple editor on same page Placeholder text issue

### ISSUE THREAD

**Issue by pkprasad25** [Sibiraj-S/ngx-editor#44]
When using multiple editors on same page, setting placeholder text for last editor update same text for other editor also

**Comment by Sibiraj-S** [comment]
@pkprasad25 That is not possible. Each editor is an individual component. and one cannot inherit the property of other. Can you post a demo in [stackblitz](https://stackblitz.com/) with the issue?

**Comment by pkprasad25** [comment]
Hi Sibiraj Thanks for your quick response
please find the sample code here https://stackblitz.com/edit/angular-8jqvla?file=app%2Fapp.component.html

**Comment by Sibiraj-S** [comment]
Found the bug. I will patch by tomorrow.

**Comment by pkprasad25** [comment]
Hi Sibiraj,
Is it resolved ?

**Comment by Sibiraj-S** [comment]
Kind of busy. Sorry.

**Comment by pkprasad25** [comment]
After updating the version Im getting the following issue

ERROR in ./node_modules/ngx-editor/esm5/ngx-editor.js
Module not found: Error: Can't resolve 'codemirror' in '/home/prasad/project/elt-www/code/elt-client/node_modules/ngx-editor/esm5'
resolve 'codemirror' in '/home/prasad/project/elt-www/code/elt-client/node_modules/ngx-editor/esm5'
  Parsed request is a module
  using description file: /home/prasad/project/elt-www/code/elt-client/node_modules/ngx-editor/package.json (relative path: ./esm5)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /home/prasad/project/elt-www/code/elt-client/node_modules/ngx-editor/package.json (relative path: ./esm5)
    resolve as module
      /home/prasad/project/elt-www/code/elt-client/node_modules/ngx-editor/esm5/node_modules doesn't exist or isnot a directory
      /home/prasad/project/elt-www/code/elt-client/node_modules/ngx-editor/node_modules doesn't exist or is not a directory
      /home/prasad/project/elt-www/code/elt-client/node_modules/node_modules doesn't exist or is not a directory
      /home/prasad/project/elt-www/code/node_modules doesn't exist or is not a directory
      /home/prasad/project/elt-www/node_modules doesn't exist or is not a directory
      /home/prasad/project/node_modules doesn't exist or is not a directory
      /home/prasad/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/prasad/project/elt-www/code/elt-client/node_modules
        using description file: /home/prasad/project/elt-www/code/elt-client/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /home/prasad/project/elt-www/code/elt-client/package.json (relative path: ./node_modules)
          using description file: /home/prasad/project/elt-www/code/elt-client/package.json (relative path: ./node_modules/codemirror)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/prasad/project/elt-www/code/elt-client/node_modules/codemirror doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/prasad/project/elt-www/code/elt-client/node_modules/codemirror.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/prasad/project/elt-www/code/elt-client/node_modules/codemirror.js doesn't exist
            as directory
              /home/prasad/project/elt-www/code/elt-client/node_modules/codemirror doesn't exist
      looking for modules in /home/prasad/project/elt-www/code/elt-client/node_modules
        using description file: /home/prasad/project/elt-www/code/elt-client/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /home/prasad/project/elt-www/code/elt-client/package.json (relative path: ./node_modules)
          using description file: /home/prasad/project/elt-www/code/elt-client/package.json (relative path: ./node_modules/codemirror)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/prasad/project/elt-www/code/elt-client/node_modules/codemirror doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/prasad/project/elt-www/code/elt-client/node_modules/codemirror.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/prasad/project/elt-www/code/elt-client/node_modules/codemirror.js doesn't exist
            as directory
              /home/prasad/project/elt-www/code/elt-client/node_modules/codemirror doesn't exist
      looking for modules in /home/prasad/project/elt-www/code/elt-client/src
        using description file: /home/prasad/project/elt-www/code/elt-client/package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /home/prasad/project/elt-www/code/elt-client/package.json (relative path: ./src)
          using description file: /home/prasad/project/elt-www/code/elt-client/package.json (relative path: ./src/codemirror)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/prasad/project/elt-www/code/elt-client/src/codemirror doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/prasad/project/elt-www/code/elt-client/src/codemirror.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/prasad/project/elt-www/code/elt-client/src/codemirror.js doesn't exist
            as directory
              /home/prasad/project/elt-www/code/elt-client/src/codemirror doesn't exist
      looking for modules in /home/prasad/project/elt-www/code/elt-client/src
        using description file: /home/prasad/project/elt-www/code/elt-client/package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /home/prasad/project/elt-www/code/elt-client/package.json (relative path: ./src)
          using description file: /home/prasad/project/elt-www/code/elt-client/package.json (relative path: ./src/codemirror)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/prasad/project/elt-www/code/elt-client/src/codemirror doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /home/prasad/project/elt-www/code/elt-client/src/codemirror.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/prasad/project/elt-www/code/elt-client/src/codemirror.js doesn't exist
            as directory

**Comment by Sibiraj-S** [comment]
have you installed code-mirror?
