### ISSUE TITLE
[Bug]: Dropdown off the edge.

### ISSUE THREAD

**Issue by Chanachai-Pansailom** [sibiraj-s/ngx-editor#449]
### What happened?

When a menu with a dropdown is on the left or right edge and then pressed, the dropdown goes out of the box.

### Version

13.0.0

### Angular Version

14.2.7

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Relevant log output

```shell
ngx-editor
```

### Willing to submit a PR?

Yes

**Comment by sibiraj-s** [comment]
Thanks for willing to submit PR 👍

**Comment by Chanachai-Pansailom** [comment]
lib edit tool custom mat-menu > div (click)="$event.stopPropagation()"

**Comment by Chanachai-Pansailom** [comment]
or calculate which side to be on

**Comment by sibiraj-s** [comment]
Hi. Closing this for now. Feel free to reopen with a PR.

Thanks
