### ISSUE TITLE
Cannot bind existing content to the editor

### ISSUE THREAD

**Issue by julpane** [Sibiraj-S/ngx-editor#45]
Hi, i have implemented release version      "ngx-editor": "3.3.0-rc.2" and  "codemirror": "5.33.0" with successfully code mirror plugin.

But, if i want edit my content, the editor cannot binding with the existing content from ngModel.

thanks for your helps.

**Comment by kakRostropovich** [comment]
I have the same problem

**Comment by Sibiraj-S** [comment]
Is your problem replicated here too https://ngx-editor.stackblitz.io/
Edit here: https://stackblitz.com/edit/ngx-editor

**Comment by julpane** [comment]
![image](https://user-images.githubusercontent.com/26126973/35612376-2eac0de6-069b-11e8-947e-6777d47be7bd.png)

I have initial htmlContent but editor still blank.
