### ISSUE TITLE
[Feature request]: Support multiple languages

### ISSUE THREAD

**Issue by rogerg93** [sibiraj-s/ngx-editor#451]
### Proposal

In the docs it says that if you want to use a different text for buttons in the editor you can configure it like this:

`NgxEditorModule.forRoot({
  locals: {
    bold: 'Bold',
    italic: 'Italic',
    code: 'Code',
    underline: 'Underline',
    // ...
  },
});`

But what about if I want to support multiple languages and have a language switch in my app?

### Willing to submit a PR?

None

**Comment by sibiraj-s** [comment]
Sorry for the delay in response. I missed this issue

Can you see if this helps https://github.com/sibiraj-s/ngx-editor/issues/354#issuecomment-878009003?

**Comment by doug0102** [comment]
You can find an example [here](https://github.com/sibiraj-s/ngx-editor/pull/398) using ngx-translate. 

The problem I am having now is it doesn't seem to update without doing a hard refresh.

**Comment by sibiraj-s** [comment]
Fixed in https://github.com/sibiraj-s/ngx-editor/pull/466.
