### ISSUE TITLE
[Bug]: XSS Vulnerability

### ISSUE THREAD

**Issue by orb77** [sibiraj-s/ngx-editor#459]
### What happened?

If you provide the editor with `img` and the tag contains `onerror`  attribute it executes JavaScript when the `src` attribute is invalid.
Sample `img` input:
``<img src="notfound" onerror="alert('Vulnerable!')" />``

### Version

15.3.0

### Angular Version

15.1.0

### What browsers are you seeing the problem on?

Chrome

### Link to reproduce

[stackblitz](https://stackblitz.com/edit/angular-pv6xss?file=src/main.ts)

### Willing to submit a PR?

None

**Comment by sibiraj-s** [comment]
Hi, Sorry for the delay in response.

The editor itself neither allows pasting javascript directly to be executed nor sanitizes the input, it is the responsibility of the developer to sanitize the input before providing it to the editor. 

Or Maybe you could write a pluing to sanitize html before the editor renders it. I am sure that there should be a prosemirror handle to preprocess html before inseted.

Let me know if you have more questions.
