### ISSUE TITLE
Code editor mode is not visible

### ISSUE THREAD

**Issue by Maden-maxi** [Sibiraj-S/ngx-editor#46]
By default all buttons are visible but in my case code editor mode not visible only.
`
<app-ngx-editor  [formControlName]="'description"></app-ngx-editor>
`
![image](https://user-images.githubusercontent.com/17612707/35684923-f9b06ba6-0770-11e8-9dc3-fbd70828a7bd.png)
 
![image](https://user-images.githubusercontent.com/17612707/35685352-259ac666-0772-11e8-8d1b-2decd2b6e94d.png)

Why code editor button is not visible?

**Comment by Sibiraj-S** [comment]
code editors are available in v>3.3.0-rc.2. What is the version you are using?

**Comment by Sibiraj-S** [comment]
@Maden-maxi. Issue will be closed in two days in-case of no response. You can reopen at anytime you want.

😸
