### ISSUE TITLE
[Feature request]: upload image from local system

### ISSUE THREAD

**Issue by A7OMICsp** [sibiraj-s/ngx-editor#472]
### Proposal

I would like to insert an image from my local system storage instead of placing an image url. I've readed that this feature was done a few years ago but I cant find it now.

**Comment by sibiraj-s** [comment]
hi. thanks for opening this. Uploading feature of image was done on a different version of editor several years back and that editor become really unreliable. so during a rewrite with prosemirror some of functions are not implemented as they are easy to extend with prosemirror plugins.

For example you could follow this https://prosemirror.net/examples/upload/ and implement the feature.

Closing the issue for now as this is not planned for now. Happy to accept a PR though.

Thank you.
