### ISSUE TITLE
[Bug]: Custom Toolbar Problem

### ISSUE THREAD

**Issue by ronnybaba** [sibiraj-s/ngx-editor#473]
### What happened?

i am trying to implement some custom toolbar in this and following the described process in documentation 
https://ngx-editor-codemirror.stackblitz.io/

here you have implemented the coremirror funcnality which is not working on this stalkblitz can you please provide me a solution or working demo so that i can implement more features according to my need 

thanks in advance

### Version

v14.0x

### Angular Version

v14.0x

### What browsers are you seeing the problem on?

Chrome

### Willing to submit a PR?

None

**Comment by ronnybaba** [comment]
can anyone please respond to this ?

**Comment by sibiraj-s** [comment]
Yeah its broken for some reason. Will check and update this weekend.

Meanwhile you can try running the project locally, it was working fine last time i checked.

See here for how to run locally https://github.com/sibiraj-s/ngx-editor/blob/master/.github/CONTRIBUTING.md

**Comment by ronnybaba** [comment]
i checked your project locally and its running fine on local but when i try to diagnose the issue by checking the ngx-editor version installed in your local project then i am unable to find it.

can you please help me with the version or if possible please resolve it

**Comment by sibiraj-s** [comment]
The setup is now fixed [ngx-editor-codemirror.stackblitz.io](https://ngx-editor-codemirror.stackblitz.io/)
