### ISSUE TITLE
[Bug]: Ordered List and Unordered List does not show numbering or bullet points.

### ISSUE THREAD

**Issue by fitterfly-jainam** [sibiraj-s/ngx-editor#485]
### What happened?

I have integrated Ngx Editor and it seems that the ordered list and unordered list does not show up. 
When I was debugging, I found that the "start" attribute of "ol" element returns NaN and due to that the problem occurs mostly. Can you please check on it?
![Screenshot 2023-07-17 at 10 50 06 AM](https://github.com/sibiraj-s/ngx-editor/assets/124351088/580a53a4-dd85-49e4-a339-4cfa2b6c5d42)

### Version

v15.3.0

### Angular Version

v14.3.0

### What browsers are you seeing the problem on?

Chrome

### Willing to submit a PR?

None

**Comment by sibiraj-s** [comment]
The editor doesn't add start attribute.

You can find a working example here https://[ngx-editor.stackblitz.io](https://ngx-editor.stackblitz.io/)/

**Comment by fitterfly-jainam** [comment]
<img width="977" alt="Screenshot 2023-07-17 at 9 31 17 PM" src="https://github.com/sibiraj-s/ngx-editor/assets/124351088/7014dd86-83bf-46a6-bf7b-50eac091f6f2">

For some reason, I'm getting bullet points and numbered list like this. I don't know what is the issue here. Can you help @sibiraj-s

**Comment by fitterfly-jainam** [comment]
Hi @sibiraj-s, I found the issue. The padding from the left side was not proper due to which it was unable to show the list numbers and bullet points. I increased the left and right padding and it shows now. Thanks anyways!

**Comment by sibiraj-s** [comment]
Glad you figured it 🎉
