### ISSUE TITLE
[Bug]: ngx-editor hangs and crashes in Chrome when inserting external image links, but works in Firefox

### ISSUE THREAD

**Issue by timemachi** [sibiraj-s/ngx-editor#488]
### What happened?

When using ngx-editor in Chrome to insert external image links, the editor experiences hangs and subsequently crashes. Interestingly, this issue is specific to Chrome under regular browsing mode, as the editor functions correctly in Firefox. Upon further testing, it was observed that when Chrome is switched to incognito (privacy) mode, ngx-editor operates without any hitches or crashes when inserting the same external image links. This suggests that the issue might be influenced by certain browser configurations, extensions, or cached data present in normal mode but not in incognito mode.

### Version

v15.3.0

### Angular Version

v15.2.0

### What browsers are you seeing the problem on?

Chrome

### Willing to submit a PR?

None

**Comment by timemachi** [comment]
Sorry i found the problem, My Chrome browser was exhibiting abnormal behavior due to an extension. Once I disabled the extension, everything returned to normal.

**Comment by sibiraj-s** [comment]
Hi. thanks for update. Sorry I saw the issue on a weekend and forgot to reply once I came back. 

Glad the issue is fixed now
