### ISSUE TITLE
[Bug]: Input rules do not apply styles correctly. Some marker characters are not replaced 

### ISSUE THREAD

**Issue by raphael-inglin-ergon** [sibiraj-s/ngx-editor#490]
### What happened?

When using markdown syntax to e.g. write bold text by typing `**bold text**` it will be replaced to show **\*\*bold text\*** instead of **bold text**. Same applies to italics. This can be easily reproduced in the demo application: https://ngx-editor.stackblitz.io/.

#### Potential Cause & Solution

After a quick look at the code, I think the issue comes from the regex patterns in `defaultPlugins.ts` combined with the application of those rules in `markInputRule.ts`. All groups in the regex patterns are non-capturing, so the `if(match[2])` branch is never executed and the wrong range is being replaced. It could probably be fixed by using capturing groups at the right place or using named groups.

### Version

15.3.0

### Angular Version

16.1.0

### Link to reproduce

https://ngx-editor.stackblitz.io/

### Willing to submit a PR?

Yes

**Comment by sibiraj-s** [comment]
Thanks for report. Please raise a PR, I will try to merge it soon.
