### ISSUE TITLE
[Bug]: broken link to documentation page

### ISSUE THREAD

**Issue by asgerrud** [sibiraj-s/ngx-editor#492]
### What happened?

Clicking the **docs** link on the website leads to a 404 page. The url should be changed from `/en/introduction` to `/ngx-editor/en/introduction/`

![image](https://github.com/sibiraj-s/ngx-editor/assets/36601572/fdca00c3-0fa9-449f-9569-011f655ebfaf)

### Version

15.3.0

### Angular Version

16.1.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Link to reproduce

https://sibiraj-s.github.io/ngx-editor/

### Willing to submit a PR?

Yes

**Comment by sibiraj-s** [comment]
Thanks for reporting. Feel free to raise a PR ❤️
