### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by aburg15** [sibiraj-s/ngx-editor#495]
### What happened?

The stackblitz url listed in the README currently displays the following error upon load:

Error in /turbo_modules/ngx-editor@14.2.0/fesm2015/ngx-editor.mjs (11:17)
Unexpected token 'export'

### Version

n/a

### Angular Version

n/a

### What browsers are you seeing the problem on?

Chrome

### Link to reproduce

https://stackblitz.com/edit/ngx-editor?file=src%2Fapp%2Fapp.component.ts

### Willing to submit a PR?

None

**Comment by sibiraj-s** [comment]
HI @aburg15 . Thanks for reporting this. Should be fixed now
