### ISSUE TITLE
[Feature request]: allow passing preserveWhiteSpace to ProseMirror

### ISSUE THREAD

**Issue by ansemjo** [sibiraj-s/ngx-editor#496]
### Proposal

I think this is similar to #430. Even if you insert a `<code>` block, insert multiple spaces inside that block and then later re-parse the exported HTML with an `ngx-editor` (I'm using the "Reactive Forms" style, if that makes any difference), the spaces get trimmed down.

The need for retaining spaces is also [discussed on the ProseMirror forum](https://discuss.prosemirror.net/t/retaining-spaces/227/3), with the apparent solution being that you could pass `{ preserveWhiteSpace: true }` to PM. So yes, while the "editor itself does not [...] transform HTML", maybe it could help by passing this as an optional flag to ProseMirror?

(Or is there a way to configure this via `attributes` or something and I just haven't figured it out yet? 😬)

### Willing to submit a PR?

None

---

I see that `preserveWhitespace` is used on the [documentation page on Schema](https://sibiraj-s.github.io/ngx-editor/en/schema/), but I'm not sure how to use / apply this to the entirety of the HTML that is passed to the editor?

**Edit:** Overriding the default paragraph schema like this works for my use-case, too. I'm ignoring the `align` style here because I am manually aligning text with a monospace font anyway.

```typescript
import { DOMOutputSpec, NodeSpec, Schema } from "prosemirror-model";
import { nodes as basicNodes, marks } from "ngx-editor";

// extend the prosemirror schema to always preserveWhitespace
const preserve: NodeSpec = {
  content: "inline*",
  group: "block",
  parseDOM: [{
    tag: "p",
    preserveWhitespace: "full",
  }],
  toDOM(): DOMOutputSpec {
    return ["p", { }, 0];
  },
};

const nodes = Object.assign({}, basicNodes, {
  "paragraph": preserve,
});

const schema = new Schema({ nodes, marks });

// then use this when instantiating editor:
this.editor = new Editor({
  schema: schema,
  // ...
});
```

**Comment by ansemjo** [comment]
So, I figured out how to use a schema for my use-case (see the edit in the first comment above). I'm not sure how well that works for any nested nodes but so far it seems to work fine.

I'll leave the issue open for you to decide whether the API addition of `ParseOptions` makes sense ..

**Comment by sibiraj-s** [comment]
HI. Thanks for creating the issue. Will look into this tomorrow.

**Comment by lpepen-re** [comment]
I've been running into the same issue. Since this issue is still open i assume it has yet to be implemented. Looking forward to this feature (or something similar that will allow the users to preserve white spaces when parsing from html to json with toDoc()

**Comment by sibiraj-s** [comment]
Added in v17.1.0
