### ISSUE TITLE
[Bug]: Some formatting functions will result in CSP exceptions

### ISSUE THREAD

**Issue by gs-scooter** [sibiraj-s/ngx-editor#504]
### What happened?

When using the editor within an Angular component, a content security policy exception is thrown in the browser if any of these functions are chosen in the editor:

- Text alignment
- Colors
- Ordered / unordered list

The issue is that attempting any of these functions will try to add a style attribute to a DOM element. The CSP exception will then break functionality.

### Version

v16.0.1

### Angular Version

v16.2.2

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-XXXXXXXXX' fonts.googleapis.com cdnjs.cloudflare.com". Either the 'unsafe-inline' keyword, a hash ('sha256-C8oNnV7QJNwOdkv12C9sTrLv3O9tgEE8jtcA5AQhZ+0='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
```

### Willing to submit a PR?

No

**Comment by sibiraj-s** [comment]
Sorry for the delayed reply. 

Some styles are in-lined by prosemirror. I guess unsafe inline has to allowed and there are no workarounds for this.
