### ISSUE TITLE
[Feature request]: Any chance of indent making a comeback?  

### ISSUE THREAD

**Issue by bstaley** [sibiraj-s/ngx-editor#508]
### Proposal

Hello, was hoping to be able to use indent with the latest version. I see in #394 you were able to add HR back in. Any hope for indent?

### Willing to submit a PR?

None

**Comment by sibiraj-s** [comment]
Can add indent and outdent. I'll spend sometime this weekend.

**Comment by sibiraj-s** [comment]
Sorry for the delay, This is now available in v17.2.0. indent, outdent is not enabled by default, you can add them manually to toolbar configuration to enable them

See here https://sibiraj-s.github.io/ngx-editor/menu
