### ISSUE TITLE
[Bug]: Mentions & Tags Demo Issue  Schema is missing its top node type ('doc')

### ISSUE THREAD

**Issue by gorkemyontem** [sibiraj-s/ngx-editor#512]
### What happened?

When attempting to use the Mentions & Tags demo in ngx-editor, I encountered an "Uncaught RangeError: Schema is missing its top node type ('doc')" error. This issue is reproducible not only in my local environment but also on the documentation website where the demo is showcased.

### Version

v16.0.1

### Angular Version

v17.0.1

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Uncaught RangeError: Schema is missing its top node type ('doc')
    at Function.compile (index.cjs:1814:35)
    at new Schema (index.cjs:1893:133)
    at 391 (schema.ts:6:16)
    at __webpack_require__ (bootstrap:19:1)
    at 36777 (changelog-new.component.ts:18:1)
    at __webpack_require__ (bootstrap:19:1)
    at 71922 (changelog.routes.ts:5:1)
    at __webpack_require__ (bootstrap:19:1)
    at 10611 (app.config.ts:17:1)
    at __webpack_require__ (bootstrap:19:1)
```

### Willing to submit a PR?

None

**Comment by sibiraj-s** [comment]
please share a reproducible example.  you can see a working demo here https://sibiraj-s.github.io/ngx-editor/examples/mentions/

**Comment by gorkemyontem** [comment]
Hi there, I have decided not to use this project. You may close this issue if you want. 
But I have to tell you, the demo that you have shared is not working. I cannot see a working demo. I'm sorry. 

![image](https://github.com/sibiraj-s/ngx-editor/assets/8965495/782492ec-0486-402e-a188-b39b67f3a4e9)

**Comment by sibiraj-s** [comment]
Cool. I'll verify later why the example doesn't work.

**Comment by sibiraj-s** [comment]
Seems something wrong with the compiler in stackblitz. Worked after reloading once or twice. (with no code changes)

<img width="751" alt="Screenshot 2024-01-21 at 7 50 38 PM" src="https://github.com/sibiraj-s/ngx-editor/assets/20282546/852aef57-5df9-48e7-822d-fb16b43d564d">
