### ISSUE TITLE
[Bug]: Unexpected token ':'

### ISSUE THREAD

**Issue by dilbarov** [sibiraj-s/ngx-editor#520]
### What happened?

When I use the module in SSR, I get a SyntaxError: Unexpected token ':' error

### Version

v16.0.1

### Angular Version

v17.1.1

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
[vite] Error when evaluating SSR module /main.server.mjs:
|- SyntaxError: Unexpected token ':'
    at new AsyncFunction (<anonymous>)
    at instantiateModule (file:///some-project/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50858:28)
```

### Willing to submit a PR?

None

**Comment by sibiraj-s** [comment]
SSR is not supported as the editor heavily relies on client side api's to work.

**Comment by dilbarov** [comment]
> SSR is not supported as the editor heavily relies on client side api's to work.

This worked fine in version 15

**Comment by dilbarov** [comment]
The problem is in the build with vite in dev mode. There is an error with the prose mirror library.Because [this ](https://github.com/ProseMirror/prosemirror-transform/blob/ef881296c2d548772eca19fee511db631354b56d/src/replace.ts#L247) construct does not work in strict mode.

Issue can be closed

**Comment by sibiraj-s** [comment]
Thanks for figuring this out.
