### ISSUE TITLE
[Bug]: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by alexpivtorak** [sibiraj-s/ngx-editor#527]
### What happened?

There's a problem with Jest. Testing a standalone component which uses 'ngx-editor' falls with an error:
"Cannot use import statement outside a module"

### Version

v17.0.1

### Angular Version

v17.1.3

### Relevant log output

```shell
node_modules\ngx-editor\node_modules\nanoid\index.browser.js:1        
    ({"Object.<anonymous>":function(module,exports,require,__dirna 
me,__filename,jest){import { urlAlphabet } from './url-alphabet/index.js' 
                                                                   
                    ^^^^^^ 
 
    SyntaxError: Cannot use import statement outside a module      
 
      20 | import { filter, Subject } from "rxjs"; 
      21 | 
    > 22 | import * as NgxEditor from "ngx-editor";
```

### Willing to submit a PR?

No

**Comment by sibiraj-s** [comment]
Hi, it seems the issue is related to a configuration issue in package.json. You may need to add type:module in package.json. The package is built with ng-packager with no configuration changes to their defaults.

**Comment by PhilKoepfer** [comment]
type:module in package.json not worked for us

We need to add (but it slowed our tests down):
```
  transformIgnorePatterns: [
    'node_modules/ngx-editor/node_modules/nanoid/index.js',
  ],
```

**Comment by sibiraj-s** [comment]
Oh. I can remove the nanoid package. it just provides a very minor functionality.

**Comment by kiwidude68** [comment]
Also getting a bunch of similar errors here, all blame seemingly being pointed to that nanoid component. Any chance a 17.0.2 can be pushed out with that removed soonish? I can't get the transformIgnorePatterns to work as a workaround - it is still failing the test suites.
```
 D:\Git\my-project\node_modules\ngx-editor\node_modules\nanoid\index.js:1
  ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { webcrypto as crypto } from 'node:crypto'
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

**Comment by sibiraj-s** [comment]
Removed nanoid in v17.0.2
