### ISSUE TITLE
Cannot find module 'ngx-bootstrap'.

### ISSUE THREAD

**Issue by ericel** [Sibiraj-S/ngx-editor#53]
`ERROR in node_modules/ngx-editor/app/ngx-editor/ngx-editor-toolbar/ngx-editor-toolbar.component.d.ts(3,31): error TS2307: Cannot find module 'ngx-bootstrap'.`

**Comment by Sibiraj-S** [comment]
Have You installed ngx-bootstrap as peerDependency? I am working on it. Comment back if that works.

**Comment by ericel** [comment]
Yeah , I would not. But wouldn't it be nice if someone didn't to be forced to use ng-bootstrap?

**Comment by ericel** [comment]
```
ERROR in ./node_modules/ngx-editor/esm5/ngx-editor.js
Module not found: Error: Can't resolve 'codemirror' in 'D:\websites\otcollect\node_modules\ngx-editor\esm5'
ERROR in ./node_modules/ngx-editor/esm5/ngx-editor.js
Module not found: Error: Can't resolve 'codemirror/mode/xml/xml.js' in 'D:\websites\otcollect\node_modules\ngx-editor\esm5'
```

**Comment by Sibiraj-S** [comment]
Okay. Thanks. I guess I found the bug.

**Comment by Sibiraj-S** [comment]
>Yeah , I would now. But wouldn't it be nice if someone didn't have to be forced to use ng-bootstrap?

you don't have to include anything. Just Install the dependency. Try that.
