### ISSUE TITLE
[Feature request]: Menu Keyboard Accessibility

### ISSUE THREAD

**Issue by davideblakeman** [sibiraj-s/ngx-editor#531]
### Proposal

I request keyboard accessibility for the menu so I can skip having to create my own custom menu bar and avoid the technical debt of having to replace a custom menu bar if this is implemented in future. Just adding `tabindex="0"` to all the `ngx-toggle-command` and other buttons would suffice. But to be WCAG compliant also adding `aria-label` and `role="button"` descriptions for screen readers would also be desirable.

### Willing to submit a PR?

Yes if my assistance is requested and when I find time.

**Comment by sibiraj-s** [comment]
Fixed in v17.1.0, the items are now button and added roles, aria-label, etc wherever applicable.
