### ISSUE TITLE
[Feature request]: Custom color

### ISSUE THREAD

**Issue by willdochnur** [sibiraj-s/ngx-editor#533]
### Proposal

I would like to be able to set my own custom color. It does not need to a color picker. Just a simple input field to set hex or rgba color code would do the trick.

### Willing to submit a PR?

None

**Comment by sibiraj-s** [comment]
Hi, Sorry for the delay in response. You can easily create that with a custom menu item, you can use the input of your choice

See: https://sibiraj-s.github.io/ngx-editor/menu/#custom-menu. Once the custom menu is created you can use the following commands to set the color

```ts
textColor(<color_value>)
backgroundColor(<color_value>)
```

See here on how to run commands https://sibiraj-s.github.io/ngx-editor/commands/.
