### ISSUE TITLE
[Bug]: Removing a link from a text with decoration like a bold font, removes all text decoration

### ISSUE THREAD

**Issue by Ade-mir** [sibiraj-s/ngx-editor#535]
### What happened?

**How to reproduce:**
- Add a text.
- Add a link to the text.
- Add any or all of the text decoration like bold, italic, underline, etc, to the linked text.
- Remove the link.

**Expected result:**
The link is removed, but the text decoration/s remain.

**Actual result:**
The link is removed, but all the text decoration is as well.

This is true regardless of if the link is added to the text before or after the text decoration.

### Version

v17.0.1

### Angular Version

v17.1.1

### What browsers are you seeing the problem on?

Chrome

### Link to reproduce

https://ngx-editor.stackblitz.io/

### Willing to submit a PR?

None

**Comment by sibiraj-s** [comment]
Fixed in v17.1.0
