### ISSUE TITLE
[Bug]: Button "Remove" in Text-Color and Background-Color not working

### ISSUE THREAD

**Issue by DywiTom** [sibiraj-s/ngx-editor#545]
### What happened?

Hello!

Button "Remove" is not working. Also deselecting of Alignment.
See gif. Thanks!

![not working =(](https://github.com/sibiraj-s/ngx-editor/assets/87300270/424923bc-33a8-432c-8e55-db42884626e4)

### Version

v17.5.1

### Angular Version

v17

### What browsers are you seeing the problem on?

Chrome

### Willing to submit a PR?

None

**Comment by sibiraj-s** [comment]
Should be fixed in v17.5.3
