### ISSUE TITLE
[Bug]: Wrong `<input>` type for `url`

### ISSUE THREAD

**Issue by Lapotor** [sibiraj-s/ngx-editor#550]
### What happened?

On popups where you have a URL field the `<input>` type is set to `type="href"` this is not a valid [`<input>` type](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#input_types).

It should be `type="url"` to match valid valid `<input>` type.

https://github.com/sibiraj-s/ngx-editor/blob/3741a9ebd10e4ab004d22ac02c6206fb8f68a85a/projects/ngx-editor/src/lib/modules/menu/link/link.component.html#L23

https://github.com/sibiraj-s/ngx-editor/blob/3741a9ebd10e4ab004d22ac02c6206fb8f68a85a/projects/ngx-editor/src/lib/modules/menu/image/image.component.html#L23

### Version

v17.5.4

### Angular Version

v17.3.9

### What browsers are you seeing the problem on?

Firefox

### Willing to submit a PR?

Yes

**Comment by Lapotor** [comment]
There for this rule don't apply to the URL fields:

https://github.com/sibiraj-s/ngx-editor/blob/3741a9ebd10e4ab004d22ac02c6206fb8f68a85a/projects/ngx-editor/src/lib/editor.component.scss#L326-L329

**Comment by sibiraj-s** [comment]
Thanks for catching this, Please raise a PR. will get that deployed soon.
