### ISSUE TITLE
HTML content is not rendering properly in editor.

### ISSUE THREAD

**Issue by SaurabhaArya** [sibiraj-s/ngx-editor#551]
### What happened?

I am on Angular v15 and trying to implement `ngx-editor v15.3.0`. 

When I try to render the HTML content, it does not comes in proper HTML format in the editor. 

For example, `<table>` tag is ignored and all the content is put inside the `<p>` tag. 

Here's the stackblitz [link](https://stackblitz.com/edit/angular-15-starter-pack-srzsdb?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html).

Desired output:
<img width="655" alt="image" src="https://github.com/sibiraj-s/ngx-editor/assets/16134421/0fad8959-a1ea-43e2-a650-268aa751a1ca">

Actual Output: 
<img width="817" alt="image" src="https://github.com/sibiraj-s/ngx-editor/assets/16134421/f9b0f842-8aad-44e5-91d4-5cb0617117ca">

Kindly assist.
Thanks.

### Version

v15.3.0

### Angular Version

v15.2.10

### What browsers are you seeing the problem on?

Chrome

### Link to reproduce

https://stackblitz.com/edit/angular-15-starter-pack-srzsdb?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

### Willing to submit a PR?

None

**Comment by sibiraj-s** [comment]
Hi @SaurabhaArya , Tables aren't supported.

**Comment by SaurabhaArya** [comment]
Okay. Thanks for your response.
