### ISSUE TITLE
[Feature request]: Reset both text and background color in editor-menu to default color

### ISSUE THREAD

**Issue by lucasluizss** [sibiraj-s/ngx-editor#562]
### Description

When using the ngx-editor library in an Angular application, the editor menu does not provide an option to reset the text color and background color to their default values. This limitation prevents users from reverting customized color settings back to the standard theme colors, which can affect the consistency and readability of the content. As a result, once a color is applied to the text or background, there is no straightforward way to remove it using the editor's built-in menu options.

### Problem Statement/Justification

In our Angular application utilizing the ngx-editor library, we have identified a significant limitation: the editor menu lacks functionality to reset the text and background colors to their default values. This deficiency hampers user experience by preventing them from easily reverting customized color settings back to the standard theme colors.

### Additional Information

Implementing this feature would improve overall user satisfaction, streamline content creation processes, and bring ngx-editor in line with user expectations for a modern text editor.
The color only resets when a new line is added or everything is deleted from the text editor.

### Willing to submit a PR?

No

**Comment by sibiraj-s** [comment]
I assumed that you found that its possible already? You just need to select the color and rest.

**Comment by sibiraj-s** [comment]
I assume that you have found that it already exists. You just need to select the color and reset from the same color picker

**Comment by lucasluizss** [comment]
> I assume that you have found that it already exists. You just need to select the color and reset from the same color picker

Exactly. Since we use a different style for that I was unable to see the button until I saw the demo.
