### ISSUE TITLE
[Bug]: "insert command" button like "Clear formatting" triggers a form submit

### ISSUE THREAD

**Issue by natharduini** [sibiraj-s/ngx-editor#564]
### What happened?

My ngx-editor is in a form and when I click the "Clear formatting" menu button, it triggers a form submission.

Adding `type="button"` in insert-command.component.html prevents that.

### Version

v17.x.x

### Angular Version

v17.x.x

### What browsers are you seeing the problem on?

Firefox, Chrome

### Link to reproduce

https://stackblitz.com/edit/ngx-editor-vanv24

### Willing to submit a PR?

Yes

**Comment by matthiassommer** [comment]
I noticed the same for horizontal_rule and format_clear
