### ISSUE TITLE
[Bug]: Failed to open link

### ISSUE THREAD

**Issue by zoeyz777** [sibiraj-s/ngx-editor#571]
### What happened?

Readme file, the demo link cannot jump
![image](https://github.com/user-attachments/assets/cf19fb56-392f-46d3-a0e1-4de2e448d918)

### Version

v17.5.4

### Angular Version

v17.3

### What browsers are you seeing the problem on?

Chrome

### Link to reproduce

https://github.com/sibiraj-s/ngx-editor/blob/master/README.md

### Willing to submit a PR?

None

**Comment by sibiraj-s** [comment]
Will fix, Its supposed to land here https://ngx-editor.stackblitz.io/

**Comment by zoeyz777** [comment]
can you assign this to me? I'll fix it later.Thanks

**Comment by sibiraj-s** [comment]
Done.

**Comment by sibiraj-s** [comment]
Closing since this is fixed. Thanks @zoeyz777

**Comment by zoeyz777** [comment]
Thanks so much for your help! @sibiraj-s
