### ISSUE TITLE
[Feature]: Possibility to use another icons font

### ISSUE THREAD

**Issue by iget-master** [Sibiraj-S/ngx-editor#58]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [x] Feature request
- [ ] Documentation issue or request

## Description

My proposal is to add the possibility to use another icon set, for example [material icons](https://material.io/icons/).

My motivation is: I want to implement ngx-editor on a [Material Angular](https://material.angular.io/) based application, but I really don't want to clog my application with another font package if I don't really need it.

I'm willing to help on development of this feature if necessary.

### Version Information

not relevant

### Browser

not relevant

**Comment by Sibiraj-S** [comment]
Nice one. So Material Projects can use that too. Without FA

**Comment by Sibiraj-S** [comment]
Material misses few icons I guess or Did I miss the following
* Ordered List
* Paragraph
* Eraser
* Horizontal line
* Quote
* Unlink

So, this won't be a viable option. 

#### Proposal

Since all components are capable of working individually. Alternatively, What I can do is I can expose the API's for toolbar and Message component. You can disable the default toolbar and design your own and then you can interact with the Editor.

Hope that will work 😕

What do You think?

**Comment by iget-master** [comment]
- Ordered list `<i class="material-icons">format_list_numbered</i>`
- Paragraph ~didn't found~
- Eraser ~didn't found~
- Horizontal line ~didn't found~
- Quote `<i class="material-icons">format_quote</i>`
- Unlink ~didn't found~

Yeah, unfortunately the font misses many icons.

I think that exposing API for toolbar might solve the issue, but is a "reinvent the wheel" job...

Maybe we can solve it by embedding a fork of font-awesome (or any other) containing only necessary icons, so we:

1. Avoid needing of import font-awesome on entire project
2. Make the component lighter since it will load a smaller font.

I'm not sure if it's possible to embed fonts on angular components, but I think so!

**Comment by Sibiraj-S** [comment]
>  but is a "reinvent the wheel" job...

I won` t be I guess. It is already there. I just have to export the component (I guess). Let me try that.

Also, I won't be able to work on this for long. I mat not be able to find time, since we are planning of a new project.

**Comment by iget-master** [comment]
Alright, thanks!

**Comment by Sibiraj-S** [comment]
@iget-master . What about using SVG's https://www.flaticon.com/packs/font-awesome

**Comment by iget-master** [comment]
My only care is about overhead. Loading an entire icon font for using 10~15 icons is overhead.

Even loading 10~15 icons pack is overhead if we already use another icon font, but of course that's better then an entire icon font.

I'll think about some way to solve it...

**Comment by Sibiraj-S** [comment]
@iget-master. If this package https://github.com/FortAwesome/angular-fontawesome gets ready I have no need for font dependency. I may be able to ship icons that are only needed along with this editor.

It is not yet production ready.

**Comment by Sibiraj-S** [comment]
closing this now. I will work on backlogs when I get some time.
