### ISSUE TITLE
[Bug]: ngx-editor with vmw clarity is broken

### ISSUE THREAD

**Issue by gpradeepjain** [sibiraj-s/ngx-editor#581]
### What happened?

Hi Team,

I am using  "../../node_modules/@clr/ui/clr-ui.min.css" in my angular.json

As I have added above, my ngx-editor styling is broken as shown in the image below. Is there a way to prevent this behaviour?

<img width="1235" alt="Screenshot 2024-09-26 at 3 29 09 PM" src="https://github.com/user-attachments/assets/9b0592cd-138b-4a0d-9ec8-34e2f20b3d20">

### Version

17.0.1

### Angular Version

17.1.1

### What browsers are you seeing the problem on?

Chrome

### Willing to submit a PR?

None

**Comment by sibiraj-s** [comment]
the editor doesn't add any styles on how the content looks, its upto you to configure it, the imported `@clr/ui/clr-ui.min.css` might have some styles affecting the default list styles , you might want to override those for the editor

**Comment by sibiraj-s** [comment]
Closing this, since this is not an editor issue. if you still think this should be solved on editor side. Please clarify why. Feel free to continue discussion if needed.
