### ISSUE TITLE
[Enhancement]: Remove ngx-bootstrap dependency

### ISSUE THREAD

**Issue by iget-master** [Sibiraj-S/ngx-editor#59]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [x] Enhancement 
- [ ] Feature request
- [ ] Documentation issue or request

## Description

Not really a feature, but an improvement: This package have a peerDependency of `ngx-bootstrap` when it actually uses only the popover module.

The problem is that this force we to load full bootstrap stylesheet (or build a css only with popover), but loading it on *Material Angular* application will broke some styles.

Since it's a simple feature (show/hide a div with a content), it can be embed on the editor itself.

### Version Information

**ngx-editor**: v3.3.0-rc.6

**Comment by iget-master** [comment]
Nice! Again, I'm willing to help on this project, I really like this kind of projects since there's no alternatives of WYSIWYG for Angular 2+ that are 100% angular native. I hate wrappers for things that wasn't made for Angular 2+ :+1:

**Comment by Sibiraj-S** [comment]
Sure. Contributions are always welcomed. @iget-master

**Comment by Sibiraj-S** [comment]
I am not removing `ngx-bootstrap` since it wont affect any styles. I am removing `bootstrap`. Instead Providing some inline styles within the scope of the editor.

**Comment by Sibiraj-S** [comment]
closed in 8aa0ffd
