### ISSUE TITLE
[Feature]: Option to include Save button in toolbar

### ISSUE THREAD

**Issue by Fabrotich** [Sibiraj-S/ngx-editor#63]
# I'm submitting

- [ ] Bug report
- [x] Feature request
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Documentation issue or request

## Description

Can we have a save button on the editor by default or is there a way to add custom buttons?

### Version Information

```
ngx-editor: 3.2.1
angular: 4.4.6
```

**Comment by Sibiraj-S** [comment]
save what? and Can you explain the motivation of this feature?

**Comment by Fabrotich** [comment]
To save content written into the editor. I'd like the save button to be on the toolbar. The motivation for this is for user initiated saving. Or are there ways for me to trigger saving without having to put a save button below the editor?

**Comment by Sibiraj-S** [comment]
Right Now. There is no such option to add custom button to the toolbar. Instead. There is a proposal I made to another feature. I think that may be useful in your case

> Since all components are capable of working individually. Alternatively, What I can do is I can expose the API's for toolbar and Message component. You can disable the default toolbar and design your own and then you can interact with the Editor.

Discussion here #58

**Comment by Fabrotich** [comment]
Yeah that would be great.

**Comment by Sibiraj-S** [comment]
So closing this issue now. Follow the above thread for details
