### ISSUE TITLE
codemirror won't play well with universal

### ISSUE THREAD

**Issue by ericel** [Sibiraj-S/ngx-editor#64]
@Sibiraj-S  codemirror doesn't  play well with universal. It should be one of those dependencies u choose whether to use or not!

Wouldn't that be nice?

**Comment by Sibiraj-S** [comment]
Follow the issue template. That`s why it is there for. 

Currently I have no idea to replace codemirror and I don`t have enough time to work on that. I will be keeping this in backlog.

😄
