### ISSUE TITLE
[Feature]: Option to set font color

### ISSUE THREAD

**Issue by b3app** [Sibiraj-S/ngx-editor#65]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [x] Feature request**
- [ ] Documentation issue or request

## Description

Hi!

It's possible to add a font color and font size features?
Thank you!

**Comment by Sibiraj-S** [comment]
Hi @b3app. Track the font size feature here #31

**Comment by b3app** [comment]
I am so grateful, @Sibiraj-S ! 
I'm waiting for update.

**Comment by Ishusubash** [comment]
@b3app . It's already on. Follow the PR #66 . I am working on setting font size. That's why the delay.

**Comment by Sibiraj-S** [comment]
@b3app . It's already on. Follow the PR #66 . I am working on setting font size. That's why the delay.

**Comment by Sibiraj-S** [comment]
@b3app. There you go. Update to the latest version for the changes

**Comment by b3app** [comment]
@Sibiraj-S You saved me. Thank you!
