### ISSUE TITLE
[Feature]: Option to insert Tables

### ISSUE THREAD

**Issue by benjamin-wilson** [Sibiraj-S/ngx-editor#67]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [X] Feature request
- [ ] Documentation issue or request

## Description

Allow creation of tables. When sanitizing output of the editor, formatting becomes limited and the addition of tables would greatly increase formatting available to our users.

**Comment by Sibiraj-S** [comment]
@benjamin-wilson I currently don't have time to work on this. I am adding it to backlog and I will work on this later.
