### ISSUE TITLE
[Feature]: Support HTML header tags

### ISSUE THREAD

**Issue by chami007** [sibiraj-s/ngx-editor#70]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [x] Feature request
- [ ] Documentation issue or request

## Description

 Could we add H1, H2, H3 headers as well please ?

**Comment by Sibiraj-S** [comment]
Yeah, Why not. Its already on my task list.

**Comment by danielcarlan** [comment]
Hi @Sibiraj-S ! Any news on this? We're also waiting for this 😄

**Comment by Sibiraj-S** [comment]
Hi, @danielcarlan . I am doing a major re write to ngx-editor and upgrading to Angular 6. I am quite busy recently with someother tasks here and I was unable to spend enough time with it. That will be the next thing I will work on after Upgrade. It will be released along with v4.0
