### ISSUE TITLE
Can't bind to 'config' since it isn't a known property of 'app-ngx-editor'

### ISSUE THREAD

**Issue by morscad** [Sibiraj-S/ngx-editor#71]
I followed the example on the main package page.
1- I added `"ngx-editor": "^3.3.0-rc.9",` to package.json (along with `ngx-bootstrap` and `codemirror`) and then did an npm install

2- in app.module I did `import { NgxEditorModule } from "ngx-editor";` and added NgxEditorModule to `@NgModule({ imports: [NgxEditorModule]})`

3- in one of my component's template I added 
`<app-ngx-editor [spellcheck]="true" [(ngModel)]="replyMessage" [config]="_config"> </app-ngx-editor>`

No compile errors when compiling with angular cli (I am using version 5.2.6), but when I load my app in a browser it gives me this error on start.
where did I go wrong?

```
compiler.js:485 Uncaught Error: Template parse errors:
Can't bind to 'config' since it isn't a known property of 'app-ngx-editor'.
1. If 'app-ngx-editor' is an Angular component and it has 'config' input, then verify that it is part of this module.
2. If 'app-ngx-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
								[(ngModel)]="replyMessage"
								id="description"
								[ERROR ->][config]="wysiwygConfig">
				</app-ngx-editor>

"): ng:///AppRoutesModule/EmailReplyPanel.html@37:8
'app-ngx-editor' is not a known element:
1. If 'app-ngx-editor' is an Angular component, then verify that it is part of this module.
2. If 'app-ngx-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
				[ERROR ->]<app-ngx-editor [spellcheck]="true"
								[(ngModel)]="replyMessage"
								id="description"
"): ng:///AppRoutesModule/EmailReplyPanel.html@34:4
    at syntaxError (compiler.js:485)
    at TemplateParser.webpackJsonp.../../../compiler/esm5/compiler.js.TemplateParser.parse (compiler.js:24668)
    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._parseTemplate (compiler.js:34621)
    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileTemplate (compiler.js:34596)
    at compiler.js:34497
    at Set.forEach (<anonymous>)
    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileComponents (compiler.js:34497)
    at compiler.js:34367
    at Object.then (compiler.js:474)
    at JitCompiler.webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:34366)
syntaxError @ compiler.js:485
webpackJsonp.../../../compiler/esm5/compiler.js.TemplateParser.parse @ compiler.js:24668
webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._parseTemplate @ compiler.js:34621
webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileTemplate @ compiler.js:34596
(anonymous) @ compiler.js:34497
webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileComponents @ compiler.js:34497
(anonymous) @ compiler.js:34367
then @ compiler.js:474
webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler._compileModuleAndComponents @ compiler.js:34366
webpackJsonp.../../../compiler/esm5/compiler.js.JitCompiler.compileModuleAsync @ compiler.js:34260
webpackJsonp.../../../platform-browser-dynamic/esm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAsync @ platform-browser-dynamic.js:239
webpackJsonp.../../../core/esm5/core.js.PlatformRef.bootstrapModule @ core.js:5567
../../../../../src/ts/main-aot.ts @ main-aot.ts:7
__webpack_require__ @ bootstrap 10cdd3045e56e3ac5ff1:54
0 @ SortableTableView.ts:5
__webpack_require__ @ bootstrap 10cdd3045e56e3ac5ff1:54
webpackJsonpCallback @ bootstrap 10cdd3045e56e3ac5ff1:25
(anonymous) @ main.bundle.js:1
```

**Comment by Sibiraj-S** [comment]
Edit the question, follow ISSUE TEMPLATE. Else issue will be closed after 2 days from opening.

**Comment by Sibiraj-S** [comment]
can you provide a simple example like a github repo. where I can replicate the error @morscad

**Comment by morscad** [comment]
Thanks for the quick response.. it's quite a big and complex app with a lot of code that works with our back end system that I cannot share, if this is the only way you can tell what the problem is, I can build a stripped down version of it.

but in essence, the structure is:
1- Main.ts: bootstraps the module `AppModule`
2- AppModule.ts 
- imports NgxEditorModule and AppRoutesModule.ts
- Bootstraps `CoreController` as the main application component

3- AppRoutesModule.ts imports `RouteModule.forRoot([{ path: 'email', component: EmailComponent		            }])` 

4- CoreController has the `<router-outlet></router-outlet>` directive that loads EmailComponent when the url changes, has a button that change route to `/email` on click

5- EmailComponent includes `<app-ngx-editor></app-ngx-editor>` in its template

6- the application is compiled with `ng build --dev --delete-output-path false --watch`

is this descriptive enough or do you still need the code?

**Comment by eduardbraun** [comment]
I am getting the same issue

**Comment by Sibiraj-S** [comment]
@morscad .to reproduce an error You don't have to do that much. Just craft a simple application with `angular-cli` and do what you have done there. That's more than enough.

What ever you tell, I cannot reproduce your exact error you get, as developer there is a change where I might unkownigly implement it correctly (Human mind 😅 )

But I'll try

**Comment by Sibiraj-S** [comment]
@morscad , @eduardbraun . From what versions are you getting this error. Is it a regression or a bug since begining

**Comment by morscad** [comment]
I am working on a stripped down version of my app for you, will be ready in a bit
I am using version `"ngx-editor": "^3.3.0-rc.9",` in my code, and this is the first time I ever used this component so it is not an update

will upload the new files soon

**Comment by Sibiraj-S** [comment]
okay. Just share a gihub repo @morscad

**Comment by eduardbraun** [comment]
if fixed the issue. I had to update my npm packes with npm update --save, then I installed missing dependencies @angular/common and codemirror. That fixed my problem

**Comment by Sibiraj-S** [comment]
Yeah @eduardbraun has a point. delete `lock` file and `npm install`.

Try again.

**Comment by morscad** [comment]
nope, sorry.. a fresh npm install and an npm update didn't work for me. I have the required dependencies in my package file
I will finish the minimal app and deploy it on github for you in a few minutes

**Comment by Sibiraj-S** [comment]
Okay. Lets work it out. If it is a bug and is identified I ll make a release with fix right away.

**Comment by Sibiraj-S** [comment]
@morscad . I made a simple example. following steps exactly as you said. But it seems to not have any problems. Check the attachment

[ngx-editor.zip](https://github.com/Sibiraj-S/ngx-editor/files/1763773/editor-example.zip).

Have you defined the `_config` object in `TS` file?

**Comment by morscad** [comment]
here's the minimal app, same result as the full app.. there is some complexity in the way I am copying external dependency files (which is related to our production flow), but the behavior is the same.
just run `npm install` and then `npm run dev` .. it works on http://localhost:3000

if you go to `src/ts/modules/email/_templates/email_component.html` and uncomment the editor directive, the app will fail on load.. if you keep it in comment it will run fine.

Thanks a lot for your help

[minimalApp.zip](https://github.com/Sibiraj-S/ngx-editor/files/1763864/minimalApp.zip)

**Comment by Sibiraj-S** [comment]
Haha, Simple mistake @morscad .

Import `NgxEditorModule` in `AppRoutesModule.ts`. Everything should work as you expected.


**Simple Rule**: Import a module where the component is imported or use a `sharedModule` and export the modules which you want to use.

Cheers: 🍻

**Comment by morscad** [comment]
Perfect. works like a charm
Thanks a lot for your help, it is much appreciated

cheers

**Comment by Sibiraj-S** [comment]
😄
