### ISSUE TITLE
image uploader not putting image in content

### ISSUE THREAD

**Issue by codechavez** [Sibiraj-S/ngx-editor#75]
# I'm submitting a issue that it seems to be related  when using the image functionality.

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [x] Feature request
- [x] Documentation issue or request

## Description

I'm running a into the issue when using the image upload. After a successful called (file was uploaded to my host), the image is not added to the content. 

### Version Information

```
ngx-editor: 3.3.0-rc.10
angular: 5.2.5
```

### Browser

- [x] Chrome

**Comment by Sibiraj-S** [comment]
@codechavez . Any message from the editor.

What was the response after uploading the image?

**Comment by Sibiraj-S** [comment]
@codechavez. Issue will be closed in 2 days if no response is made.

**Comment by Sibiraj-S** [comment]
@codechavez. Closing as Inactive. 

Feel free to open anytime 🍻

**Comment by charan-r** [comment]
Hello,

I'm encountering this issue where i'm getting success response from backend when I checked it in network tab (Chrome dev tools).
```
{
    "url" : "http://pathOfFile"
}
```
I opened that image path link through browser. I works. But not appended to editor content.

Any help is appreciated, Thanks
