### ISSUE TITLE
[Bug]: The editor does not properly clear its displayed value when re-binding an empty string

### ISSUE THREAD

**Issue by chrisstaley** [Sibiraj-S/ngx-editor#78]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

I have an editor like so:
```html
<form [formGroup]="billNoteTemplateModelForm">
	<app-ngx-editor formControlName="noteHtml"
			[placeholder]="'Enter text here...'"
			[(ngModel)]="noteTemplate.noteHtml"></app-ngx-editor>
</form>
```
The expected behavior is that whenever `noteTemplate.noteHtml` is changed via code, the editor should update its displayed value as well. However, if `noteHtml` is first set to any non-empty-string value, and then back to an empty string, the editor does not update its displayed value properly: it displays both the `placeholder` text and the previous non-empty-string value. It should instead display only the `placeholder` text.

The offending code appears to be the if-statement on [line 199](https://github.com/Sibiraj-S/ngx-editor/blob/391c91503ba3f572cf04a5d442157111e25f2693/src/app/ngx-editor/ngx-editor.component.ts#L199) of `ngx-editor.component.ts`. When the new value is detected to be an empty string, `writeValue()` does not call `refreshView()`.

### Version Information

```
ngx-editor: 3.3.0-rc.10
angular: 5.2.7
```

### Browser

- [X] Chrome - 64.0.3282.186
- [ ]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

**Comment by Sibiraj-S** [comment]
@chrisstaley. Since WriteValue is called twice I had a return statement which is removed now.
