### ISSUE TITLE
[Bug]: Incorrectly matched Button/code

### ISSUE THREAD

**Issue by drc-gcoakley** [sibiraj-s/ngx-editor#80]
# I'm submitting a bug

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

The button labeled 'Paragraph' does not insert an HTML Paragraph tag, which is '&lt;p>'. 
Instead it inserts an HTML Line Break tag '&lt;br>'.

### Version Information

https://ngx-editor.stackblitz.io/  (Currently - v3.3.0-rc.11) 

### Browser

- [ ] Chrome - x.x.x
- [X] Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

**Comment by Sibiraj-S** [comment]
@drc-gcoakley. The total function will be replaced, since it works differently in different browsers.

Also this function is a trivial one.
