### ISSUE TITLE
[Enhance]: Should produce strictly correct HTML.

### ISSUE THREAD

**Issue by drc-gcoakley** [Sibiraj-S/ngx-editor#81]
# I'm submitting an 

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [X] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

Produce strictly valid HTML.  What is produced by this editor does not have proper tags (https://github.com/Sibiraj-S/ngx-editor/issues/80) is uses non-standard tags (&lt;strike> is not a standard tag for HTML 4+), and it tends to place layout tags inside of character formatting tags. 

For an example of that last, text formatting such as bold, italic, etc. tags always seem to include line breaks inside of them despite the fact that the formatting does not affect the line break.
 
1) Create the following document of text--no formatting:
> first line
> second line
2) Make the first line bold. Make the second line italic. So far the HTML output is exactly as expected. 
3) Place the cursor at the end of the first line then press enter. Notice in the HTML output that the BR tag in inside of the bold tags. Backspace to join the lines back together. 
3) Place the cursor at the beginning of the second line then press enter. Notice in the HTML output that the BR tag in inside of the italic tags. 

When producing and editor component that is likely to be used in conjunction with other software I would think it is reasonable to assume such software is likely to want to read the produced output. Not producing strictly correct HTML complicates the use of this editor and thus adoption of it. 

### Version Information

https://ngx-editor.stackblitz.io/  (Currently - v3.3.0-rc.11) 

### Browser

- [ ] Chrome - x.x.x
- [X]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

**Comment by Sibiraj-S** [comment]
@drc-gcoakley . sorry for late reply. These will change as the browser gets updated. Also I don't find it that mandatory to use strict HTML 5 tags yet
