### ISSUE TITLE
[BUG]: Cannot easily turn off superscript and subscript formatting.

### ISSUE THREAD

**Issue by drc-gcoakley** [Sibiraj-S/ngx-editor#82]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

Add any text at the end of the document, select it then click the superscript button. Now, there is no way (that I have found) to add normal text after that--it is all added to the superscript. The same behavior happens with subscripts.

### Version Information

https://ngx-editor.stackblitz.io/  (Currently - v3.3.0-rc.11) 

### Browser

- [ ] Chrome - x.x.x
- [X]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

**Comment by Sibiraj-S** [comment]
@drc-gcoakley. Have you tried cleat formatting option. That should work.

**Comment by drc-gcoakley** [comment]
I have only used the online demo. Is there way to enable that option in the demo?

**Comment by Sibiraj-S** [comment]
yes. it is there already there.

The eraser icon clear's formatting.


Close the issue. If it works

**Comment by drc-gcoakley** [comment]
Clicking on the 'Clear Formatting' button does change the next character to be outside of a superscript or subscript.  I don't find this to be an obvious solution but it does work. Thanks. 
This seems like it would work in other similar situations.
