### ISSUE TITLE
[Bug]: Some editor buttons such as delete redo and undo work on different inputs.

### ISSUE THREAD

**Issue by MBelkhechine** [Sibiraj-S/ngx-editor#84]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

Let's assume you have a name input and just beneath it the ngx-editor. If you write text in the name input and then click on delete from the toolbar, the text in the name input is affected and consequently the last letter is deleted.

Expected behavior: The text in the input name has to remain unchanged.

### Version Information

```
ngx-editor: v3.3.0-rc.11
angular: 4
```

### Browser

It happened on Chrome.
I didn't test on the rest of browsers

**Comment by Sibiraj-S** [comment]
@MBelkhechine . Please do check in other browsers too

**Comment by Sibiraj-S** [comment]
> latest with respect to the date of writing this bug

@MBelkhechine. Don't mention like this. those details will/may be helpful for references in future.

**Comment by Sibiraj-S** [comment]
can you post an example @MBelkhechine  using stackblitz.

**Comment by Sibiraj-S** [comment]
@MBelkhechine . closing as inactive. Feel free to open again
