### ISSUE TITLE
Cascading exponents.

### ISSUE THREAD

**Issue by drc-gcoakley** [Sibiraj-S/ngx-editor#86]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [X] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

I'd actually consider this a bug but, can see an argument for it being an enhancement.

I would like to be able to enter the following expression.
    1 raised to the power of (2 raised to the power of 3).  
When I try this with the toolbar buttons what I get is the first/upper expression in the attached image. The editor treats the superscript action as a toggle like the bold or italic. But, superscripts can be added on top of each other. The same is true of subscripts.

What I want is the second/lower image which I created by editing the HTML source then switching back to the display mode.

![image](https://user-images.githubusercontent.com/26071543/37170290-106765d2-22d0-11e8-87a7-4ea987028643.png)

### Version Information

https://ngx-editor.stackblitz.io/  (Currently - v3.3.0-rc.11) 

### Browser

- [ ] Chrome - x.x.x
- [X]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

**Comment by Sibiraj-S** [comment]
@drc-gcoakley. Thats how it works I guess. The editor makes use of [contenteditable](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content) and [document.execCommand](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand). 

I meant it to be simple with sufficient features. Also the enhancement you asked for is a very rare user scenario. User can always edit the HTML if he requires.


Closing this now and adding it to backlog. 🍻
