### ISSUE TITLE
Image Upload Problem

### ISSUE THREAD

**Issue by barkinkizilkaya** [Sibiraj-S/ngx-editor#88]
ı try to upload image file to asset/image folder ı set imageendpoint but it give me 404 is there any way to upload image file ?

can you give me a sample

**Comment by Sibiraj-S** [comment]
@barkinkizilkaya. 404 states that endpoint isn't available. Can you create a sample repo/something explaining your issue.

**Comment by barkinkizilkaya** [comment]
my component config like this

  editorConfig ={
    "editable": true,
    "spellcheck": true,
    "height": "auto",
    "minHeight": "0",
    "width": "auto",
    "minWidth": "0",
    "translate": "yes",
    "enableToolbar": true,
    "showToolbar": true,
    "placeholder": "Enter text here...",
    **"imageEndPoint": "assets\image",**
    "toolbar": [
        ["bold", "italic", "underline", "strikeThrough", "superscript", "subscript"],
        ["fontSize", "color"],
        ["justifyLeft", "justifyCenter", "justifyRight", "justifyFull", "indent", "outdent"],
        ["cut", "copy", "delete", "removeFormat", "undo", "redo"],
        ["paragraph", "blockquote", "removeBlockquote", "horizontalLine", "orderedList", "unorderedList"],
        ["link", "unlink", "image"],
        ["code"]
    ]
}

**Comment by Sibiraj-S** [comment]
You must provide an HTTP endpoint.

**Comment by barkinkizilkaya** [comment]
how can you sample it. in development evviroment how can ı test  ?

**Comment by Sibiraj-S** [comment]
try something like `http://localhost:80/asstes/image`.

**Comment by barkinkizilkaya** [comment]
when o set url like this "imageEndPoint": "http://localhost:4200/assets/image",

the it give error

ERROR HttpErrorResponse {headers: HttpHeaders, status: 404, statusText: "Not Found", url: "http://localhost:4200/assets/image", ok: false, …}

**Comment by barkinkizilkaya** [comment]
![image](https://user-images.githubusercontent.com/10937356/37405982-20f50d10-27a7-11e8-90c2-33ccf07abe6f.JPG)

**Comment by Sibiraj-S** [comment]
i don't understand.  you have pointed to a folder. I guess. It should be an valid end-point. which can process your images which is sent as form-data.

The back end should be able to handle the image uploaded.

**Comment by Sibiraj-S** [comment]
I thought initially `asstes/image` this as an `HTTP_ENDPOINT`.

**Comment by barkinkizilkaya** [comment]
you mean ngxeditor doesnt enough to upload image ? 

I try to upload an image simply using your editor to a folder.

**Comment by Sibiraj-S** [comment]
You cannot do that. 😕 . Have you ever came across that behavior somewhere

**Comment by barkinkizilkaya** [comment]
yes ı want upload images to the assets\image folder

**Comment by Sibiraj-S** [comment]
You cant do that. It should be an valid HTTP endpoint.  See the docs https://sibiraj-s.github.io/ngx-editor/additional-documentation/image-uploader.html

**Comment by barkinkizilkaya** [comment]
ı check the document how can ı write suitable end point ? can you give a sample it ?

**Comment by Sibiraj-S** [comment]
Are you a beginner?

**Comment by barkinkizilkaya** [comment]
in angular yes.

**Comment by Sibiraj-S** [comment]
leave that to backend guys or google it. you can find a lot of examples.

Thanks for using ngx-editor

**Comment by Yezuz05** [comment]
Hi, I tried to upload an image with the editor and my backend returns the required json format but I keep getting 'range out of editor 'error
