### ISSUE TITLE
[(html)] doesn't work after subscription on Observable

### ISSUE THREAD

**Issue by ssuperczynski** [Sibiraj-S/ngx-editor#9]
Given I have:

```html
<app-ngx-editor
  [spellcheck]="true"
  [(html)]="htmlContent"
  [config]="editorConfig">
</app-ngx-editor>
```

```ts
export class AccessComponent implements OnInit {
  htmlContent = '<h6>Hello</h6>';

  ngOnInit() {
    this.someService.getAction()
      .subscribe(data => {
        this.htmlContent = '<h3>hello world</h3>'; // <-- doesn't work
      });
  }
}
```

Then result is:

![screen shot 2017-11-16 at 14 00 56](https://user-images.githubusercontent.com/6843074/32892470-9c1de4c2-cad6-11e7-8386-d6f2f31e07c2.png)

In `ngx-editor.component.ts` you need to implement `OnChanges` and then:

```ts
ngOnChanges(changes: SimpleChanges) {
  const html: SimpleChange = changes.html;
  if (html) {
    this.html = html.currentValue;
  }
}
```

**Comment by Sibiraj-S** [comment]
> In ngx-editor.component.ts you need to implement OnChanges .

I think there is no need for that. That is why I have used this.


https://github.com/Sibiraj-S/ngx-editor/blob/5af69b9fa035692f8c5f9052464b5400725d53e8/src/app/ngx-editor/ngx-editor.component.ts#L68-L74.

So updating value via `ngOnChanges` is not necessary. I will patch this soon.

**Comment by Sibiraj-S** [comment]
@ssuperczynski . Have you checked now? It is being fixed.

**Comment by ssuperczynski** [comment]
@Sibiraj-S It works. Thank you so much 🚀
