### ISSUE TITLE
[Docs]: Documentation improvement

### ISSUE THREAD

**Issue by tiagoapolo** [Sibiraj-S/ngx-editor#90]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [ ] Feature request
- [x] Documentation issue or request

## Description

Documentation improvement

### Version Information

```
ngx-editor: 3.3.0-rc.13
angular: 5.2.5
```

### Browser

- [x] Chrome - 65.0.3325.162
- [ ]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

### Required dependencies for ngx-editor : 
```
"codemirror"
"font-awesome"
"ngx-bootstrap"
```

### After installing make sure to edit .angular-cli.json adding the required stylesheets: 
```
"styles": [
  "styles.css",
  "../node_modules/font-awesome/css/font-awesome.css",
  "../node_modules/codemirror/lib/codemirror.css"
],
```

**Comment by Sibiraj-S** [comment]
@tiagoapolo . Have you seen this https://sibiraj-s.github.io/ngx-editor/additional-documentation/prerequisites.html ?
