### ISSUE TITLE
[Bug]: ngModel is not working in code mode

### ISSUE THREAD

**Issue by saralamuralikrishna** [Sibiraj-S/ngx-editor#91]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

When in go into view cod mode and make changes the Model binding is not working, the value of the htmlcontent is not updated. 

### Version Information

```
ngx-editor: 3.3.0-rc.13
angular: 5.2.6
```

### Browser

- [x] Chrome - 65.0.3325.162
- [ ]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - 41.16299.248.0

**Comment by Sibiraj-S** [comment]
@saralamuralikrishna . check the demo. Its working https://ngx-editor.stackblitz.io/

**Comment by saralamuralikrishna** [comment]
I had a look at the demo, my assumptions is when I enter some text in the editor it should show at the bottom of the editor but as I can see nothing is shown if I am in the code editor mode as shown below. If am wrong please let me know.

![image](https://user-images.githubusercontent.com/9860533/37641137-e77e421a-2c18-11e8-874f-c0c7679fccf5.png)

**Comment by Sibiraj-S** [comment]
@saralamuralikrishna . I will update once you switch from code editor mode to text editor mode. That's how it works.
