### ISSUE TITLE
[Docs]: Unclear prerequisites - update README

### ISSUE THREAD

**Issue by DenisVuyka** [Sibiraj-S/ngx-editor#92]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [ ] Feature request
- [x] Documentation issue or request

## Description

It is not clear from the main readme that this component requires a bunch of extra libs that are very tricky to configure for a typical Angular project:

    CodeMirror - Code Edit/Preview
    FontAwesome - Toolbar icons
    NgxBootstrap - Popover

Please provide this information for the main README.md and optionally a way to setup everything in a blank Angular CLI project.

**Comment by iamvenkat45** [comment]
Adding above to the existing issue, do we have any option to create custom toolbar ?
Eg: Word highlight or insert shapes etc.. 

Thanks in advance..

**Comment by Sibiraj-S** [comment]
@iamvenkat45 . Nope.
