### ISSUE TITLE
[Feature]: Support Anuglar 4

### ISSUE THREAD

**Issue by ajmeersha** [Sibiraj-S/ngx-editor#93]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [ ] Enhancement
- [x] Feature request
- [ ] Documentation issue or request

## Description

Support Angular 4

### Browser

- [x] Chrome - x.x.x
- [ ]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

**Comment by Sibiraj-S** [comment]
@ajmeersha . That is a valid request but It is not possible. because, Angular 4 has some strict meta information than Angular 5. So you will get Meta Mismatch error, I recommend you to upgrade to Angular 5.

**Comment by ajmeersha** [comment]
yaa but u can make this work from version above 4

**Comment by Sibiraj-S** [comment]
Yes, I already works well with angular 5

**Comment by ajmeersha** [comment]
https://github.com/manishjanky/ngx-pagination-bootstrap/issues/2 can u checkout this issue

**Comment by Sibiraj-S** [comment]
Check what?

**Comment by ajmeersha** [comment]
i raise the same issue for that plugin and he make it work with angular 4 also

**Comment by Sibiraj-S** [comment]
@ajmeersha. Try v1.2.1

**Comment by ajmeersha** [comment]
@Sibiraj-S   still cant able to obtain two-way binding, I pass the value to the htmlContent in the constructor but it won't show in the editor?

**Comment by Sibiraj-S** [comment]
Can you provide a stackblitz of what you have tried

**Comment by Sibiraj-S** [comment]
@ajmeersha . The library you mentioned has been downgraded to Angular 4. But I clearly mentioned on the top what would be the compatibility of the editor,

> A Simple WYSIWYG Editor for Angular5+ Applications.
