### ISSUE TITLE
[Enhance]: Remove the ngx-bootstrap dependency

### ISSUE THREAD

**Issue by Karnich** [sibiraj-s/ngx-editor#95]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report
- [x] Enhancement
- [x] Feature request
- [ ] Documentation issue or request

## Description

Ive been looking for the right editor for my application and i decided to set on yours for the moment because by the looks of the readme the only peer dependency is font-awesome.. which i can live with.. But when trying to use 3.3 i found that ngx-bootstrap also was a peer dependency?

Anyways i found one of the reasons why i continued to move away from an editor while looking for one, was duo to it having dependencies to stuff where i felt like i imported big libraries to support a very small chunk of my application. 

I feel like this editor distinguished itself from the rest by having the lowest amount of dependencies.. it should be its strength.. so adding ngx-bootstrap just puts it inline with the rest?

anyways thats just my two cents :)

for now im using 3.2 which does not have that dependency.

**Comment by jmls** [comment]
ah please, please could you remove this ? I'm just about to ditch using this as I don't use bootstrap, nor do I want to ;)

Are there any instructions for including codemirror in the project ? Or is it just a simple script include in angular-cli ?

**Comment by jmls** [comment]
ah I see in another pr that you are planning to remove codemirror - that would also be great ;) Any eta for these changes ? I have a project that needs markdown, but needs to be out for acceptance testing very soon ...

**Comment by samalexander** [comment]
@sibiraj-s can't we just make ngx-bootstrap a regular dependency? It is only used for the PopoverModule.

**Comment by sibiraj-s** [comment]
Yeah, I am working on it in #166 I faced some issues So I reverted it back. I will work on it. 😄
