### ISSUE TITLE
[BUG] Can't bind to 'placeholder' since it isn't a known property of 'app-ngx-editor'

### ISSUE THREAD

**Issue by abelardolg** [Sibiraj-S/ngx-editor#97]
# I'm submitting a

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report
- [ ] Enhancement
- [ ] Feature request
- [ ] Documentation issue or request

## Description

I installed at the first time this editor inside my project but the below message was displayed.
I previously installed CodeMirror, FontAwesome and NGXBootstrap (popover) projects.

![captura](https://user-images.githubusercontent.com/22522883/38303885-aba41ed6-3807-11e8-8752-a59b301a65b0.PNG)

### Version Information

```
ngx-editor: v3.3.0-rc.13
@angular/cli: 1.7.3
```

### Browser

- [x] Chrome - Versión 64.0.3282.186 (Build oficial) (64 bits)
- [ ]  Mozilla Firefox - x.x.x
- [ ] Opera - x.x.x
- [ ] Microsoft Edge - x.x.x

**Comment by Sibiraj-S** [comment]
I think you have not imported `ngxEditorModule`.

**Comment by abelardolg** [comment]
Hi, 
Yes, I imported NgxEditorModule as well as PopoverModule from NgX-Bootstrap:

import {NgxEditorModule} from 'ngx-editor';
import { PopoverModule } from 'ngx-bootstrap/popover';

![image](https://user-images.githubusercontent.com/22522883/38304609-53651470-380a-11e8-98f7-125a6d2f957d.png)

**Comment by abelardolg** [comment]
I am including it in a feature module but I don't think it is a problem.

**Comment by abelardolg** [comment]
I will check it out and I will return it back. :) :+1:  Thanks for your support and time! Priceless.

**Comment by Sibiraj-S** [comment]
Check #71. There is a similar issue.
