### ISSUE TITLE
Image Upload from the editor

### ISSUE THREAD

**Issue by sanketnaik99** [Sibiraj-S/ngx-editor#98]
Hey, I've been having problems implementing the image upload feature using an ImageEndpoint. Could you show a working demo since the demo on stackblitz.io doesn't seem to work. I'm getting the same error as the demo.

**Comment by Sibiraj-S** [comment]
HI @sanketnaik99 , The endpoint is not specified in the demo, If you get the same error, you might not have specified it too.  Check https://sibiraj-s.github.io/ngx-editor/additional-documentation/image-uploader.html

**Comment by sanketnaik99** [comment]
I've specified the demo as the link to my firebase storage (uses REST API). Still won't work.

**Comment by Sibiraj-S** [comment]
Can you post the error you get? or a small implementation?

**Comment by sanketnaik99** [comment]
The progress bar goes from 0 to 100 and then returns an error saying cannot read property url of 'null'

**Comment by sanketnaik99** [comment]
Could you just show how you would do it by using an actual image endpoint?

**Comment by Sibiraj-S** [comment]
I guess the image is getting uploaded, but the response isn't as expected. The response  should be a json like 

```json
{
    "url": "https://location-where-image-uploaded"
}
```

**Comment by sanketnaik99** [comment]
Is there any way to solve that? I'm using angularfire2 to connect to my firebase database

**Comment by Sibiraj-S** [comment]
so, what does it return actually. The editor needs a URL of the image to be inserted.

**Comment by Sibiraj-S** [comment]
@sanketnaik99 . Considered this not as a BUG./FR, Closing this. But Feel free to comment/continue the discussion.
